import { CalculatorContent } from '@/types/calculator';

export const phq9Content: CalculatorContent = {
  en: {
    whatIs:
      'The Patient Health Questionnaire-9 (PHQ-9) is a widely used, validated screening tool designed to assess the presence and severity of depression based on the diagnostic criteria for major depressive disorder from the DSM-IV (Diagnostic and Statistical Manual of Mental Disorders, Fourth Edition). Developed by Drs. Robert Spitzer, Janet Williams, and Kurt Kroenke in 1999, the PHQ-9 consists of nine questions that correspond directly to the nine DSM criteria for diagnosing major depression. Each question asks about symptoms experienced over the past two weeks, including depressed mood, loss of interest or pleasure (anhedonia), sleep disturbances, fatigue, appetite changes, feelings of worthlessness or guilt, difficulty concentrating, psychomotor agitation or retardation, and thoughts of death or self-harm. Respondents rate each symptom on a scale from 0 (not at all) to 3 (nearly every day), yielding a total score ranging from 0 to 27. The PHQ-9 is brief, taking only 2-3 minutes to complete, making it practical for use in primary care settings, mental health clinics, research studies, and even self-assessment. Scores are interpreted as follows: 0-4 indicates minimal or no depression, 5-9 suggests mild depression, 10-14 indicates moderate depression, 15-19 suggests moderately severe depression, and 20-27 indicates severe depression. Beyond screening, the PHQ-9 can be used to monitor treatment response over time, as decreasing scores indicate symptom improvement. A unique and critical feature of the PHQ-9 is question 9, which directly assesses suicidal ideation by asking about thoughts of being better off dead or of hurting oneself. Any positive response to this question warrants immediate further evaluation and safety planning, regardless of the total score.',

    howToCalculate:
      'Calculating the PHQ-9 score is straightforward and involves summing the individual item scores. The questionnaire contains nine items, each corresponding to a DSM-IV criterion for major depressive disorder. For each question, respondents indicate how often they have been bothered by each symptom over the past two weeks using the following scale: 0 = Not at all, 1 = Several days, 2 = More than half the days, 3 = Nearly every day. The nine symptoms assessed are: (1) Little interest or pleasure in doing things, (2) Feeling down, depressed, or hopeless, (3) Trouble falling or staying asleep, or sleeping too much, (4) Feeling tired or having little energy, (5) Poor appetite or overeating, (6) Feeling bad about yourself - or that you are a failure or have let yourself or your family down, (7) Trouble concentrating on things, such as reading the newspaper or watching television, (8) Moving or speaking so slowly that other people could have noticed, or being so fidgety or restless that you have been moving around a lot more than usual, (9) Thoughts that you would be better off dead, or of hurting yourself in some way. To obtain the total PHQ-9 score, simply add up the scores for all nine questions. For example, if a person answers: 2, 2, 1, 3, 1, 2, 1, 0, 0, the total score would be 2+2+1+3+1+2+1+0+0 = 12, indicating moderate depression. In addition to the total score, clinicians often assess functional impairment using a tenth question (not counted in the score) that asks how difficult the symptoms have made it to work, take care of things at home, or get along with others. Response options are: not difficult at all, somewhat difficult, very difficult, or extremely difficult. The presence of functional impairment, combined with the total score, helps determine the clinical significance of depressive symptoms and guides treatment decisions.',

    interpretation:
      'PHQ-9 scores are interpreted according to established severity ranges that have been validated in numerous studies across diverse populations. A score of 0-4 indicates minimal or no depression, suggesting that the individual is likely not experiencing clinically significant depressive symptoms. Scores of 5-9 suggest mild depression, which may benefit from watchful waiting, patient education, and follow-up reassessment in 2-4 weeks. If symptoms persist or worsen, treatment such as psychotherapy may be considered. Scores of 10-14 indicate moderate depression, typically warranting active treatment with psychotherapy (such as cognitive behavioral therapy or interpersonal therapy), antidepressant medication, or both, depending on patient preference and clinical judgment. Scores of 15-19 suggest moderately severe depression, which generally requires active treatment combining both medication and psychotherapy for optimal outcomes. Scores of 20-27 indicate severe depression, necessitating immediate initiation of pharmacotherapy and/or psychotherapy, and consideration of specialty mental health referral or even hospitalization if there is acute safety risk. It is crucial to note that interpretation should never rely solely on the total score. Question 9, which assesses suicidal ideation, requires special attention. Any score greater than 0 on question 9 (indicating thoughts of death or self-harm on several days or more) should trigger immediate suicide risk assessment, safety planning, and appropriate intervention, potentially including emergency psychiatric evaluation, regardless of the overall score. Additionally, the PHQ-9 should be interpreted in clinical context, considering factors such as recent life stressors, medical conditions that can mimic or contribute to depression (hypothyroidism, anemia, chronic pain, neurological disorders), substance use, and response to previous treatments. The PHQ-9 is a screening tool, not a diagnostic instrument - a positive screen should lead to comprehensive clinical assessment to confirm the diagnosis and develop an individualized treatment plan.',

    medicalDisclaimer:
      'This PHQ-9 calculator is provided for educational, informational, and screening purposes only and must never be used as a substitute for professional mental health evaluation, diagnosis, or treatment. The PHQ-9 is a screening tool designed to identify possible depression and assess symptom severity, but it cannot diagnose depression or any other mental health condition. A formal diagnosis of major depressive disorder or other psychiatric conditions requires comprehensive clinical assessment by a qualified mental health professional, including detailed psychiatric interview, evaluation of symptom duration and functional impairment, consideration of differential diagnoses, and assessment for co-occurring conditions. Self-administration of the PHQ-9 without professional guidance can lead to misinterpretation and inappropriate self-treatment. Never make decisions about starting, stopping, or changing psychiatric medications based solely on PHQ-9 scores without consulting a psychiatrist, physician, or other qualified healthcare provider. If you are experiencing thoughts of death, suicide, or self-harm (indicated by any response other than "not at all" to question 9), seek immediate help by calling emergency services (911 in the US), the National Suicide Prevention Lifeline (988 in the US), or going to the nearest emergency room. Depression is a treatable medical condition, and effective treatments including psychotherapy and medication are available. Do not delay seeking professional help if you are struggling with symptoms of depression, anxiety, or other mental health concerns. This tool does not replace consultation with psychiatrists, psychologists, licensed clinical social workers, licensed professional counselors, or other mental health professionals who can provide comprehensive evaluation, accurate diagnosis, evidence-based treatment, and ongoing monitoring.',

    references: [
      'Kroenke K, Spitzer RL, Williams JB. The PHQ-9: validity of a brief depression severity measure. J Gen Intern Med. 2001;16(9):606-613.',
      'American Psychiatric Association. Diagnostic and Statistical Manual of Mental Disorders, 5th Edition (DSM-5). Arlington, VA: American Psychiatric Publishing; 2013.',
      'Manea L, Gilbody S, McMillan D. Optimal cut-off score for diagnosing depression with the Patient Health Questionnaire (PHQ-9): a meta-analysis. CMAJ. 2012;184(3):E191-196.',
      'Kroenke K, Spitzer RL. The PHQ-9: A new depression diagnostic and severity measure. Psychiatr Ann. 2002;32(9):509-515.',
      'Löwe B, et al. Monitoring depression treatment outcomes with the Patient Health Questionnaire-9. Med Care. 2004;42(12):1194-1201.',
    ],

    tips: [
      'Answer all questions honestly based on how you have actually been feeling over the past two weeks, not how you think you should feel or how you felt in the distant past',
      'If question 9 (thoughts of death or self-harm) receives any score other than 0, seek immediate professional help - contact a mental health crisis line, emergency services, or go to an emergency room',
      'The PHQ-9 can be used repeatedly to monitor symptoms over time - take it every 2-4 weeks during treatment to track whether symptoms are improving',
      'Share your PHQ-9 results with your healthcare provider to facilitate conversation about mental health and treatment options',
      'Remember that depression is highly treatable - effective treatments include psychotherapy (such as cognitive behavioral therapy or interpersonal therapy), medication (antidepressants), or combination approaches',
      'A high score does not mean weakness or failure - depression is a medical condition with biological, psychological, and social components',
      'Lifestyle factors can help manage depression alongside professional treatment: regular exercise, adequate sleep, healthy nutrition, social connection, and stress management techniques',
      'If your score indicates moderate to severe depression, do not try to manage it alone - reach out to a mental health professional for comprehensive evaluation and treatment planning',
    ],

    faqs: [
      {
        question: 'What score on the PHQ-9 indicates clinical depression?',
        answer:
          'While there is no absolute cutoff, a PHQ-9 score of 10 or higher is commonly used as the threshold for clinically significant depression that may warrant treatment. Scores of 10-14 suggest moderate depression, 15-19 indicate moderately severe depression, and 20-27 reflect severe depression. However, the interpretation should consider clinical context. Some individuals with scores of 8-9 may have clinically significant depression if symptoms cause substantial functional impairment or distress, while others with scores of 10-12 may not meet full diagnostic criteria for major depressive disorder if symptoms have been present for less than two weeks or if they are better explained by grief, medical illness, or situational stressors. The PHQ-9 is a screening tool that identifies individuals who need further evaluation - a comprehensive clinical assessment by a mental health professional is required to make a formal diagnosis of depression.',
      },
      {
        question: 'How often should I take the PHQ-9?',
        answer:
          'The frequency of PHQ-9 administration depends on the purpose and clinical situation. For initial screening in primary care or other settings, a single administration is sufficient to identify potential depression requiring further evaluation. For individuals undergoing treatment for depression, the PHQ-9 should be administered regularly to monitor treatment response - typically every 2-4 weeks during the acute treatment phase. Research shows that repeated measurement and feedback of PHQ-9 scores to both patients and providers improves treatment outcomes. Once depression has improved and the patient is in the maintenance phase, less frequent administration (every 2-3 months) may be appropriate to monitor for relapse. For self-monitoring, individuals may choose to complete the PHQ-9 weekly or biweekly to track their symptoms, but should always share results with their healthcare provider and not rely on self-assessment alone for treatment decisions.',
      },
      {
        question: 'Can the PHQ-9 diagnose other mental health conditions besides depression?',
        answer:
          'No, the PHQ-9 is specifically designed to screen for major depressive disorder and does not diagnose other mental health conditions. However, depression frequently co-occurs with other psychiatric disorders including anxiety disorders (generalized anxiety disorder, panic disorder, social anxiety), post-traumatic stress disorder (PTSD), bipolar disorder, substance use disorders, and eating disorders. An elevated PHQ-9 score should prompt evaluation for these co-occurring conditions as well. Additionally, some symptoms on the PHQ-9 (such as sleep disturbance, concentration problems, and psychomotor changes) can occur in other conditions. For comprehensive mental health assessment, healthcare providers may use additional screening tools such as the GAD-7 for anxiety, the Mood Disorder Questionnaire (MDQ) for bipolar disorder, or structured clinical interviews. If you have concerns about anxiety, mood swings, trauma, or other mental health issues in addition to or instead of depression, discuss these with a mental health professional.',
      },
      {
        question: 'What should I do if I score high on question 9 about thoughts of death or self-harm?',
        answer:
          'Any positive response to question 9 (indicating thoughts of death or self-harm on several days, more than half the days, or nearly every day) requires immediate action. First, recognize that having these thoughts does not mean you are weak or broken - they are symptoms of depression that can be treated. Do not wait or try to handle these thoughts alone. Seek immediate help through one of these options: (1) Call the National Suicide Prevention Lifeline at 988 (available 24/7 in the United States), (2) Call emergency services (911), (3) Go to the nearest emergency room, (4) Contact a mental health crisis line in your area, (5) Reach out to your therapist, psychiatrist, or primary care doctor immediately. While waiting for help, stay with someone you trust and remove access to means of self-harm (firearms, medications, sharp objects). If you are supporting someone who endorsed question 9, do not leave them alone, take their thoughts seriously, listen without judgment, and help them access professional help immediately. Suicidal thoughts are a medical emergency requiring immediate professional intervention - effective treatments are available and most people who receive help can recover and go on to live fulfilling lives.',
      },
      {
        question: 'Is the PHQ-9 accurate for everyone, including different age groups and cultures?',
        answer:
          'The PHQ-9 has been extensively validated across diverse populations and has shown good reliability and validity in various age groups, cultural backgrounds, and languages. However, some considerations apply. For adolescents, a modified version called the PHQ-9 Modified for Teens (PHQ-A) may be more appropriate, as it uses language better suited to younger individuals. For elderly populations, the PHQ-9 remains valid, though some somatic symptoms (fatigue, sleep changes, appetite changes) may be more common due to aging or medical conditions, potentially leading to false positives. Cultural factors can influence symptom expression and reporting - some cultures may be more likely to report somatic symptoms (physical complaints) rather than emotional symptoms of depression, while others may have stigma around mental health that affects honest reporting. The PHQ-9 has been translated into many languages and validated in many countries, but cultural adaptation beyond simple translation may be needed for optimal performance. Despite these considerations, the PHQ-9 remains one of the most well-validated and widely applicable depression screening tools available. For specific populations or when cultural factors are relevant, interpretation should be done by clinicians familiar with cultural considerations in mental health assessment.',
      },
    ],
  },
  tr: {
    whatIs:
      'Hasta Sağlığı Anketi-9 (PHQ-9), DSM-IV\'ten (Ruhsal Bozuklukların Tanısal ve İstatistiksel El Kitabı, Dördüncü Baskı) majör depresif bozukluk için tanı kriterlerine dayalı olarak depresyonun varlığını ve şiddetini değerlendirmek için tasarlanmış, yaygın olarak kullanılan, doğrulanmış bir tarama aracıdır. 1999\'da Dr. Robert Spitzer, Janet Williams ve Kurt Kroenke tarafından geliştirilen PHQ-9, majör depresyonu teşhis etmek için dokuz DSM kriterine doğrudan karşılık gelen dokuz sorudan oluşur. Her soru, depresif ruh hali, ilgi veya zevk kaybı (anhedoni), uyku bozuklukları, yorgunluk, iştah değişiklikleri, değersizlik veya suçluluk duyguları, konsantrasyon güçlüğü, psikomotor ajitasyon veya gerilik ve ölüm veya kendine zarar verme düşünceleri dahil olmak üzere son iki hafta içinde yaşanan semptomlar hakkında sorar. Yanıtlayanlar her semptomu 0\'dan (hiç) 3\'e (neredeyse her gün) kadar bir ölçekte değerlendirir ve 0 ile 27 arasında değişen toplam bir puan verir. PHQ-9 kısadır, tamamlanması yalnızca 2-3 dakika sürer, bu da birinci basamak sağlık ortamlarında, ruh sağlığı kliniklerinde, araştırma çalışmalarında ve hatta kendini değerlendirmede kullanım için pratik hale getirir. Puanlar şu şekilde yorumlanır: 0-4 minimal veya depresyon olmadığını gösterir, 5-9 hafif depresyon önerir, 10-14 orta derecede depresyon gösterir, 15-19 orta derecede şiddetli depresyon önerir ve 20-27 şiddetli depresyon gösterir. Taramanın ötesinde, PHQ-9 zaman içinde tedavi yanıtını izlemek için kullanılabilir, çünkü azalan puanlar semptom iyileşmesini gösterir. PHQ-9\'un benzersiz ve kritik bir özelliği, ölmüş olmak veya kendine zarar vermek hakkında düşünceler sorarak intihar düşüncesini doğrudan değerlendiren 9. sorudur. Bu soruya verilen herhangi bir olumlu yanıt, toplam puandan bağımsız olarak derhal daha fazla değerlendirme ve güvenlik planlaması gerektirir.',

    howToCalculate:
      'PHQ-9 puanını hesaplamak basittir ve bireysel öğe puanlarını toplamayı içerir. Anket, her biri majör depresif bozukluk için bir DSM-IV kriterine karşılık gelen dokuz öğe içerir. Her soru için, yanıtlayanlar son iki hafta içinde her semptomdan ne sıklıkla rahatsız olduklarını şu ölçeği kullanarak belirtirler: 0 = Hiç, 1 = Birkaç gün, 2 = Günlerin yarısından fazlası, 3 = Neredeyse her gün. Değerlendirilen dokuz semptom şunlardır: (1) Bir şeyler yapmaya çok az ilgi veya zevk duymak, (2) Kendini üzgün, depresif veya umutsuz hissetmek, (3) Uykuya dalmada veya uykuda kalmada sorun veya çok fazla uyumak, (4) Kendini yorgun hissetmek veya çok az enerjiye sahip olmak, (5) Kötü iştah veya aşırı yeme, (6) Kendin hakkında kötü hissetmek - ya da başarısız olduğunu veya kendini veya aileni hayal kırıklığına uğrattığını düşünmek, (7) Gazete okumak veya televizyon izlemek gibi şeylere konsantre olmakta güçlük, (8) Diğer insanların fark edebileceği kadar yavaş hareket etmek veya konuşmak, ya da normalden çok daha fazla hareket edecek kadar tedirgin veya huzursuz olmak, (9) Ölmüş olmanın daha iyi olacağını veya bir şekilde kendine zarar vermeyi düşünmek. Toplam PHQ-9 puanını elde etmek için, tüm dokuz sorunun puanlarını toplamanız yeterlidir. Örneğin, bir kişi şöyle cevap verirse: 2, 2, 1, 3, 1, 2, 1, 0, 0, toplam puan 2+2+1+3+1+2+1+0+0 = 12 olur ve orta derecede depresyon gösterir. Toplam puana ek olarak, klinisyenler genellikle semptomların çalışmayı, evde işleri halletmeyi veya başkalarıyla geçinmeyi ne kadar zorlaştırdığını soran onuncu bir soru (puanda sayılmaz) kullanarak fonksiyonel bozulmayı değerlendirirler. Yanıt seçenekleri şunlardır: hiç zor değil, biraz zor, çok zor veya aşırı derecede zor. Fonksiyonel bozulmanın varlığı, toplam puanla birleştiğinde depresif semptomların klinik önemini belirlemeye yardımcı olur ve tedavi kararlarına rehberlik eder.',

    interpretation:
      'PHQ-9 puanları, çeşitli popülasyonlarda çok sayıda çalışmada doğrulanmış belirlenmiş şiddet aralıklarına göre yorumlanır. 0-4 puan minimal veya depresyon olmadığını gösterir ve bireyin klinik olarak önemli depresif semptomlar yaşamadığını önerir. 5-9 puan hafif depresyon önerir, bu dikkatli izleme, hasta eğitimi ve 2-4 hafta içinde takip yeniden değerlendirmeden faydalanabilir. Semptomlar devam ederse veya kötüleşirse, psikoterapi gibi tedaviler düşünülebilir. 10-14 puan orta derecede depresyon gösterir, tipik olarak hasta tercihi ve klinik yargıya bağlı olarak psikoterapi (bilişsel davranışçı terapi veya kişilerarası terapi gibi), antidepresan ilaç veya her ikisi ile aktif tedavi gerektirir. 15-19 puan orta derecede şiddetli depresyon önerir, bu genellikle optimal sonuçlar için hem ilaç hem de psikoterapiyi birleştiren aktif tedavi gerektirir. 20-27 puan şiddetli depresyon gösterir, farmakoterapi ve/veya psikoterapinin derhal başlatılmasını ve akut güvenlik riski varsa uzmanlık ruh sağlığı sevki veya hatta hastaneye yatış düşünülmesini gerektirir. Yorumlamanın asla yalnızca toplam puana güvenmemesi gerektiğini not etmek önemlidir. İntihar düşüncesini değerlendiren 9. soru özel dikkat gerektirir. 9. soruda 0\'dan büyük herhangi bir puan (birkaç gün veya daha fazla ölüm veya kendine zarar verme düşüncelerini belirtir), genel puandan bağımsız olarak, acil psikiyatrik değerlendirme dahil olmak üzere derhal intihar riski değerlendirmesi, güvenlik planlaması ve uygun müdahaleyi tetiklemelidir. Ek olarak, PHQ-9 klinik bağlamda, son yaşam stresörleri, depresyonu taklit edebilecek veya depresyona katkıda bulunabilecek tıbbi durumlar (hipotiroidizm, anemi, kronik ağrı, nörolojik bozukluklar), madde kullanımı ve önceki tedavilere yanıt gibi faktörler göz önünde bulundurularak yorumlanmalıdır. PHQ-9 bir tarama aracıdır, tanı aracı değildir - pozitif bir tarama, teşhisi doğrulamak ve bireyselleştirilmiş bir tedavi planı geliştirmek için kapsamlı klinik değerlendirmeye yol açmalıdır.',

    medicalDisclaimer:
      'Bu PHQ-9 hesaplayıcı yalnızca eğitim, bilgilendirme ve tarama amaçlıdır ve asla profesyonel ruh sağlığı değerlendirmesi, teşhis veya tedavinin yerine kullanılmamalıdır. PHQ-9, olası depresyonu belirlemek ve semptom şiddetini değerlendirmek için tasarlanmış bir tarama aracıdır, ancak depresyonu veya başka bir ruh sağlığı durumunu teşhis edemez. Majör depresif bozukluk veya diğer psikiyatrik durumların resmi teşhisi, ayrıntılı psikiyatrik görüşme, semptom süresi ve fonksiyonel bozulma değerlendirmesi, ayırıcı tanıların göz önünde bulundurulması ve eşlik eden durumların değerlendirilmesi dahil olmak üzere kalifiye bir ruh sağlığı profesyoneli tarafından kapsamlı klinik değerlendirme gerektirir. Profesyonel rehberlik olmadan PHQ-9\'un kendi kendine uygulanması yanlış yorumlamaya ve uygunsuz kendi kendine tedaviye yol açabilir. Yalnızca PHQ-9 puanlarına dayanarak bir psikiyatrist, doktor veya başka bir kalifiye sağlık hizmeti sağlayıcısına danışmadan psikiyatrik ilaçları başlatma, durdurma veya değiştirme konusunda asla karar vermeyin. Ölüm, intihar veya kendine zarar verme düşünceleri yaşıyorsanız (9. soruya "hiç" dışında herhangi bir yanıtla gösterilir), acil servisleri (ABD\'de 911), Ulusal İntihar Önleme Yaşam Hattı\'nı (ABD\'de 988) arayarak veya en yakın acil servise giderek derhal yardım isteyin. Depresyon tedavi edilebilir bir tıbbi durumdur ve psikoterapi ve ilaç dahil olmak üzere etkili tedaviler mevcuttur. Depresyon, kaygı veya diğer ruh sağlığı endişelerinin semptomlarıyla mücadele ediyorsanız profesyonel yardım aramayı geciktirmeyin. Bu araç, kapsamlı değerlendirme, doğru teşhis, kanıta dayalı tedavi ve devam eden izleme sağlayabilen psikiyatristler, psikologlar, lisanslı klinik sosyal hizmet uzmanları, lisanslı profesyonel danışmanlar veya diğer ruh sağlığı profesyonelleriyle konsültasyonun yerini almaz.',

    references: [
      'Kroenke K, Spitzer RL, Williams JB. PHQ-9: kısa bir depresyon şiddeti ölçüsünün geçerliliği. J Gen Intern Med. 2001;16(9):606-613.',
      'Amerikan Psikiyatri Birliği. Ruhsal Bozuklukların Tanısal ve İstatistiksel El Kitabı, 5. Baskı (DSM-5). Arlington, VA: American Psychiatric Publishing; 2013.',
      'Manea L, Gilbody S, McMillan D. Hasta Sağlığı Anketi (PHQ-9) ile depresyonu teşhis etmek için optimal kesme puanı: bir meta-analiz. CMAJ. 2012;184(3):E191-196.',
      'Kroenke K, Spitzer RL. PHQ-9: Yeni bir depresyon tanısı ve şiddet ölçüsü. Psychiatr Ann. 2002;32(9):509-515.',
      'Löwe B, ve ark. Hasta Sağlığı Anketi-9 ile depresyon tedavi sonuçlarını izleme. Med Care. 2004;42(12):1194-1201.',
    ],

    tips: [
      'Tüm soruları, nasıl hissetmeniz gerektiğine veya uzak geçmişte nasıl hissettiğinize göre değil, son iki hafta içinde gerçekte nasıl hissettiğinize göre dürüstçe cevaplayın',
      '9. soru (ölüm veya kendine zarar verme düşünceleri) 0 dışında herhangi bir puan alırsa, derhal profesyonel yardım isteyin - bir ruh sağlığı kriz hattını, acil servisleri arayın veya acil servise gidin',
      'PHQ-9, zaman içinde semptomları izlemek için tekrar tekrar kullanılabilir - semptomların iyileşip iyileşmediğini takip etmek için tedavi sırasında her 2-4 haftada bir alın',
      'Ruh sağlığı ve tedavi seçenekleri hakkında konuşmayı kolaylaştırmak için PHQ-9 sonuçlarınızı sağlık hizmeti sağlayıcınızla paylaşın',
      'Depresyonun oldukça tedavi edilebilir olduğunu unutmayın - etkili tedaviler psikoterapi (bilişsel davranışçı terapi veya kişilerarası terapi gibi), ilaç (antidepresanlar) veya kombinasyon yaklaşımlarını içerir',
      'Yüksek bir puan zayıflık veya başarısızlık anlamına gelmez - depresyon biyolojik, psikolojik ve sosyal bileşenlere sahip bir tıbbi durumdur',
      'Yaşam tarzı faktörleri profesyonel tedavinin yanı sıra depresyonu yönetmeye yardımcı olabilir: düzenli egzersiz, yeterli uyku, sağlıklı beslenme, sosyal bağlantı ve stres yönetimi teknikleri',
      'Puanınız orta ila şiddetli depresyon gösteriyorsa, bunu tek başınıza yönetmeye çalışmayın - kapsamlı değerlendirme ve tedavi planlaması için bir ruh sağlığı profesyoneline ulaşın',
    ],

    faqs: [
      {
        question: 'PHQ-9\'da hangi puan klinik depresyonu gösterir?',
        answer:
          'Mutlak bir kesme noktası olmasa da, PHQ-9 puanı 10 veya daha yüksek genellikle tedavi gerektirebilecek klinik olarak önemli depresyon için eşik olarak kullanılır. 10-14 puan orta derecede depresyon, 15-19 orta derecede şiddetli depresyon ve 20-27 şiddetli depresyonu yansıtır. Ancak, yorum klinik bağlamı dikkate almalıdır. 8-9 puan alan bazı bireyler, semptomlar önemli fonksiyonel bozulmaya veya sıkıntıya neden oluyorsa klinik olarak önemli depresyona sahip olabilirken, semptomlar iki haftadan daha kısa süre boyunca mevcutsa veya yas, tıbbi hastalık veya durumsal stresörlerle daha iyi açıklanıyorsa 10-12 puan alan diğerleri majör depresif bozukluk için tam tanı kriterlerini karşılamayabilir. PHQ-9, daha fazla değerlendirmeye ihtiyaç duyan bireyleri belirleyen bir tarama aracıdır - resmi bir depresyon teşhisi koymak için bir ruh sağlığı profesyoneli tarafından kapsamlı bir klinik değerlendirme gereklidir.',
      },
      {
        question: 'PHQ-9\'u ne sıklıkla almalıyım?',
        answer:
          'PHQ-9 uygulamasının sıklığı amaca ve klinik duruma bağlıdır. Birinci basamak veya diğer ortamlarda ilk tarama için, daha fazla değerlendirme gerektiren potansiyel depresyonu belirlemek için tek bir uygulama yeterlidir. Depresyon için tedavi gören bireyler için, tedavi yanıtını izlemek için PHQ-9 düzenli olarak uygulanmalıdır - tipik olarak akut tedavi aşamasında her 2-4 haftada bir. Araştırmalar, PHQ-9 puanlarının hem hastalara hem de sağlayıcılara tekrarlanan ölçümü ve geri bildiriminin tedavi sonuçlarını iyileştirdiğini göstermektedir. Depresyon iyileştikten ve hasta bakım aşamasında olduğunda, nüks için izleme için daha az sıklıkta uygulama (her 2-3 ayda bir) uygun olabilir. Kendi kendini izleme için, bireyler semptomlarını takip etmek için haftalık veya iki haftada bir PHQ-9\'u tamamlamayı seçebilir, ancak sonuçları her zaman sağlık hizmeti sağlayıcılarıyla paylaşmalı ve tedavi kararları için yalnızca kendini değerlendirmeye güvenmemelidir.',
      },
      {
        question: 'PHQ-9 depresyonun yanı sıra diğer ruh sağlığı durumlarını teşhis edebilir mi?',
        answer:
          'Hayır, PHQ-9 özellikle majör depresif bozukluğu taramak için tasarlanmıştır ve diğer ruh sağlığı durumlarını teşhis etmez. Ancak, depresyon sıklıkla anksiyete bozuklukları (jeneralize anksiyete bozukluğu, panik bozukluğu, sosyal anksiyete), travma sonrası stres bozukluğu (TSSB), bipolar bozukluk, madde kullanım bozuklukları ve yeme bozuklukları dahil diğer psikiyatrik bozukluklarla birlikte görülür. Yüksek bir PHQ-9 puanı, bu eşlik eden durumların da değerlendirilmesini istemelidir. Ek olarak, PHQ-9\'daki bazı semptomlar (uyku bozukluğu, konsantrasyon sorunları ve psikomotor değişiklikler gibi) diğer durumlarda da ortaya çıkabilir. Kapsamlı ruh sağlığı değerlendirmesi için, sağlık hizmeti sağlayıcıları anksiyete için GAD-7, bipolar bozukluk için Duygudurum Bozukluğu Anketi (MDQ) veya yapılandırılmış klinik görüşmeler gibi ek tarama araçları kullanabilir. Depresyona ek olarak veya yerine anksiyete, ruh hali değişiklikleri, travma veya diğer ruh sağlığı sorunları hakkında endişeleriniz varsa, bunları bir ruh sağlığı profesyoneli ile tartışın.',
      },
      {
        question: 'Ölüm veya kendine zarar verme düşünceleri hakkındaki 9. soruda yüksek puan alırsam ne yapmalıyım?',
        answer:
          '9. soruya herhangi bir olumlu yanıt (birkaç gün, günlerin yarısından fazlası veya neredeyse her gün ölüm veya kendine zarar verme düşüncelerini belirtir) derhal harekete geçilmesini gerektirir. İlk olarak, bu düşüncelere sahip olmanın zayıf veya kırık olduğunuz anlamına gelmediğini kabul edin - bunlar tedavi edilebilecek depresyon semptomlarıdır. Beklemeyin veya bu düşünceleri tek başınıza halletmeye çalışmayın. Şu seçeneklerden biri aracılığıyla derhal yardım isteyin: (1) Ulusal İntihar Önleme Yaşam Hattı\'nı 988\'de arayın (Amerika Birleşik Devletleri\'nde 7/24 kullanılabilir), (2) Acil servisleri arayın (911), (3) En yakın acil servise gidin, (4) Bölgenizdeki bir ruh sağlığı kriz hattıyla iletişime geçin, (5) Terapistinize, psikiyatristinize veya birinci basamak doktorunuza derhal ulaşın. Yardım beklerken, güvendiğiniz biriyle kalın ve kendine zarar verme araçlarına erişimi kaldırın (ateşli silahlar, ilaçlar, keskin nesneler). 9. soruyu onaylayan birini destekliyorsanız, onları yalnız bırakmayın, düşüncelerini ciddiye alın, yargılamadan dinleyin ve profesyonel yardıma erişmelerine yardımcı olun. İntihar düşünceleri derhal profesyonel müdahale gerektiren bir tıbbi acil durumdur - etkili tedaviler mevcuttur ve yardım alan çoğu insan iyileşebilir ve tatmin edici hayatlar yaşamaya devam edebilir.',
      },
      {
        question: 'PHQ-9 farklı yaş grupları ve kültürler dahil herkes için doğru mu?',
        answer:
          'PHQ-9, çeşitli popülasyonlarda kapsamlı bir şekilde doğrulanmıştır ve çeşitli yaş gruplarında, kültürel geçmişlerde ve dillerde iyi güvenilirlik ve geçerlilik göstermiştir. Ancak, bazı hususlar geçerlidir. Ergenler için, PHQ-9 Gençler İçin Değiştirilmiş (PHQ-A) adlı değiştirilmiş bir versiyon daha uygun olabilir, çünkü daha genç bireylere daha uygun dil kullanır. Yaşlı popülasyonlar için, PHQ-9 geçerli kalır, ancak bazı somatik semptomlar (yorgunluk, uyku değişiklikleri, iştah değişiklikleri) yaşlanma veya tıbbi durumlar nedeniyle daha yaygın olabilir ve potansiyel olarak yanlış pozitiflere yol açabilir. Kültürel faktörler semptom ifadesini ve raporlamayı etkileyebilir - bazı kültürler depresyonun duygusal semptomları yerine somatik semptomları (fiziksel şikayetler) bildirme olasılığı daha yüksek olabilirken, diğerleri dürüst raporlamayı etkileyen ruh sağlığı etrafında damgalama olabilir. PHQ-9 birçok dile çevrilmiş ve birçok ülkede doğrulanmıştır, ancak optimal performans için basit çevirinin ötesinde kültürel adaptasyon gerekebilir. Bu hususlara rağmen, PHQ-9 mevcut en iyi doğrulanmış ve en yaygın uygulanabilir depresyon tarama araçlarından biri olmaya devam etmektedir. Belirli popülasyonlar için veya kültürel faktörler alakalı olduğunda, yorumlama ruh sağlığı değerlendirmesinde kültürel hususlara aşina klinisyenler tarafından yapılmalıdır.',
      },
    ],
  },
};
