import { CalculatorContent } from '@/types/calculator';

export const dueDateContent: CalculatorContent = {
  en: {
    whatIs:
      'A pregnancy due date calculator, also called an estimated date of delivery (EDD) calculator, is a tool used to predict when a pregnant woman will give birth. The due date represents the end of the 40th week of pregnancy, which is calculated as 280 days (40 weeks) from the first day of the last menstrual period (LMP). This calculation method, known as Naegele\'s Rule, was developed in the early 1800s and remains the standard approach used by healthcare providers worldwide. The due date serves as an important reference point throughout pregnancy for monitoring fetal development, scheduling prenatal appointments and tests, and preparing for delivery. However, it is important to understand that only about 5% of babies are born exactly on their due date—most babies arrive within two weeks before or after the estimated date. A normal pregnancy can last anywhere from 37 to 42 weeks, with babies born during this window considered full-term. The due date calculator uses various methods including last menstrual period, conception date, ultrasound measurements, or IVF transfer date to provide the most accurate estimate possible.',

    howToCalculate:
      'The most common method for calculating a due date is using the first day of your last menstrual period (LMP). This method follows Naegele\'s Rule: take the first day of your last period, add 7 days, subtract 3 months, and add 1 year. For example, if your LMP was January 1, 2024: add 7 days = January 8, subtract 3 months = October 8, add 1 year = October 8, 2024. Alternatively, you can simply add 280 days (40 weeks) to your LMP. This calculation assumes a regular 28-day menstrual cycle with ovulation occurring around day 14. If your cycle is longer or shorter, the due date should be adjusted accordingly—for a 32-day cycle, add 4 days to the calculated due date; for a 25-day cycle, subtract 3 days. For the conception/ovulation method, add 266 days (38 weeks) to your known conception date. For ultrasound dating, your healthcare provider measures the baby and calculates how many weeks pregnant you are at the time of the scan, then projects forward to week 40. Ultrasound dating is most accurate when performed during the first trimester (before 13 weeks), with accuracy within 3-5 days. For IVF pregnancies, the calculation depends on embryo transfer date: for a day 3 embryo transfer, add 263 days; for a day 5 embryo transfer, add 261 days. Healthcare providers may update your due date after first-trimester ultrasound if there is a significant discrepancy (more than 5-7 days) between LMP dating and ultrasound measurements.',

    formulaDetails:
      'The standard pregnancy calculation is based on gestational age rather than fetal age. Gestational age starts from the first day of the last menstrual period, approximately two weeks before conception actually occurs. This means when healthcare providers say you are "8 weeks pregnant," the embryo is actually about 6 weeks old (fetal age). This system was adopted because most women know when their last period started but rarely know the exact conception date. Full-term pregnancy is calculated as 40 weeks (280 days) from LMP, which equals 38 weeks (266 days) from conception. The calculation assumes ovulation occurs on day 14 of a 28-day cycle, with conception happening within 24 hours of ovulation. For LMP method: Due Date = LMP + 280 days. For conception method: Due Date = Conception Date + 266 days. For ultrasound method: Due Date = Ultrasound Date + (280 - gestational age in days). For IVF day 3 transfer: Due Date = Transfer Date + 263 days (this accounts for 14 days before egg retrieval + 3 days of embryo development). For IVF day 5 transfer: Due Date = Transfer Date + 261 days. The accuracy of due date calculation varies by method: LMP-based calculations are accurate within 1-2 weeks for women with regular cycles, but less reliable for irregular cycles; first-trimester ultrasound is accurate within 3-5 days and is considered the most reliable method; conception date method is very accurate if the conception date is certain; IVF dating is extremely accurate because the exact conception date is known. Healthcare providers typically use the earliest ultrasound measurement if it differs from LMP dating by more than 5-7 days in the first trimester, as ultrasound measurements in early pregnancy are more accurate than menstrual history for many women.',

    categories: [
      {
        range: 'Weeks 1-13',
        label: 'First Trimester',
        description:
          'Critical period of organ formation. All major organs and body systems begin developing. Morning sickness and fatigue are common. Risk of miscarriage is highest during this period. First prenatal visit and dating ultrasound typically occur.',
        color: '#3B82F6',
      },
      {
        range: 'Weeks 14-27',
        label: 'Second Trimester',
        description:
          'Often called the "honeymoon period" of pregnancy. Energy returns and morning sickness usually subsides. Baby movements (quickening) felt around weeks 18-20. Anatomy ultrasound at 18-22 weeks. Baby\'s gender can be determined.',
        color: '#10B981',
      },
      {
        range: 'Weeks 28-40+',
        label: 'Third Trimester',
        description:
          'Baby gains most of their weight. Mother experiences increased discomfort as baby grows. Braxton Hicks contractions may occur. Baby is considered full-term at 37 weeks. Most babies are born between 39-41 weeks.',
        color: '#F59E0B',
      },
      {
        range: 'Week 37-42',
        label: 'Full Term Period',
        description:
          'Baby is mature enough to be born safely. 37-38 weeks: early term; 39-40 weeks: full term (optimal for delivery); 41 weeks: late term; 42+ weeks: post-term (may require induction).',
        color: '#8B5CF6',
      },
    ],

    interpretation:
      'Your due date is an estimate, not a guarantee. Only about 5% of babies arrive on their exact due date, while approximately 90% are born within two weeks (before or after) of the estimated date. First-time mothers are slightly more likely to deliver after their due date, while women who have given birth before may deliver earlier. The due date helps healthcare providers track fetal development through pregnancy milestones, schedule important tests and screenings at appropriate times, and determine when a pregnancy has gone past its expected timeframe. Babies born between 37 and 42 weeks gestation are considered term, though the optimal window is 39-40 weeks. Babies born before 37 weeks are premature and may require special medical care, while pregnancies lasting beyond 42 weeks are post-term and carry increased risks requiring medical evaluation. Your due date may be adjusted after ultrasound measurements, particularly if early ultrasound dating differs significantly from menstrual dating. The most accurate due dates come from first-trimester ultrasounds combined with reliable menstrual history. Understanding that the due date is an approximation helps manage expectations and reduces anxiety as the estimated date approaches. Focus on the "due month" rather than the specific date, and prepare for delivery anytime from 37 weeks onward.',

    limitations:
      'Due date calculations have several important limitations. First, the LMP method assumes all women have regular 28-day cycles with ovulation on day 14, but many women have irregular cycles, making LMP-based dating unreliable. Irregular periods, recent use of hormonal birth control, breastfeeding while conceiving, or polycystic ovary syndrome (PCOS) can all affect cycle regularity and calculation accuracy. Second, many women do not remember their exact LMP date or may confuse early pregnancy spotting (implantation bleeding) with a period. Third, the due date calculation does not account for individual variations in pregnancy length—some women naturally have slightly longer or shorter pregnancies. Fourth, dating based solely on LMP becomes increasingly unreliable as pregnancy progresses because ultrasound measurements of baby size become more variable in later pregnancy as babies grow at different rates. Fifth, factors such as maternal age, ethnicity, body mass index (BMI), number of previous pregnancies, and genetic factors can influence pregnancy length but are not considered in standard calculations. Sixth, twins and multiple pregnancies have different timelines—twins typically deliver around 37 weeks, and higher-order multiples even earlier, but standard calculators do not adjust for multiples. Seventh, certain medical conditions, complications, or interventions may necessitate early delivery before the due date. Eighth, ultrasound dating in the second and third trimesters is less accurate (within 1-3 weeks) because babies grow at different rates, making size-based dating less reliable. Finally, the due date does not predict the exact day of delivery—it represents a 5-week window (37-42 weeks) when delivery is expected. For these reasons, healthcare providers use "estimated due date" (EDD) rather than "exact due date" and make clinical decisions based on multiple factors beyond the calculated date.',

    healthRisks:
      'Understanding pregnancy timing is crucial for managing health risks at different stages. Premature birth (before 37 weeks) carries significant risks including respiratory distress syndrome, difficulty regulating body temperature, feeding problems, jaundice, increased infection risk, developmental delays, and long-term health complications. The earlier the birth, the greater the risks—babies born before 28 weeks face the most serious complications. Late preterm babies (34-36 weeks) have better outcomes than very preterm babies but still face more risks than full-term infants. Conversely, post-term pregnancies (beyond 42 weeks) also carry increased risks including macrosomia (large baby leading to difficult delivery), placental insufficiency (placenta stops functioning properly), decreased amniotic fluid, meconium aspiration (baby inhales fetal waste), stillbirth risk increases slightly, and increased likelihood of needing cesarean delivery. The optimal delivery window is 39-40 weeks when babies are mature but placental function is still optimal. Babies born at 37-38 weeks (early term) have slightly higher risks of respiratory problems, feeding difficulties, and temperature regulation issues compared to 39-40 week babies. This is why elective inductions or cesarean deliveries are not recommended before 39 weeks without medical indication. Accurate pregnancy dating is essential for appropriate timing of interventions—administering corticosteroids if preterm delivery is likely (to mature baby\'s lungs), determining when to induce labor if pregnancy extends beyond due date, scheduling cesarean deliveries at the safest time, and avoiding unnecessary early deliveries that mistake pregnancy length. Women should attend all prenatal appointments, where healthcare providers monitor baby\'s growth, position, and wellbeing through physical exams, ultrasounds, and fetal monitoring. Signs requiring immediate medical attention include decreased fetal movement, vaginal bleeding, severe abdominal pain, persistent headache with vision changes, signs of preterm labor (regular contractions before 37 weeks), or fluid leakage. Understanding your accurate due date helps you recognize when symptoms warrant urgent evaluation.',

    alternativeMeasures:
      'Beyond the standard due date calculation, healthcare providers use multiple methods to assess pregnancy progress and confirm dating accuracy. First-trimester ultrasound (dating scan) performed between 8-13 weeks measures the crown-rump length (CRL)—the length from the top of the baby\'s head to bottom—and provides accurate dating within 3-5 days. This is the most accurate method for determining due date and is preferred over menstrual dating when there is a discrepancy of more than 5-7 days. Second-trimester ultrasound (anatomy scan) at 18-22 weeks measures multiple parameters including biparietal diameter (head width), head circumference, abdominal circumference, and femur length to estimate gestational age within 7-10 days. However, second-trimester dating is less accurate than first-trimester because babies begin growing at individual rates. Fundal height measurement—measuring the distance from the pubic bone to the top of the uterus—provides a rough estimate of pregnancy progress. From 20 weeks onward, the fundal height in centimeters should roughly correspond to gestational age in weeks (±2-3 cm). Significant deviation may indicate growth problems or incorrect dating. Fetal movement counting becomes important in the third trimester to monitor baby\'s wellbeing, though it does not determine dating. Blood tests including beta-hCG (pregnancy hormone) levels can confirm early pregnancy but do not accurately date pregnancy beyond broad estimates. Quantitative hCG testing shows characteristic doubling patterns in early pregnancy but varies too much between individuals for precise dating. Some healthcare systems use pregnancy wheels or gestational age calculators—circular charts or apps that quickly determine due date and current gestational age from the LMP. For IVF and fertility treatment pregnancies, precise embryo transfer dates provide the most accurate dating possible. Advanced maternal age (35+), fertility treatments, multiples pregnancies, or complicated medical histories may warrant more frequent ultrasounds to monitor growth and confirm dating. The American College of Obstetricians and Gynecologists (ACOG) recommends that the due date be established by the best available method early in pregnancy and should not be changed by later ultrasounds unless there is a significant discrepancy (more than 2 weeks in the third trimester). Once established, the due date should remain consistent throughout pregnancy to avoid confusion and inappropriate interventions.',

    demographicDifferences:
      'Pregnancy length and due date accuracy vary across different populations and individual factors. Ethnicity influences average pregnancy length—studies show that Black women have slightly shorter average pregnancies (about 39 weeks) compared to white and Asian women, with babies born on average 3-4 days earlier even in uncomplicated pregnancies. However, this difference is not accounted for in standard due date calculations. Maternal age affects pregnancy outcomes: teenage mothers and women over 35 have higher rates of both preterm and post-term births. First-time mothers (nulliparous) typically deliver 3-5 days later on average than women who have given birth before (multiparous), and first pregnancies are more likely to go beyond 40 weeks. Women who have previously had preterm births are at higher risk of preterm delivery in subsequent pregnancies. Body mass index (BMI) influences pregnancy length and dating accuracy—women with higher BMI may have less accurate ultrasound measurements due to technical limitations, and obesity is associated with slightly longer pregnancies and higher rates of post-term births. Women with PCOS or irregular cycles require ultrasound dating rather than LMP dating due to unpredictable ovulation. Multiple pregnancies (twins, triplets) have significantly shorter expected gestation: twins average 37 weeks, triplets 33 weeks, and quadruplets 30 weeks, yet standard calculators assume singleton pregnancies. Assisted reproductive technology (ART) pregnancies including IVF have precisely known conception dates, making them the most accurately dated pregnancies. Seasonal variations exist—babies conceived in spring/summer are slightly more likely to be born preterm, possibly due to environmental factors and vitamin D levels. Socioeconomic factors including access to prenatal care, stress levels, nutrition, and working conditions influence pregnancy outcomes and timing. Women in high-stress occupations or those with limited prenatal care access have higher preterm birth rates. Genetic factors play a role—family history of early or late deliveries may indicate inherited tendencies for pregnancy length. These demographic differences underscore the importance of individualized care and understanding that due dates are estimates with inherent variability.',

    medicalDisclaimer:
      'This pregnancy due date calculator is designed for educational and informational purposes only and should not replace professional medical advice, diagnosis, or prenatal care. The calculated due date is an estimate based on the information provided and represents an approximation, not a guarantee of when delivery will occur. Only about 5% of babies are born on their exact due date. This calculator is intended for singleton pregnancies (one baby) with uncomplicated medical histories—twin, triplet, or higher-order multiple pregnancies have different expected delivery timelines and require specialized medical oversight. The calculator should not be used as the sole method for dating pregnancy or making medical decisions. Accurate pregnancy dating requires comprehensive evaluation by qualified healthcare providers who can consider your complete medical history, perform physical examinations, conduct ultrasounds, and integrate multiple sources of information. Never use this calculator to delay or avoid seeking professional prenatal care. Regular prenatal appointments are essential for monitoring maternal and fetal health, detecting potential complications early, performing necessary screening tests, and preparing for safe delivery. Pregnant women should establish prenatal care with an obstetrician, midwife, or other qualified prenatal care provider as soon as pregnancy is confirmed. This calculator assumes the provided dates are accurate—incorrect information will produce incorrect results. Women with irregular menstrual cycles, uncertain LMP dates, recent hormonal contraceptive use, breastfeeding while conceiving, PCOS, or other reproductive health conditions require ultrasound dating rather than LMP-based calculations. This calculator does not account for medical complications, previous pregnancy history, maternal health conditions, medications, or other factors that may affect pregnancy length or require early delivery. Seek immediate medical attention if you experience warning signs including vaginal bleeding, severe abdominal pain, persistent headaches with vision changes, decreased fetal movement, signs of preterm labor, leaking fluid, or any concerning symptoms. The information provided does not constitute medical advice and should not be used to self-diagnose or self-treat any medical condition. Always consult qualified healthcare professionals for personalized medical guidance, diagnostic testing, and treatment recommendations. Pregnancy management requires individualized care that considers your unique circumstances, medical history, and current health status.',

    references: [
      'American College of Obstetricians and Gynecologists (ACOG). Methods for Estimating the Due Date. Committee Opinion No. 700. Obstet Gynecol. 2017;129:e150-4.',
      'World Health Organization. WHO recommendations on antenatal care for a positive pregnancy experience. Geneva: WHO; 2016.',
      'National Institute for Health and Care Excellence (NICE). Antenatal care for uncomplicated pregnancies. Clinical guideline [CG62]. 2008, updated 2021.',
      'Naegele FC. Erfahrungen und Abhandlungen aus dem Gebiethe der Krankheiten des weiblichen Geschlechtes nebst Grundriss einer Geschichte der Geburtshülfe. Heidelberg: August Oswald; 1812.',
      'Mongelli M, Wilcox M, Gardosi J. Estimating the date of confinement: ultrasonographic biometry versus certain menstrual dates. Am J Obstet Gynecol. 1996;174(1):278-281.',
      'Butt K, Lim K; Sonography Committee. Determination of gestational age by ultrasound. J Obstet Gynaecol Can. 2014;36(2):171-181.',
      'Hoffman CS, Messer LC, Mendola P, et al. Comparison of gestational age at birth based on last menstrual period and ultrasound during the first trimester. Paediatr Perinat Epidemiol. 2008;22(6):587-596.',
      'Savitz DA, Terry JW Jr, Dole N, et al. Comparison of pregnancy dating by last menstrual period, ultrasound scanning, and their combination. Am J Obstet Gynecol. 2002;187(6):1660-1666.',
    ],

    tips: [
      'Track your menstrual cycles using a calendar or app to know your LMP date accurately for future pregnancy planning',
      'First-trimester ultrasound (8-13 weeks) provides the most accurate due date—request early dating if your LMP is uncertain',
      'Remember that your due date is an estimate covering a 5-week window (37-42 weeks) when delivery is expected',
      'Prepare for delivery starting at 37 weeks—pack hospital bag, finalize birth plan, and arrange postpartum support early',
      'Attend all scheduled prenatal appointments for monitoring growth, performing tests, and updating delivery plans',
      'Focus on preparing for a "due month" rather than a specific date to reduce anxiety as the due date approaches',
      'First-time mothers often deliver 3-5 days after their due date—avoid scheduling visitors or commitments for the exact date',
      'Discuss induction policies with your healthcare provider—understand at what point (typically 41-42 weeks) induction may be recommended',
      'Monitor fetal movements starting around 28 weeks—contact your provider immediately if you notice decreased movement',
      'Take childbirth education classes in the second trimester (before you become too uncomfortable) to prepare mentally and physically',
      'If your due date is adjusted based on ultrasound, ask your provider why and understand which dating method is considered most reliable',
      'For IVF pregnancies, your due date is extremely accurate since conception date is precisely known—trust this dating over later ultrasounds',
    ],

    faqs: [
      {
        question: 'How accurate is the due date calculator?',
        answer:
          'Due date calculators provide estimates with varying accuracy depending on the method used. LMP-based calculations are accurate within 1-2 weeks for women with regular 28-day cycles, but less accurate for irregular cycles. First-trimester ultrasound (8-13 weeks) is the most accurate method, dating pregnancy within 3-5 days. Second-trimester ultrasounds are accurate within 7-10 days, while third-trimester ultrasounds are only accurate within 2-3 weeks due to individual growth variations. IVF dating is extremely accurate because the exact conception date is known. Only about 5% of babies arrive on their exact due date, but approximately 90% are born within two weeks (before or after) the estimated date. Your healthcare provider will use the most reliable dating method available and may adjust your due date if early ultrasound measurements differ significantly from menstrual dating.',
      },
      {
        question: 'What if I don\'t remember my last menstrual period?',
        answer:
          'If you cannot remember your LMP date or have irregular cycles, your healthcare provider will use ultrasound dating to determine your due date. A first-trimester ultrasound (ideally between 8-13 weeks) measures the crown-rump length and provides accurate dating within 3-5 days. This is actually more accurate than menstrual dating for many women. Ultrasound dating is the preferred method for women with irregular cycles, recent hormonal contraceptive use, uncertain LMP dates, breastfeeding while conceiving, or PCOS. The earlier the ultrasound is performed, the more accurate the dating. If you are already in the second trimester, ultrasound can still provide dating, though with slightly less precision (within 7-10 days). Never guess at your LMP date, as incorrect information leads to incorrect dating and potentially inappropriate medical decisions.',
      },
      {
        question: 'Why did my due date change after an ultrasound?',
        answer:
          'Healthcare providers may adjust your due date if early ultrasound measurements differ significantly from LMP-based dating. According to ACOG guidelines, if a first-trimester ultrasound shows gestational age differing by more than 5-7 days from LMP dating, the ultrasound date should be used because it is more accurate. This happens commonly when women have irregular cycles, miscalculate their LMP, or mistake implantation bleeding for a period. Once established using the most reliable method (typically first-trimester ultrasound), your due date should remain consistent and should not be changed by later ultrasounds unless there is a discrepancy of more than 2 weeks in the third trimester. Later ultrasounds measure baby size, which varies between individuals, making them less reliable for dating. The adjusted due date is not wrong—it simply reflects more accurate information than the initial estimate.',
      },
      {
        question: 'Is my baby overdue if I pass my due date?',
        answer:
          'No, your baby is not considered overdue until after 42 weeks of pregnancy. A due date at 40 weeks is an estimate, and normal pregnancy lasts anywhere from 37 to 42 weeks. Babies born between 37-38 weeks are "early term," 39-40 weeks are "full term" (optimal), 41 weeks is "late term," and 42+ weeks is "post-term." About 50% of women deliver after their due date, especially first-time mothers who tend to go 3-5 days past their due date on average. Most healthcare providers will monitor you closely after 40 weeks with weekly or twice-weekly appointments that may include non-stress tests and amniotic fluid checks. Induction is typically discussed around 41 weeks and often recommended by 42 weeks due to increased risks associated with post-term pregnancy. However, induction timing is individualized based on your health, baby\'s condition, and cervical readiness.',
      },
      {
        question: 'Can stress or activity affect when I deliver?',
        answer:
          'While chronic severe stress during pregnancy is associated with slightly increased preterm birth risk, normal daily stress or reasonable physical activity does not significantly change when you will deliver or make your baby come early or late. Your body determines labor onset through complex hormonal signals when the baby and placenta are ready, not through your conscious control. Moderate exercise during pregnancy is safe and beneficial, and working (unless your job involves heavy physical labor or prolonged standing) does not typically trigger early labor in healthy pregnancies. However, very high stress levels, inadequate rest, poor nutrition, or physically demanding work may contribute to preterm birth risk in vulnerable women. Activities that are safe during pregnancy do not cause labor to start before your body and baby are ready. Once you reach full term (37+ weeks), walking, sex, nipple stimulation, and spicy foods are often suggested to encourage labor, but scientific evidence for these methods is limited—they may help ripen the cervix if your body is already preparing for labor but will not force labor to start if you are not physiologically ready.',
      },
      {
        question: 'How is the due date calculated for twins?',
        answer:
          'For twin pregnancies, the due date is still calculated as 40 weeks from the LMP or based on early ultrasound, but twins typically deliver earlier than singletons. The average delivery time for twins is around 37 weeks, though many twins are born between 35-37 weeks. Triplets average 33 weeks, and quadruplets around 30 weeks. However, standard due date calculators assume singleton pregnancies and do not adjust for multiples. Your healthcare provider will monitor twin pregnancies more closely with more frequent ultrasounds and appointments. Many providers recommend delivery by 38-39 weeks for uncomplicated twin pregnancies to reduce risks, and some twins are delivered earlier if complications arise. The dating method (LMP or ultrasound) is the same for twins as singletons, but management and delivery planning differs significantly. Twin pregnancies are always considered higher-risk and require specialized obstetric care.',
      },
      {
        question: 'Can my due date be wrong by weeks or months?',
        answer:
          'If your due date is based on a first-trimester ultrasound, it is very unlikely to be wrong by more than 5-7 days. However, if dating is based solely on uncertain menstrual history without ultrasound confirmation, it could potentially be off by weeks. This is why ACOG recommends ultrasound dating, especially for women with irregular cycles or uncertain LMP. Cases where due dates are drastically wrong (by months) are extremely rare and typically occur only when women have no prenatal care and very irregular cycles with uncertain LMP. Such cases might include women who conceived while breastfeeding (suppressed periods), coming off birth control (irregular return of cycles), or with PCOS. First-trimester ultrasound essentially eliminates the possibility of dating being off by more than a week. If you are concerned about your due date accuracy, discuss getting or reviewing an early ultrasound with your healthcare provider. Dating established in the first trimester should be trusted over later ultrasounds, which measure baby size (which varies) rather than developmental age.',
      },
    ],
  },
  tr: {
    whatIs:
      'Hamilelik doğum tarihi hesaplayıcısı, tahmini doğum tarihi (TDT) hesaplayıcısı olarak da adlandırılır ve hamile bir kadının ne zaman doğum yapacağını tahmin etmek için kullanılan bir araçtır. Doğum tarihi, hamileliğin 40. haftasının sonunu temsil eder ve son adet döneminin (SAT) ilk gününden itibaren 280 gün (40 hafta) olarak hesaplanır. Naegele Kuralı olarak bilinen bu hesaplama yöntemi 1800\'lü yılların başında geliştirilmiş ve dünya çapında sağlık hizmeti sağlayıcıları tarafından kullanılan standart yaklaşım olmaya devam etmektedir. Doğum tarihi, hamilelik boyunca fetal gelişimi izlemek, doğum öncesi randevuları ve testleri planlamak ve doğuma hazırlanmak için önemli bir referans noktası görevi görür. Ancak, bebeklerin yalnızca yaklaşık %5\'inin tam doğum tarihinde doğduğunu anlamak önemlidir—çoğu bebek tahmini tarihten iki hafta önce veya sonra dünyaya gelir. Normal bir hamilelik 37 ila 42 hafta arasında sürebilir ve bu pencerede doğan bebekler term kabul edilir. Doğum tarihi hesaplayıcı, mümkün olan en doğru tahmini sağlamak için son adet dönemi, döllendirme tarihi, ultrason ölçümleri veya tüp bebek transfer tarihi dahil olmak üzere çeşitli yöntemler kullanır.',

    howToCalculate:
      'Doğum tarihini hesaplamanın en yaygın yöntemi, son adet döneminizin (SAT) ilk gününü kullanmaktır. Bu yöntem Naegele Kuralını takip eder: son adet döneminizin ilk gününü alın, 7 gün ekleyin, 3 ay çıkarın ve 1 yıl ekleyin. Örneğin, SAT\'ınız 1 Ocak 2024 ise: 7 gün ekleyin = 8 Ocak, 3 ay çıkarın = 8 Ekim, 1 yıl ekleyin = 8 Ekim 2024. Alternatif olarak, SAT\'ınıza basitçe 280 gün (40 hafta) ekleyebilirsiniz. Bu hesaplama, 14. günde ovülasyon gerçekleşen düzenli 28 günlük adet döngüsünü varsayar. Döngünüz daha uzun veya daha kısa ise, doğum tarihi buna göre ayarlanmalıdır—32 günlük bir döngü için hesaplanan doğum tarihine 4 gün ekleyin; 25 günlük bir döngü için 3 gün çıkarın. Döllendirme/yumurtlama yöntemi için, bilinen döllendirme tarihinize 266 gün (38 hafta) ekleyin. Ultrason tarihleme için, sağlık hizmeti sağlayıcınız bebeği ölçer ve tarama sırasında kaç haftalık hamile olduğunuzu hesaplar, ardından 40. haftaya kadar projelendirme yapar. Ultrason tarihleme, ilk trimesterde (13 haftadan önce) yapıldığında en doğrudur ve 3-5 gün içinde doğruluğa sahiptir. Tüp bebek hamilelikleri için, hesaplama embriyo transfer tarihine bağlıdır: 3. gün embriyo transferi için 263 gün ekleyin; 5. gün embriyo transferi için 261 gün ekleyin. Sağlık hizmeti sağlayıcıları, SAT tarihleme ile ultrason ölçümleri arasında önemli bir tutarsızlık (5-7 günden fazla) varsa ilk trimester ultrasonundan sonra doğum tarihinizi güncelleyebilir.',

    formulaDetails:
      'Standart hamilelik hesaplaması fetal yaştan ziyade gestasyonel yaşa dayanır. Gestasyonel yaş, son adet döneminin ilk gününden başlar ve döllendirme gerçekten meydana gelmeden yaklaşık iki hafta öncedir. Bu, sağlık hizmeti sağlayıcıları "8 haftalık hamilesiniz" dediğinde, embriyonun aslında yaklaşık 6 haftalık (fetal yaş) olduğu anlamına gelir. Bu sistem benimsenmiştir çünkü çoğu kadın son adet döneminin ne zaman başladığını bilir ancak kesin döllendirme tarihini nadiren bilir. Term hamilelik, SAT\'tan itibaren 40 hafta (280 gün) olarak hesaplanır, bu da döllendirmeden itibaren 38 hafta (266 gün) eşittir. Hesaplama, 28 günlük bir döngünün 14. gününde ovülasyonun gerçekleştiğini ve döllendirmenin ovülasyondan sonraki 24 saat içinde gerçekleştiğini varsayar. SAT yöntemi için: Doğum Tarihi = SAT + 280 gün. Döllendirme yöntemi için: Doğum Tarihi = Döllendirme Tarihi + 266 gün. Ultrason yöntemi için: Doğum Tarihi = Ultrason Tarihi + (280 - gün cinsinden gestasyonel yaş). Tüp bebek 3. gün transferi için: Doğum Tarihi = Transfer Tarihi + 263 gün (bu, yumurta toplama öncesi 14 gün + 3 gün embriyo gelişimini hesaba katar). Tüp bebek 5. gün transferi için: Doğum Tarihi = Transfer Tarihi + 261 gün. Doğum tarihi hesaplamasının doğruluğu yönteme göre değişir: SAT tabanlı hesaplamalar düzenli döngüleri olan kadınlar için 1-2 hafta içinde doğrudur, ancak düzensiz döngüler için daha az güvenilirdir; ilk trimester ultrason 3-5 gün içinde doğrudur ve en güvenilir yöntem olarak kabul edilir; döllendirme tarihi yöntemi, döllendirme tarihi kesinse çok doğrudur; tüp bebek tarihleme son derece doğrudur çünkü kesin döllendirme tarihi bilinir. Sağlık hizmeti sağlayıcıları, ilk trimesterde SAT tarihleme ile 5-7 günden fazla farklılık gösteriyorsa genellikle en erken ultrason ölçümünü kullanır, çünkü erken hamilelik ultrason ölçümleri birçok kadın için adet geçmişinden daha doğrudur.',

    categories: [
      {
        range: 'Hafta 1-13',
        label: 'İlk Trimester',
        description:
          'Organ oluşumunun kritik dönemi. Tüm majör organlar ve vücut sistemleri gelişmeye başlar. Sabah bulantısı ve yorgunluk yaygındır. Düşük riski bu dönemde en yüksektir. İlk doğum öncesi ziyaret ve tarihleme ultrasonu genellikle gerçekleşir.',
        color: '#3B82F6',
      },
      {
        range: 'Hafta 14-27',
        label: 'İkinci Trimester',
        description:
          'Genellikle hamileliğin "balayı dönemi" olarak adlandırılır. Enerji geri döner ve sabah bulantısı genellikle azalır. Bebek hareketleri 18-20. haftalarda hissedilir. 18-22. haftalarda anatomi ultrasonu yapılır. Bebeğin cinsiyeti belirlenebilir.',
        color: '#10B981',
      },
      {
        range: 'Hafta 28-40+',
        label: 'Üçüncü Trimester',
        description:
          'Bebek kilosunun çoğunu alır. Anne bebek büyüdükçe artan rahatsızlık yaşar. Braxton Hicks kasılmaları oluşabilir. Bebek 37. haftada term kabul edilir. Çoğu bebek 39-41. haftalar arasında doğar.',
        color: '#F59E0B',
      },
      {
        range: 'Hafta 37-42',
        label: 'Term Dönemi',
        description:
          'Bebek güvenli bir şekilde doğmak için yeterince olgunlaşmıştır. 37-38 hafta: erken term; 39-40 hafta: tam term (doğum için optimal); 41 hafta: geç term; 42+ hafta: postterm (indüksiyon gerektirebilir).',
        color: '#8B5CF6',
      },
    ],

    interpretation:
      'Doğum tarihiniz bir tahmindir, garanti değildir. Bebeklerin yalnızca yaklaşık %5\'i tam doğum tarihlerinde dünyaya gelirken, yaklaşık %90\'ı tahmini tarihten iki hafta içinde (önce veya sonra) doğar. İlk kez anne olanlar doğum tarihlerinden sonra doğum yapma olasılığı biraz daha yüksekken, daha önce doğum yapmış kadınlar daha erken doğum yapabilir. Doğum tarihi, sağlık hizmeti sağlayıcılarının hamilelik kilometre taşları boyunca fetal gelişimi takip etmesine, önemli test ve taramaları uygun zamanlarda planlamasına ve hamileliğin beklenen zaman dilimini ne zaman geçtiğini belirlemeye yardımcı olur. 37 ile 42 hafta gebelik arasında doğan bebekler term kabul edilir, ancak optimal pencere 39-40 haftadır. 37 haftadan önce doğan bebekler erken doğmuştur ve özel tıbbi bakıma ihtiyaç duyabilirken, 42 haftanın ötesinde süren hamileliklerin postterm olması ve tıbbi değerlendirme gerektiren artan riskleri vardır. Doğum tarihiniz ultrason ölçümlerine göre ayarlanabilir, özellikle erken ultrason tarihleme adet tarihlemesinden önemli ölçüde farklıysa. En doğru doğum tarihleri, güvenilir adet geçmişiyle birleştirilen ilk trimester ultrasonlarından gelir. Doğum tarihinin bir yaklaşım olduğunu anlamak beklentileri yönetmeye ve tahmini tarih yaklaştıkça kaygıyı azaltmaya yardımcı olur. Belirli bir tarihten ziyade "doğum ayına" odaklanın ve 37. haftadan itibaren her an doğuma hazırlanın.',

    limitations:
      'Doğum tarihi hesaplamalarının birkaç önemli sınırlaması vardır. İlk olarak, SAT yöntemi tüm kadınların 14. günde ovülasyon olan düzenli 28 günlük döngülere sahip olduğunu varsayar, ancak birçok kadının düzensiz döngüleri vardır ve bu da SAT tabanlı tarihlemeyi güvenilmez kılar. Düzensiz adet dönemleri, son hormonal doğum kontrolü kullanımı, hamile kalırken emzirme veya polikistik over sendromu (PKOS) döngü düzenliliğini ve hesaplama doğruluğunu etkileyebilir. İkinci olarak, birçok kadın kesin SAT tarihini hatırlamaz veya erken hamilelik lekelenmesini (implantasyon kanaması) adet ile karıştırabilir. Üçüncü olarak, doğum tarihi hesaplaması hamilelik uzunluğundaki bireysel varyasyonları hesaba katmaz—bazı kadınlar doğal olarak biraz daha uzun veya daha kısa hamileliklere sahiptir. Dördüncü olarak, yalnızca SAT\'a dayalı tarihleme, hamilelik ilerledikçe giderek daha güvenilmez hale gelir çünkü bebeğin büyüklüğüne ilişkin ultrason ölçümleri, bebekler farklı hızlarda büyüdüğü için geç hamilelikte daha değişken hale gelir. Beşinci olarak, anne yaşı, etnik köken, vücut kitle indeksi (VKİ), önceki hamilelik sayısı ve genetik faktörler gibi faktörler hamilelik uzunluğunu etkileyebilir ancak standart hesaplamalarda dikkate alınmaz. Altıncı olarak, ikizler ve çoğul gebelikler farklı zaman çizelgelerine sahiptir—ikizler genellikle 37. hafta civarında doğar ve daha yüksek dereceli çoğullar daha da erken doğar, ancak standart hesaplayıcılar çoğullar için ayarlama yapmaz. Yedinci olarak, belirli tıbbi durumlar, komplikasyonlar veya müdahaleler doğum tarihinden önce erken doğumu gerekli kılabilir. Sekizinci olarak, ikinci ve üçüncü trimesterdeki ultrason tarihleme daha az doğrudur (1-3 hafta içinde) çünkü bebekler farklı hızlarda büyür ve boyut tabanlı tarihleme daha az güvenilir hale gelir. Son olarak, doğum tarihi doğumun tam gününü tahmin etmez—doğumun beklendiği 5 haftalık bir pencereyi (37-42 hafta) temsil eder. Bu nedenlerle, sağlık hizmeti sağlayıcıları "kesin doğum tarihi" yerine "tahmini doğum tarihi" (TDT) kullanır ve hesaplanan tarihin ötesinde birden fazla faktöre dayalı klinik kararlar alır.',

    healthRisks:
      'Hamilelik zamanlamasını anlamak, farklı aşamalardaki sağlık risklerini yönetmek için çok önemlidir. Erken doğum (37 haftadan önce), solunum sıkıntısı sendromu, vücut sıcaklığını düzenlemede zorluk, beslenme sorunları, sarılık, artmış enfeksiyon riski, gelişimsel gecikmeler ve uzun vadeli sağlık komplikasyonları dahil olmak üzere önemli riskler taşır. Doğum ne kadar erken olursa, riskler o kadar büyük olur—28 haftadan önce doğan bebekler en ciddi komplikasyonlarla karşı karşıyadır. Geç preterm bebekler (34-36 hafta) çok preterm bebeklerden daha iyi sonuçlara sahiptir ancak yine de term bebeklerden daha fazla riskle karşı karşıyadır. Tersine, postterm hamileliklerin (42 haftanın ötesinde) makrozomi (zor doğuma yol açan büyük bebek), plasental yetmezlik (plasenta düzgün çalışmayı bırakır), azalmış amniyotik sıvı, mekonyum aspirasyonu (bebek fetal atık solur), ölü doğum riskinin hafifçe artması ve sezaryen doğuma ihtiyaç duyma olasılığının artması dahil artan riskleri vardır. Optimal doğum penceresi, bebeklerin olgun ancak plasental fonksiyonun hala optimal olduğu 39-40 haftadır. 37-38. haftalarda doğan bebekler (erken term), 39-40 haftalık bebeklere kıyasla solunum sorunları, beslenme zorlukları ve sıcaklık düzenleme sorunları için biraz daha yüksek risklere sahiptir. Bu nedenle elektif indüksiyonlar veya sezaryen doğumlar tıbbi endikasyon olmadan 39 haftadan önce önerilmez. Doğru hamilelik tarihleme, müdahalelerin uygun zamanlaması için esastır—preterm doğum olasılığı varsa kortikosteroidlerin uygulanması (bebeğin akciğerlerini olgunlaştırmak için), hamilelik doğum tarihini geçerse doğumu ne zaman indüklemek gerektiğini belirleme, sezaryen doğumları en güvenli zamanda planlama ve hamilelik uzunluğunu yanlış hesaplayan gereksiz erken doğumlardan kaçınma. Kadınlar tüm doğum öncesi randevularına katılmalıdır; burada sağlık hizmeti sağlayıcıları fiziksel muayeneler, ultrasonlar ve fetal izleme yoluyla bebeğin büyümesini, pozisyonunu ve refahını izler. Acil tıbbi yardım gerektiren belirtiler arasında azalmış fetal hareket, vajinal kanama, şiddetli karın ağrısı, görme değişiklikleriyle birlikte kalıcı baş ağrısı, preterm doğum belirtileri (37 haftadan önce düzenli kasılmalar) veya sıvı sızıntısı bulunur. Doğru doğum tarihinizi anlamak, semptomların ne zaman acil değerlendirme gerektirdiğini tanımanıza yardımcı olur.',

    alternativeMeasures:
      'Standart doğum tarihi hesaplamasının ötesinde, sağlık hizmeti sağlayıcıları hamilelik ilerlemesini değerlendirmek ve tarihleme doğruluğunu onaylamak için birden fazla yöntem kullanır. 8-13. haftalar arasında yapılan ilk trimester ultrason (tarihleme taraması) tepe-makat uzunluğunu (CRL)—bebeğin başının tepesinden altına kadar olan uzunluğu—ölçer ve 3-5 gün içinde doğru tarihleme sağlar. Bu, doğum tarihini belirlemek için en doğru yöntemdir ve 5-7 günden fazla bir tutarsızlık olduğunda adet tarihlemesine tercih edilir. 18-22. haftalardaki ikinci trimester ultrason (anatomi taraması), 7-10 gün içinde gestasyonel yaşı tahmin etmek için biparietal çap (baş genişliği), baş çevresi, karın çevresi ve femur uzunluğu dahil birden fazla parametreyi ölçer. Ancak, ikinci trimester tarihleme ilk trimesterden daha az doğrudur çünkü bebekler bireysel hızlarda büyümeye başlar. Fundus yüksekliği ölçümü—pubis kemiğinden rahimin tepesine kadar olan mesafeyi ölçmek—hamilelik ilerlemesinin kaba bir tahminini sağlar. 20. haftadan itibaren, santimetre cinsinden fundus yüksekliği hafta cinsinden gestasyonel yaşa kabaca karşılık gelmelidir (±2-3 cm). Önemli sapma büyüme sorunlarını veya yanlış tarihlemeyi gösterebilir. Fetal hareket sayımı, bebeğin refahını izlemek için üçüncü trimesterde önemli hale gelir, ancak tarihleme belirlemez. Beta-hCG (hamilelik hormonu) seviyeleri dahil kan testleri erken hamileliği doğrulayabilir ancak geniş tahminlerin ötesinde hamileliği doğru bir şekilde tarihlemez. Kantitatif hCG testi erken hamilelikte karakteristik ikiye katlanma kalıpları gösterir ancak kesin tarihleme için bireyler arasında çok fazla değişir. Bazı sağlık sistemleri hamilelik çarkları veya gestasyonel yaş hesaplayıcıları kullanır—SAT\'tan doğum tarihini ve mevcut gestasyonel yaşı hızlı bir şekilde belirleyen dairesel çizelgeler veya uygulamalar. Tüp bebek ve doğurganlık tedavisi hamilelikleri için, kesin embriyo transfer tarihleri mümkün olan en doğru tarihlemeyi sağlar. İleri anne yaşı (35+), doğurganlık tedavileri, çoğul hamilelikler veya komplike tıbbi geçmişler büyümeyi izlemek ve tarihlemeyi onaylamak için daha sık ultrasonları gerektirebilir. Amerikan Kadın Doğum Uzmanları Koleji (ACOG), doğum tarihinin hamileliğin erken döneminde mevcut en iyi yöntemle belirlenmesini ve üçüncü trimesterde önemli bir tutarsızlık (2 haftadan fazla) olmadıkça daha sonraki ultrasonlarla değiştirilmemesini önerir. Oluşturulduktan sonra, doğum tarihi karışıklığı ve uygunsuz müdahaleleri önlemek için hamilelik boyunca tutarlı kalmalıdır.',

    demographicDifferences:
      'Hamilelik uzunluğu ve doğum tarihi doğruluğu farklı popülasyonlar ve bireysel faktörler arasında değişir. Etnik köken ortalama hamilelik uzunluğunu etkiler—çalışmalar Siyah kadınların beyaz ve Asyalı kadınlara kıyasla biraz daha kısa ortalama hamileliklere (yaklaşık 39 hafta) sahip olduğunu, bebeklerin komplike olmamış hamileliklerde bile ortalama 3-4 gün erken doğduğunu göstermektedir. Ancak, bu fark standart doğum tarihi hesaplamalarında dikkate alınmaz. Anne yaşı hamilelik sonuçlarını etkiler: genç anneler ve 35 yaş üstü kadınlar hem preterm hem de postterm doğum oranlarına sahiptir. İlk kez anneler (nullipar) genellikle daha önce doğum yapmış kadınlardan (multipar) ortalama 3-5 gün daha geç doğum yapar ve ilk hamileliklerin 40 haftayı geçme olasılığı daha yüksektir. Daha önce preterm doğum yapmış kadınlar, sonraki hamileliklerde preterm doğum riskinde daha yüksektir. Vücut kitle indeksi (VKİ) hamilelik uzunluğunu ve tarihleme doğruluğunu etkiler—daha yüksek VKİ\'ye sahip kadınlar teknik sınırlamalar nedeniyle daha az doğru ultrason ölçümlerine sahip olabilir ve obezite biraz daha uzun hamileliklere ve daha yüksek postterm doğum oranlarına sahiptir. PKOS veya düzensiz döngüleri olan kadınlar öngörülemeyen ovülasyon nedeniyle SAT tarihleme yerine ultrason tarihlemeye ihtiyaç duyar. Çoğul gebelikler (ikizler, üçüzler) önemli ölçüde daha kısa beklenen gestasyona sahiptir: ikizler ortalama 37 hafta, üçüzler 33 hafta ve dörtüzler 30 hafta, ancak standart hesaplayıcılar tek bebek hamilelikleri varsayar. Tüp bebek dahil yardımcı üreme teknolojisi (YÜT) hamilelikleri kesin olarak bilinen döllendirme tarihlerine sahiptir ve bu onları en doğru tarihlenen hamilelikleri yapar. Mevsimsel varyasyonlar mevcuttur—ilkbahar/yaz aylarında gebe kalan bebekler preterm doğma olasılığı biraz daha yüksektir, muhtemelen çevresel faktörler ve D vitamini seviyeleri nedeniyle. Doğum öncesi bakıma erişim, stres seviyeleri, beslenme ve çalışma koşulları dahil sosyoekonomik faktörler hamilelik sonuçlarını ve zamanlamasını etkiler. Yüksek stresli mesleklerde çalışan veya sınırlı doğum öncesi bakım erişimi olan kadınlar daha yüksek preterm doğum oranlarına sahiptir. Genetik faktörler rol oynar—erken veya geç doğum aile geçmişi hamilelik uzunluğu için kalıtsal eğilimleri gösterebilir. Bu demografik farklılıklar, bireyselleştirilmiş bakımın önemini ve doğum tarihlerinin doğası gereği değişkenliğe sahip tahminler olduğunu anlamayı vurgular.',

    medicalDisclaimer:
      'Bu hamilelik doğum tarihi hesaplayıcısı yalnızca eğitim ve bilgilendirme amaçlarıdır ve profesyonel tıbbi tavsiye, teşhis veya doğum öncesi bakımın yerini almamalıdır. Hesaplanan doğum tarihi, sağlanan bilgilere dayalı bir tahmindir ve doğumun ne zaman gerçekleşeceğinin garantisi değil, bir yaklaşımını temsil eder. Bebeklerin yalnızca yaklaşık %5\'i tam doğum tarihlerinde doğar. Bu hesaplayıcı, komplike olmayan tıbbi geçmişlere sahip tekiz hamilelikleri (bir bebek) için tasarlanmıştır—ikiz, üçüz veya daha yüksek dereceli çoğul hamileliklerin farklı beklenen doğum zaman çizelgeleri vardır ve özel tıbbi gözetim gerektirir. Hesaplayıcı, hamilelik tarihlemesi veya tıbbi kararlar almak için tek yöntem olarak kullanılmamalıdır. Doğru hamilelik tarihleme, tam tıbbi geçmişinizi değerlendirebilen, fiziksel muayeneler yapabilen, ultrasonlar yapabilen ve birden fazla bilgi kaynağını entegre edebilen kalifiye sağlık hizmeti sağlayıcıları tarafından kapsamlı değerlendirme gerektirir. Profesyonel doğum öncesi bakım aramayı geciktirmek veya bundan kaçınmak için asla bu hesaplayıcıyı kullanmayın. Düzenli doğum öncesi randevular, anne ve fetal sağlığı izlemek, potansiyel komplikasyonları erken tespit etmek, gerekli tarama testlerini gerçekleştirmek ve güvenli doğuma hazırlanmak için esastır. Hamile kadınlar, hamilelik doğrulandığında bir doğum uzmanı, ebe veya diğer kalifiye doğum öncesi bakım sağlayıcısı ile doğum öncesi bakım kurmalıdır. Bu hesaplayıcı sağlanan tarihlerin doğru olduğunu varsayar—yanlış bilgi yanlış sonuçlar üretecektir. Düzensiz adet döngüleri, belirsiz SAT tarihleri, son hormonal kontraseptif kullanımı, hamile kalırken emzirme, PKOS veya diğer üreme sağlığı durumları olan kadınlar SAT tabanlı hesaplamalar yerine ultrason tarihlemesine ihtiyaç duyar. Bu hesaplayıcı tıbbi komplikasyonları, önceki hamilelik geçmişini, anne sağlık durumlarını, ilaçları veya hamilelik uzunluğunu etkileyebilecek veya erken doğumu gerektirebilecek diğer faktörleri hesaba katmaz. Vajinal kanama, şiddetli karın ağrısı, görme değişiklikleriyle birlikte kalıcı baş ağrıları, azalmış fetal hareket, preterm doğum belirtileri, sızan sıvı veya endişe verici semptomlar yaşıyorsanız derhal tıbbi yardım alın. Sağlanan bilgiler tıbbi tavsiye oluşturmaz ve herhangi bir tıbbi durumu kendi kendine teşhis etmek veya kendi kendine tedavi etmek için kullanılmamalıdır. Kişiselleştirilmiş tıbbi rehberlik, teşhis testi ve tedavi önerileri için her zaman kalifiye sağlık profesyonellerine danışın. Hamilelik yönetimi, benzersiz koşullarınızı, tıbbi geçmişinizi ve mevcut sağlık durumunuzu dikkate alan bireyselleştirilmiş bakım gerektirir.',

    references: [
      'Amerikan Kadın Doğum Uzmanları Koleji (ACOG). Doğum Tarihini Tahmin Etme Yöntemleri. Komite Görüşü No. 700. Obstet Gynecol. 2017;129:e150-4.',
      'Dünya Sağlık Örgütü. Olumlu bir hamilelik deneyimi için doğum öncesi bakıma ilişkin WHO önerileri. Cenevre: WHO; 2016.',
      'Sağlık ve Bakım Mükemmelliği Ulusal Enstitüsü (NICE). Komplike olmamış hamileliklerde doğum öncesi bakım. Klinik kılavuz [CG62]. 2008, 2021 güncellemesi.',
      'Naegele FC. Erfahrungen und Abhandlungen aus dem Gebiethe der Krankheiten des weiblichen Geschlechtes nebst Grundriss einer Geschichte der Geburtshülfe. Heidelberg: August Oswald; 1812.',
      'Mongelli M, Wilcox M, Gardosi J. Doğum tarihinin tahmini: belirli adet tarihlerine karşı ultrasonografik biyometri. Am J Obstet Gynecol. 1996;174(1):278-281.',
      'Butt K, Lim K; Sonografi Komitesi. Ultrason ile gestasyonel yaş belirleme. J Obstet Gynaecol Can. 2014;36(2):171-181.',
      'Hoffman CS, Messer LC, Mendola P, ve ark. Son adet dönemi ve ilk trimesterde ultrason temelinde doğumdaki gestasyonel yaşın karşılaştırılması. Paediatr Perinat Epidemiol. 2008;22(6):587-596.',
      'Savitz DA, Terry JW Jr, Dole N, ve ark. Son adet dönemi, ultrason taraması ve bunların kombinasyonu ile hamilelik tarihlemesinin karşılaştırılması. Am J Obstet Gynecol. 2002;187(6):1660-1666.',
    ],

    tips: [
      'Gelecekteki hamilelik planlaması için SAT tarihinizi doğru bir şekilde bilmek için adet döngülerinizi bir takvim veya uygulama kullanarak takip edin',
      'İlk trimester ultrasonu (8-13 hafta) en doğru doğum tarihini sağlar—SAT\'ınız belirsizse erken tarihleme talep edin',
      'Doğum tarihinizin doğumun beklendiği 5 haftalık bir pencereyi (37-42 hafta) kapsayan bir tahmin olduğunu unutmayın',
      '37. haftadan itibaren doğuma hazırlanın—hastane çantasını hazırlayın, doğum planını tamamlayın ve doğum sonrası desteği erken düzenleyin',
      'Büyümeyi izlemek, testleri gerçekleştirmek ve doğum planlarını güncellemek için planlanmış tüm doğum öncesi randevularınıza katılın',
      'Doğum tarihi yaklaştıkça kaygıyı azaltmak için belirli bir tarih yerine "doğum ayına" hazırlanmaya odaklanın',
      'İlk kez anneler genellikle doğum tarihlerinden 3-5 gün sonra doğum yapar—tam tarih için ziyaretçi veya taahhütler planlamaktan kaçının',
      'İndüksiyon politikalarını sağlık hizmeti sağlayıcınızla görüşün—hangi noktada (genellikle 41-42 hafta) indüksiyonun önerileb ileceğini anlayın',
      '28. haftadan itibaren fetal hareketleri izleyin—azalmış hareket fark ederseniz sağlayıcınızla derhal iletişime geçin',
      'İkinci trimesterde (çok rahatsız olmadan önce) doğum eğitim sınıflarına katılarak zihinsel ve fiziksel olarak hazırlanın',
      'Doğum tarihiniz ultrasona göre ayarlanırsa, sağlayıcınıza nedenini sorun ve hangi tarihleme yönteminin en güvenilir kabul edildiğini anlayın',
      'Tüp bebek hamilelikleri için, döllendirme tarihi kesin olarak bilindiği için doğum tarihiniz son derece doğrudur—daha sonraki ultrasonlar yerine bu tarihlemeye güvenin',
    ],

    faqs: [
      {
        question: 'Doğum tarihi hesaplayıcısı ne kadar doğrudur?',
        answer:
          'Doğum tarihi hesaplayıcıları, kullanılan yönteme bağlı olarak değişen doğruluğa sahip tahminler sağlar. SAT tabanlı hesaplamalar düzenli 28 günlük döngülere sahip kadınlar için 1-2 hafta içinde doğrudur, ancak düzensiz döngüler için daha az doğrudur. İlk trimester ultrasonu (8-13 hafta) en doğru yöntemdir ve hamileliği 3-5 gün içinde tarihler. İkinci trimester ultrasonları 7-10 gün içinde doğruyken, üçüncü trimester ultrasonları bireysel büyüme varyasyonları nedeniyle yalnızca 2-3 hafta içinde doğrudur. Tüp bebek tarihleme son derece doğrudur çünkü kesin döllendirme tarihi bilinir. Bebeklerin yalnızca yaklaşık %5\'i tam doğum tarihlerinde gelir, ancak yaklaşık %90\'ı tahmini tarihten iki hafta içinde (önce veya sonra) doğar. Sağlık hizmeti sağlayıcınız mevcut en güvenilir tarihleme yöntemini kullanacak ve erken ultrason ölçümleri adet tarihlemesinden önemli ölçüde farklıysa doğum tarihinizi ayarlayabilir.',
      },
      {
        question: 'Son adet dönemimi hatırlamıyorsam ne olur?',
        answer:
          'SAT tarihinizi hatırlayamıyorsanız veya düzensiz döngüleriniz varsa, sağlık hizmeti sağlayıcınız doğum tarihinizi belirlemek için ultrason tarihleme kullanacaktır. İlk trimester ultrasonu (ideal olarak 8-13 hafta arasında) tepe-makat uzunluğunu ölçer ve 3-5 gün içinde doğru tarihleme sağlar. Bu aslında birçok kadın için adet tarihlemesinden daha doğrudur. Ultrason tarihleme, düzensiz döngüleri, son hormonal kontraseptif kullanımı, belirsiz SAT tarihleri, hamile kalırken emzirme veya PKOS olan kadınlar için tercih edilen yöntemdir. Ultrason ne kadar erken yapılırsa, tarihleme o kadar doğru olur. Zaten ikinci trimesterdeyseniz, ultrason hala tarihleme sağlayabilir, ancak biraz daha az hassasiyetle (7-10 gün içinde). SAT tarihinizi asla tahmin etmeyin, çünkü yanlış bilgi yanlış tarihlemeye ve potansiyel olarak uygunsuz tıbbi kararlara yol açar.',
      },
      {
        question: 'Ultrasondan sonra doğum tarihim neden değişti?',
        answer:
          'Sağlık hizmeti sağlayıcıları, erken ultrason ölçümleri SAT tabanlı tarihlemeden önemli ölçüde farklıysa doğum tarihinizi ayarlayabilir. ACOG kılavuzlarına göre, ilk trimester ultrasonu gestasyonel yaşın SAT tarihlemesinden 5-7 günden fazla farklı olduğunu gösteriyorsa, daha doğru olduğu için ultrason tarihi kullanılmalıdır. Bu, kadınların düzensiz döngülere sahip olması, SAT\'larını yanlış hesaplaması veya implantasyon kanamalarını adet ile karıştırması durumunda yaygın olarak gerçekleşir. En güvenilir yöntem (tipik olarak ilk trimester ultrasonu) kullanılarak oluşturulduktan sonra, doğum tarihiniz tutarlı kalmalı ve üçüncü trimesterde 2 haftadan fazla tutarsızlık olmadıkça daha sonraki ultrasonlarla değiştirilmemelidir. Daha sonraki ultrasonlar bireyler arasında değişen bebek büyüklüğünü ölçer ve onları tarihleme için daha az güvenilir yapar. Ayarlanan doğum tarihi yanlış değildir—sadece ilk tahminden daha doğru bilgiyi yansıtır.',
      },
      {
        question: 'Doğum tarihimi geçersem bebeğim geç mi doğdu?',
        answer:
          'Hayır, bebeğiniz 42 haftalık hamilelikten sonraya kadar geç doğmuş kabul edilmez. 40. haftadaki doğum tarihi bir tahmindir ve normal hamilelik 37 ila 42 hafta arasında herhangi bir yerde sürer. 37-38. hafta arasında doğan bebekler "erken term", 39-40 hafta "tam term" (optimal), 41 hafta "geç term" ve 42+ hafta "postterm"dir. Kadınların yaklaşık %50\'si doğum tarihlerinden sonra doğum yapar, özellikle doğum tarihlerinden ortalama 3-5 gün sonra gitme eğiliminde olan ilk kez anneler. Çoğu sağlık hizmeti sağlayıcısı sizi 40 haftadan sonra non-stress testleri ve amniyotik sıvı kontrolleri içerebilen haftalık veya haftada iki kez randevularla yakından izleyecektir. İndüksiyon genellikle 41. hafta civarında tartışılır ve postterm hamilelikle ilişkili artan riskler nedeniyle genellikle 42. haftaya kadar önerilir. Ancak, indüksiyon zamanlaması sağlığınıza, bebeğin durumuna ve servikal hazırlığa göre bireyselleştirilir.',
      },
      {
        question: 'Stres veya aktivite ne zaman doğum yapacağımı etkiler mi?',
        answer:
          'Hamilelik sırasında kronik şiddetli stres hafif artmış preterm doğum riskiyle ilişkiliyken, normal günlük stres veya makul fiziksel aktivite ne zaman doğum yapacağınızı önemli ölçüde değiştirmez veya bebeğinizin erken veya geç gelmesini sağlamaz. Vücudunuz, bebek ve plasenta hazır olduğunda bilinçli kontrolünüz aracılığıyla değil, karmaşık hormonal sinyaller yoluyla doğum başlangıcını belirler. Hamilelik sırasında orta düzeyde egzersiz güvenli ve faydalıdır ve çalışmak (işiniz ağır fiziksel emek veya uzun süreli ayakta durmayı içermedikçe) genellikle sağlıklı hamileliklerde erken doğumu tetiklemez. Ancak, çok yüksek stres seviyeleri, yetersiz dinlenme, kötü beslenme veya fiziksel olarak zorlu iş hassas kadınlarda preterm doğum riskine katkıda bulunabilir. Hamilelik sırasında güvenli olan aktiviteler, vücudunuz ve bebeğiniz hazır olmadan önce doğumun başlamasına neden olmaz. Tam terme (37+ hafta) ulaştığınızda, yürüyüş, seks, meme ucu uyarımı ve baharatlı yiyecekler genellikle doğumu teşvik etmek için önerilir, ancak bu yöntemlere ilişkin bilimsel kanıtlar sınırlıdır—vücudunuz zaten doğuma hazırlanıyorsa serviksin olgunlaşmasına yardımcı olabilirler ancak fizyolojik olarak hazır değilseniz doğumun başlamasını zorlayamazlar.',
      },
      {
        question: 'İkizler için doğum tarihi nasıl hesaplanır?',
        answer:
          'İkiz hamilelikleri için, doğum tarihi hala SAT\'tan 40 hafta veya erken ultrasona göre olarak hesaplanır, ancak ikizler genellikle tekillerden daha erken doğar. İkizler için ortalama doğum süresi 37. hafta civarındadır, ancak birçok ikiz 35-37. haftalar arasında doğar. Üçüzler ortalama 33 hafta ve dörtüzler yaklaşık 30 hafta. Ancak, standart doğum tarihi hesaplayıcıları tek bebek hamilelikleri varsayar ve çoğullar için ayarlama yapmaz. Sağlık hizmeti sağlayıcınız ikiz hamilelikleri daha sık ultrasonlar ve randevularla daha yakından izleyecektir. Birçok sağlayıcı, riskleri azaltmak için komplike olmamış ikiz hamilelikleri için 38-39. haftaya kadar doğumu önerir ve bazı ikizler komplikasyonlar ortaya çıkarsa daha erken doğurtulur. Tarihleme yöntemi (SAT veya ultrason) ikizler için de tekillerle aynıdır, ancak yönetim ve doğum planlaması önemli ölçüde farklıdır. İkiz hamilelikleri her zaman daha yüksek riskli kabul edilir ve özel obstetrik bakım gerektirir.',
      },
      {
        question: 'Doğum tarihim haftalar veya aylar kadar yanlış olabilir mi?',
        answer:
          'Doğum tarihiniz ilk trimester ultrasonuna dayalıysa, 5-7 günden fazla yanlış olması pek olası değildir. Ancak, tarihleme yalnızca ultrason onayı olmadan belirsiz adet geçmişine dayalıysa, potansiyel olarak haftalar kadar uzakta olabilir. Bu nedenle ACOG, özellikle düzensiz döngüleri veya belirsiz SAT\'ı olan kadınlar için ultrason tarihlemesini önerir. Doğum tarihlerinin önemli ölçüde yanlış olduğu (aylar kadar) vakalar son derece nadirdir ve genellikle yalnızca doğum öncesi bakımı olmayan ve belirsiz SAT\'ı olan çok düzensiz döngülere sahip kadınlarda meydana gelir. Bu tür vakalar, emzirirken gebe kalan (bastırılmış adetler), doğum kontrolünden çıkan (döngülerin düzensiz dönüşü) veya PKOS\'lu kadınları içerebilir. İlk trimester ultrasonu, tarihlemenin bir haftadan fazla uzakta olma olasılığını esasen ortadan kaldırır. Doğum tarihi doğruluğunuz hakkında endişeleriniz varsa, erken ultrason almayı veya incelemeyi sağlık hizmeti sağlayıcınızla görüşün. İlk trimesterde belirlenen tarihleme, bebek büyüklüğünü (değişir) ölçen gelişim yaşı yerine daha sonraki ultrasonlara güvenilmelidir.',
      },
    ],
  },
};
