import { CalculatorContent } from '@/types/calculator';

export const waistHipRatioContent: CalculatorContent = {
  en: {
    whatIs:
      'The waist-to-hip ratio (WHR) is a standardized anthropometric measurement developed and endorsed by the World Health Organization (WHO) to evaluate the distribution of body fat across the body. It compares the circumference of your waist to the circumference of your hips, producing a simple ratio that indicates how much fat is concentrated around your midsection relative to your hips. This distinction is critically important in health assessment because not all body fat carries the same metabolic risk — where your body stores fat has profound implications for chronic disease outcomes. Central obesity, meaning excess fat stored predominantly around the abdomen and torso (often described as an "apple" body shape), is a well-established risk factor for cardiovascular disease, type 2 diabetes, hypertension, metabolic syndrome, and certain cancers. In contrast, peripheral fat stored around the hips and thighs (a "pear" body shape) is generally considered metabolically less harmful. WHR was one of the first anthropometric tools to be widely adopted in epidemiological and clinical research specifically for cardiovascular risk prediction. It is simple to calculate, requires no specialized equipment beyond a measuring tape, is completely non-invasive, and can be performed anywhere. For individuals looking to proactively monitor their health, WHR provides a valuable lens beyond BMI — which only reflects total body weight relative to height — by offering direct insight into the fat distribution pattern that most closely correlates with serious chronic disease outcomes.',

    howToCalculate:
      'Calculating your waist-to-hip ratio requires only a flexible measuring tape and two straightforward body measurements. For the most consistent and accurate results, take your measurements in the morning before eating or drinking, while wearing minimal clothing, and try to have someone else perform the measurements to avoid self-measurement bias. To measure your waist circumference, stand naturally and relax your abdomen completely — do not hold your breath, suck in, or push out. Wrap the measuring tape around your midsection at the narrowest point of your torso, which is typically located just above your navel (belly button). Keep the tape snug against your skin but without compressing or pulling the tissue, and ensure the tape is horizontal and level all the way around. Record the measurement. To measure your hip circumference, continue standing upright and place the measuring tape around the widest part of your buttocks. The tape should again be snug but not tight, kept horizontal and parallel to the floor. Record this measurement. Both measurements should be taken in the same unit — either both in centimeters or both in inches. Once you have entered both measurements and selected your biological sex, our calculator will compute your WHR and classify your result into a risk category based on WHO guidelines. For meaningful health tracking over time, repeat measurements monthly under the same conditions and compare trends rather than fixating on any single reading.',

    formulaDetails:
      'The waist-to-hip ratio is defined by a straightforward mathematical formula: WHR = Waist Circumference ÷ Hip Circumference. Because both the numerator and denominator share the same unit of measurement, the resulting ratio is dimensionless — the specific unit used does not affect the final value. A person measuring 82 cm waist and 104 cm hip will arrive at the same ratio (0.79) as someone measuring 32.3 inches waist and 40.9 inches hip. The WHO established gender-specific risk classification thresholds based on large-scale epidemiological studies that correlated body fat distribution with cardiovascular morbidity and mortality. For men, a WHR below 0.90 is classified as low risk, a WHR from 0.90 to 0.99 is classified as moderate risk, and a WHR of 1.00 or above is classified as high risk. For women, a WHR below 0.80 is low risk, 0.80 to 0.84 is moderate risk, and 0.85 or above is high risk. These thresholds differ between sexes because men and women have fundamentally different natural fat distribution patterns driven by their hormonal profiles. Testosterone promotes android (abdominal) fat storage in men, while estrogen promotes gynoid (hip and thigh) fat storage in women. The gender-specific cutoffs therefore represent meaningful risk boundaries within the physiological context of each sex. It is important to note that these thresholds were derived primarily from research on European and North American populations and may require adjustment for other ethnic groups.',

    interpretation:
      'Understanding what your WHR number means requires considering the result alongside the broader context of your overall health and lifestyle. A low-risk WHR — below 0.90 for men and below 0.80 for women — indicates a relatively favorable fat distribution profile, with proportionally less fat stored around the abdomen. This is a positive indicator, though it does not by itself guarantee excellent health; someone could have a low WHR while still being significantly overweight if their excess fat is concentrated primarily around the hips and thighs. A moderate-risk WHR — 0.90 to 0.99 for men, or 0.80 to 0.84 for women — signals meaningful abdominal fat accumulation that warrants attention. Individuals in this range are encouraged to evaluate and potentially adjust their lifestyle: incorporating regular physical activity (a mix of cardiovascular and strength training is most effective for reducing abdominal fat), improving dietary habits with an emphasis on whole foods and lean proteins, getting adequate sleep, and managing stress — as chronic stress elevates cortisol, which promotes abdominal fat storage. A high-risk WHR — 1.00 or above for men, 0.85 or above for women — indicates significant central obesity and is directly associated with elevated risks of cardiovascular disease, type 2 diabetes, and metabolic syndrome. Anyone with a high-risk WHR is strongly encouraged to consult a healthcare provider for a comprehensive metabolic health evaluation. The most valuable use of WHR is as a tracking tool: measuring periodically and observing the trend over weeks and months provides far more meaningful health information than any single measurement.',

    limitations:
      'Despite its widespread clinical use, the waist-to-hip ratio has several important limitations. Measurement sensitivity is a key concern — small differences in tape placement or tension can shift the ratio enough to change the risk classification, making consistent technique essential across repeated measurements. WHR cannot distinguish between visceral fat (the deep, metabolically active fat surrounding organs) and subcutaneous fat (the less dangerous fat just beneath the skin); it captures both types simultaneously, even though visceral fat is the primary driver of cardiometabolic risk. The ratio can also remain unchanged even when total body fat increases, if fat accumulates proportionally around both the waist and the hips. This makes WHR less sensitive to certain patterns of gradual weight gain than waist circumference alone. Muscle mass can influence results in counterintuitive ways: an individual with significant gluteal muscle mass will have a larger hip circumference and therefore a lower ratio, even if their abdominal fat is meaningful. The standard WHO thresholds were developed using primarily European and North American study populations and may not be equally valid across all ethnicities — particularly South Asian and East Asian populations, who may face elevated cardiometabolic risk at lower WHR values than the standard cutoffs suggest. Finally, age, hormonal status (particularly menopause), pregnancy, and certain medications can all influence fat distribution independently of diet or exercise, limiting WHR reliability during these periods.',

    healthRisks:
      'Elevated waist-to-hip ratio is linked to a broad spectrum of serious chronic health conditions, reflecting the systemic metabolic effects of excess central body fat. Cardiovascular disease — including coronary artery disease, heart attack, and stroke — is among the most extensively documented consequences. Visceral abdominal fat is metabolically active tissue that releases pro-inflammatory molecules (cytokines and adipokines), which promote arterial inflammation, impair blood vessel function, increase clotting risk, and accelerate atherosclerosis. Type 2 diabetes risk is strongly linked to central fat distribution; visceral fat contributes to insulin resistance, meaning the body\'s cells respond less effectively to insulin\'s signal to absorb glucose, which can progress to chronic hyperglycemia and full type 2 diabetes with downstream effects including kidney disease, nerve damage, and vision impairment. Hypertension is closely correlated with abdominal obesity: excess visceral fat increases blood volume, triggers hormonal pathways that constrict blood vessels, and activates the sympathetic nervous system. Metabolic syndrome — the coexistence of central obesity, elevated blood sugar, high triglycerides, low HDL cholesterol, and high blood pressure — is strongly associated with high WHR and represents a compounding risk factor for both heart disease and diabetes. Research has also identified associations between central obesity and increased risks of certain cancers (including colorectal, endometrial, and breast cancers), non-alcoholic fatty liver disease, and sleep apnea. The encouraging reality is that these risks are substantially modifiable; even moderate reductions in abdominal fat through sustained dietary improvements and regular physical activity can meaningfully lower cardiometabolic risk within months.',

    alternativeMeasures:
      'Several complementary body composition and health metrics can be used alongside or instead of WHR, each with distinct strengths and limitations. Body Mass Index (BMI) remains the most widely recognized general health screening tool, calculated by dividing weight in kilograms by height in meters squared. However, BMI provides no information about fat distribution or body composition — it treats muscle and fat as equivalent, meaning a muscular athlete can register as "overweight" while being metabolically healthy. Waist circumference alone has gained increasing favor as a simpler and potentially more powerful predictor of cardiovascular risk than WHR, because it directly measures abdominal size without being influenced by variations in hip size. The WHO defines high-risk waist circumference as above 102 cm for men and above 88 cm for women. Body fat percentage, measured via DEXA scanning (gold standard), bioelectrical impedance, or skinfold calipers, provides a more complete picture of overall body composition by quantifying the proportion of total body weight that is fat versus lean tissue. Some advanced DEXA systems can also distinguish visceral from subcutaneous fat. The waist-to-height ratio (WHtR), calculated as waist circumference divided by height, has emerged in recent research as a particularly promising universal screening metric — a WHtR of 0.5 or above has been proposed as a gender-neutral cutoff for elevated cardiometabolic risk that works reasonably well across diverse populations. For the most complete health picture, experts increasingly recommend combining multiple metrics — such as WHR, waist circumference, and BMI — with blood-based assessments (cholesterol, blood sugar, inflammatory markers) rather than relying on any single measurement.',

    demographicDifferences:
      'Body fat distribution patterns — and therefore meaningful WHR interpretation — vary substantially across demographic groups. Biological sex is the most fundamental axis of difference: men tend to store more fat in the abdominal region (android distribution), naturally producing higher WHR values, while women tend to store more fat around the hips and thighs (gynoid distribution), producing lower values. This is why separate risk thresholds exist for each sex. After menopause, however, women\'s fat distribution shifts toward the android pattern as estrogen levels decline, often increasing WHR even without significant overall weight gain. Age plays a significant role beyond menopause: WHR tends to increase gradually across adulthood for both sexes as abdominal fat accumulates and gluteal muscle mass decreases. Standard adult WHR thresholds should not be applied to children and adolescents. Ethnic and racial differences in fat distribution are significant and represent a major limitation of the standard WHO cutoffs. South Asian populations tend to accumulate visceral fat at lower body weights than European populations and may face elevated cardiovascular risk at WHR values considered "low risk" under standard guidelines. East Asian populations show similar tendencies. These differences mean the WHO thresholds may underestimate risk for some populations and overestimate it for others. Hormonal conditions including PCOS, hypothyroidism, and Cushing\'s syndrome can profoundly alter fat distribution independently of dietary intake or activity level. Lifestyle and physical activity interact with all these factors: highly active individuals of any demographic typically have more favorable fat distribution patterns, with less visceral fat accumulation, regardless of baseline predisposition.',

    medicalDisclaimer:
      'This waist-to-hip ratio calculator is intended for educational and general informational purposes only and must not be used as a substitute for professional medical advice, diagnosis, or treatment. The risk classifications provided are based on WHO guidelines derived primarily from European and North American research populations and may not accurately represent health risk for individuals of other ethnic backgrounds. WHR is a single measurement taken at one point in time and cannot capture the full complexity of cardiovascular or metabolic health; it should be interpreted alongside other clinical indicators. This tool is not appropriate for children under 18, pregnant or breastfeeding women, individuals with a current or past history of eating disorders, or individuals with conditions known to substantially affect body fat distribution (including Cushing\'s syndrome, hypothyroidism, PCOS, or those taking medications such as corticosteroids, insulin, or hormonal therapies). A low-risk WHR result does not guarantee absence of cardiovascular or other health risks — smoking status, family history, blood pressure, cholesterol, physical activity, and diet quality all contribute independently to overall disease risk. A moderate or high-risk WHR does not constitute a diagnosis but does warrant discussion with a qualified healthcare professional. If your result indicates moderate or high risk, please consult a physician or registered dietitian who can conduct a comprehensive assessment tailored to your individual health profile.',

    references: [
      'World Health Organization. Obesity: preventing and managing the global epidemic. Report of a WHO consultation on obesity. WHO Technical Report Series, 894. Geneva: WHO; 2000.',
      'Alberti KG, Zimmet P, Shaw J. Metabolic syndrome — a new classification from the International Diabetes Federation. Diabet Med. 2006;23(5):579-582.',
      'Ashwell M, Gunn P, Gibson S. Waist-to-height ratio is a better predictor of a healthy weight than BMI for both men and women. Obes Rev. 2012;13(3):275-284.',
      'Mishra AK, Arora NJ, Kaur L. Body adiposity measures as predictors of metabolic syndrome in Indian population. J Commun Med Public Health. 2019;34(2):103-108.',
      'Riddell JM. Using the waist:hip ratio to assess the risk of cardiovascular disease. Med J Aus. 2001;175(2):97-98.',
      'WHO Expert Consultation. Waist circumference and waist-hip ratio: report of an expert consultation. Geneva: World Health Organization; 2008.',
    ],

    tips: [
      'Take measurements first thing in the morning, before eating or drinking, for the most consistent results.',
      'Use a flexible, non-stretchable measuring tape — a tailor\'s tape works well. Avoid string or rigid rulers.',
      'Have another person take your measurements whenever possible, especially for hip circumference, to minimize self-measurement bias.',
      'Track your WHR monthly rather than daily. Day-to-day fluctuations from hydration and bloating can shift measurements by several millimeters.',
      'Combine WHR monitoring with regular blood work — fasting blood sugar, lipid panel, and blood pressure — for a comprehensive cardiovascular risk picture.',
      'Focus on sustainable lifestyle habits rather than the number itself: regular physical activity, a diet rich in vegetables and whole foods, adequate sleep, and stress management all contribute to reducing abdominal fat.',
      'Abdominal fat is among the most responsive fat deposits to lifestyle changes. Consistent caloric moderation combined with regular exercise can produce meaningful WHR improvement within several months.',
    ],

    faqs: [
      {
        question: 'Is WHR a better health predictor than BMI?',
        answer:
          'WHR and BMI measure different things. BMI reflects total body weight relative to height but tells you nothing about where fat is distributed. WHR specifically reveals the pattern of fat distribution, which is more directly relevant to cardiovascular and metabolic disease risk. Most health experts recommend using multiple metrics together — including WHR, BMI, and waist circumference — rather than relying on any single number for a complete health assessment.',
      },
      {
        question: 'Why do men and women have different WHR thresholds?',
        answer:
          'Men and women have fundamentally different hormonal profiles that drive different fat storage patterns. Testosterone promotes fat accumulation around the abdomen in men, while estrogen promotes fat storage around the hips and thighs in women. These natural physiological differences mean that the same WHR value carries different health implications depending on biological sex, which is why the WHO established separate thresholds for each.',
      },
      {
        question: 'Can I lower my WHR through lifestyle changes?',
        answer:
          'Yes. WHR responds to lifestyle modifications, particularly reductions in abdominal fat. Regular physical activity — especially a combination of cardiovascular exercise and resistance training — paired with a balanced diet can reduce abdominal fat over weeks and months. Adequate sleep (7–9 hours) and stress management are also important, as chronic stress and sleep deprivation both promote abdominal fat accumulation. Results are typically gradual rather than immediate.',
      },
      {
        question: 'Does WHR change as I get older?',
        answer:
          'Yes, WHR naturally tends to increase with age for both sexes. This is driven by age-related increases in abdominal fat and decreases in gluteal muscle mass. For women, menopause is a particularly significant turning point, as declining estrogen levels shift fat distribution from the hips toward the abdomen. This makes maintaining healthy lifestyle habits — especially physical activity — increasingly important as you age.',
      },
      {
        question: 'My WHR shows high risk — what should I do?',
        answer:
          'A high-risk WHR is not a diagnosis but a meaningful signal worth acting on. Schedule an appointment with your healthcare provider to discuss the result and request a comprehensive cardiometabolic risk assessment, typically including blood pressure, a fasting lipid panel, and fasting blood glucose. Your provider can then help develop a personalized plan based on your complete health profile.',
      },
      {
        question: 'Are the WHR thresholds accurate for my ethnicity?',
        answer:
          'The standard WHO WHR thresholds were established primarily from European and North American populations and may not be optimally calibrated for all ethnic groups. Research indicates that individuals of South Asian and East Asian descent may face elevated cardiovascular risk at WHR values considered "low risk" under standard cutoffs. If your heritage is from one of these regions, it is advisable to discuss your result with a healthcare provider familiar with these ethnic variations.',
      },
    ],
  },

  tr: {
    whatIs:
      'Bel-kalça oranı (BKO), vücut yağ dağılımını değerlendirmek için Dünya Sağlık Örgütü (DSÖ) tarafından geliştirilen ve standartlaştırılan bir sağlık ölçüm yöntemidir. Bel çevresini kalça çevresiyle karşılaştırarak ortaya çıkan oranın, özellikle bel bölgesindeki yağın kalçaya oranla ne kadar olduğunu gösterdiği bir metrikdir. Bu ölçüm sağlık değerlendirmesinde son derece önemlidir; çünkü tüm vücut yağı eşit metabolik risk taşımaz — vücudun yağı nerede depoladığı, kronik hastalık sonuçları üzerinde ciddi bir etki yaratır. Merkezi obesite yani mide çevresinde yoğunlaşan aşırı yağ ("elma" vücut tipi), kardiyovasküler hastalık, tip 2 diyabet, hipertansiyon, metabolik sendrom ve bazı kanser türleriyle doğrudan ilişkilendirilmiştir. Buna karşın kalça ve bacak çevresinde depolanan çevre yağı ("armut" vücut tipi) metabolik açıdan daha az tehlikeli kabul edilir. BKO, kardiyovasküler hastalık riskinin tahmin edilmesi amacıyla epidemiyoloji ve klinik araştırmalarda yaygın biçimde kullanılan ilk antropometrik araçlardan biridir. Yalnızca bir mezura ile yapılabilir, hiçbir özel ekipman gerektirmez ve yıkayıcı olmayan bir yöntemdir. Sağlığını yakından takip etmek isteyen bireyler için BKO, yalnızca toplam vücut ağırlığını yükseklikle ilişkilendiren VKİ\'nin ötesinde son derece yararlı bilgiler sunar.',

    howToCalculate:
      'Bel-kalça oranınızı hesaplamak için yalnızca esnek bir mezura ve iki basit ölçüm yeterlidir. En tutarlı ve doğru sonuçlar için ölçümleri sabah yemek ve su içmeden önce, az sayıda kıyafet giyerken alınması önerilir. Ayrıca mümkün olsa başkasının ölçüm yapmasını sağlamak, kendi kendini ölçme hatalarını azaltır. Bel çevresini ölçmek için dik durun ve karniyanızı tamamen rahatlatın — nefes tutmayın, karnı içeri çekmeyim ya da dışarı itmeyin. Mezurayı bel bölgesinin en dar noktasına, genellikle göbek deliğinin hemen üstine doladın. Mezura cilde temas etmeli ancak dokuyu sıkıştırmamalıdır; tüm çevre boyunca yatay tutulmalıdır. Kalça çevresini ölçmek için de dik durarak mezurayı kalça çıkıntısının en geniş noktasına doladın. Burada da mezura snug ancak sıkı olmalı, yatay tutulmalıdır. Her iki ölçüm de aynı birimde (her ikisi cm veya her ikisi inç) alınmalıdır. İki ölçümü girdikten ve cinsiyet seçtiğinizde hesaplayıcı BKO\'nuzla birlikte DSÖ kılavuzlarına göre risk kategorisini belirleyecektir. Anlamlı sağlık takibi için ölçümleri aylık bazda, aynı koşullar altında tekrarlanması önerilir.',

    formulaDetails:
      'Bel-kalça oranı basit bir matematiksel formülle hesaplanır: BKO = Bel Çevresi ÷ Kalça Çevresi. Hem pay hem de payda aynı ölçüm birimi taşıdığından sonuç birimsi bir sayı olarak ortaya çıkar — kullanılan birim (santimetre veya inç) son değeri etkilemez. DSÖ, yağ dağılımı ile kardiyovasküler hastalık arasındaki ilişkiyi araştıran büyük ölçekli epidemiyolojik çalışmalara dayanarak cinsiyete özel risk sınıflandırma eşikleri belirlemiştir. Erkekler için: BKO 0.90\'ın altı düşük risk, 0.90 ile 0.99 arası orta risk, 1.00 ve üstü yüksek risk olarak sınıflandırılır. Kadınlar için: BKO 0.80\'in altı düşük risk, 0.80 ile 0.84 arası orta risk, 0.85 ve üstü yüksek risk olarak sınıflandırılır. Bu eşikler erkekler ve kadınlar için farklıdır; çünkü iki cinsin hormonal yapıları nedeniyle doğal yağ dağılım kalıpları temel olarak farklıdır. Testosteron erkeklerde karın bölgesinde yağ depolanmasını teşvik ederken, estrogen kadınlarda kalça ve bacak çevresinde yağ depolanmasını destekler. Cinsiyete özel eşikler bu fizyolojik farklılıkları hesaba katmaktadır. Bu eşiklerin esas olarak Avrupa ve Kuzey Amerika nüfuslarında yürütülen araştırmalardan elde edildiğini de belirtmek gerekir.',

    interpretation:
      'BKO sonucunuzun ne anlama geldiğini anlamak için sonucu genel sağlık durumunuz ve yaşam tarzınızın bağlamında değerlendirmeniz önemlidir. Düşük risk BKO — erkekler için 0.90 altı, kadınlar için 0.80 altı — yağ dağılımında nispeten olumlu bir tablo gösterir; karın çevresinde orantısız yağ birikimi yoktur. Bu olumlu bir göstergedir, ancak tek başına mükemmel sağlığı garanti etmez. Orta risk BKO — erkekler için 0.90–0.99, kadınlar için 0.80–0.84 — anlamlı bir karın yağı birikiminin varlığına işaret eder. Bu aralıkta olanların yaşam tarzını gözden geçirmesi önerilir: düzenli fiziksel aktivite (karsiyo egzersiz ve direnç antrenmanının kombinasyonu karın yağı azaltmada en etkindir), tam tahıllı yiyecekler ve yağsız proteinlere dayanan dengeli bir beslenme, yeterli uyku ve stres yönetimi bunların başında gelir. Yüksek risk BKO — erkekler için 1.00 ve üstü, kadınlar için 0.85 ve üstü — önemli bir merkezi obesiteyi gösterir ve kardiyovasküler hastalık, tip 2 diyabet ve metabolik sendrom risklerinin belirgin biçimde arttığıyla doğrudan ilişkilidir. Yüksek risk sonucu alan bireyler bir sağlık profesyoneliyle iletişime geçmesi önerilir. BKO\'nun en yararlı kullanımı bir takip aracı olarak gerçekleşir; düzenli ölçümler ile haftalarca ve aylarca süren eğilimlerin izlenmesi tek bir ölçümün sağlayabileceğinden çok daha anlamlı sağlık bilgisi verir.',

    limitations:
      'Yaygın klinik kullanımına karşın, bel-kalça oranının bazı önemli sınırlamaları bulunmaktadır. Ölçüm hassasiyeti temel bir endişe kaynağıdır — mezuranın yerleştirme noktasında ya da germe miktarında küçük farklılıklar, oranı risk kategorisi değiştirecek ölçüde etkileyebilir; bu nedenle tekrarlanan ölçümlerde tutarlı teknik son derece önemlidir. BKO, viseral yağ (organları çevren derin, metabolik olarak aktif yağ) ile subkutan yağ (deri altında bulunan daha az zararlı yağ) arasında ayırt edemez; her ikisini aynı anda ölçür. Oranın da bir dezavantajı vardır: hem bel hem de kalça çevresinde orantılı yağ artışı olduğunda oran değişmez ve toplam karın yağı artışı tespit edilemez. Kas kütlesi de sonuçları beklenmedik yönlerde etkileyebilir: kalça bölgesinde yeterli kasmış kütlesine sahip olan biri daha düşük bir oran ortaya koyabilir, karın yağı önemli bile olsa. Standart DSÖ eşikleri ağırlıklı olarak Avrupa ve Kuzey Amerika nüfuslarında yapılan çalışmalardan türetilmiştir; Güney Asya ve Doğu Asya nüfusları standart kesme değerlerin altında bile yüksek risk taşıyor olabilir. Son olarak yaş, hormonal durum (özellikle menopoz), hamilelik ve bazı ilaçlar yağ dağılımını egzersiz veya diyetten bağımsız olarak etkiler.',

    healthRisks:
      'Yüksek bel-kalça oranı, merkezi vücut yağının sistemik metabolik etkileri nedeniyle geniş bir yelpazede ciddi kronik sağlık durumlarıyla ilişkilendirilmiştir. Kardiyovasküler hastalık — koronerarter hastalığı, kalp krizi ve stroke dahil — en kapsamlı biçimde belgelenen sonuçlar arasında yer alır. Viseral karın yağı, metabolik olarak aktif bir doku olarak pro-inflamatuar moleküller (sitokinler ve adipokikinler) salır; bunlar atardamarların iltihabını tetikler, kan damarlarının işlevini bozur, pıhtılaşma riskini artırır ve ateroskleroz oluşumunu hızlandırır. Tip 2 diyabet riski de merkezi yağ dağılımıyla güçlü biçimde bağlantılıdır; viseral yağ insulin direncine yol açar ve bu durum kronik hiperglisemi ile tip 2 diyabete ilerleyebilir. Hipertansiyon ise karın obesitesiyle yakın ilişkilidir: aşırı viseral yağ, kan hacmini artırır, kan damarlarını daraltacak hormonal yolları uyarır ve sempatatik sinir sistemi aktivasyonuna neden olur. Metabolik sendrom — merkezi obesite, yüksek kan şekeri, yüksek trigliseritler, düşük HDL kolesterol ve yüksek kan basıncının birlikte varlığı — yüksek BKO ile güçlü şekilde ilişkilidir. Araştırmalar ayrıca merkezi obesite ile bazı kanser türleri (kolon, rahim ve meme dahil), karaciğer yağlanma hastalığı ve uyku apnesi arasında da bağlantı ortaya koymuştur. Umut verici olan husus ise bu risklerin önemli ölçüde değiştirilebilir olmasıdır; sürdürülebilir diyetle düzenleme ve düzenli fiziksel aktiviteyle karın yağında bile küçük azalmalar, birkaç ay içinde metabolik riskleri anlamlı biçimde düşürebilir.',

    alternativeMeasures:
      'BKO\'nun yanı sıra veya yerine kullanılabilecek çeşitli vücut yapısı ve sağlık ölçümleri mevcuttur; bunların her birinin kendine özgü güçlü ve zayıf yönleri vardır. Vücut Kütle İndeksi (VKİ), en yaygın kullanılan genel sağlık tarama aracıdır; kilonun (kg) boy karesine (m²) bölünmesiyle hesaplanır. Ancak VKİ, yağ dağılımı veya vücut yapısı hakkında hiçbir bilgi sunmaz — kas ile yağı eşdeğer kabul eder. Bel çevresi tek başına, son yıllarda kardiyovasküler risk tahmininde BKO\'dan belki daha basit ve güçlü bir gösterge olarak artan bir ilgi çekmiştir; çünkü doğrudan karın boyutunu ölçür ve kalça boyutundaki farklılıklardan etkilenmez. DSÖ, yüksek risk bel çevresini erkekler için 102 cm, kadınlar için 88 cm üstü olarak tanımlar. Yağ yüzde oranı, DEXA tarama (altın standart), biyoelektriksel empedans analizi veya deri altı yağ kaliperlerinin kullanımıyla vücudun toplam ağırlığının ne kadarının yağ, ne kadarının yağsız doku olduğunu belirler. Bel-boy oranı (BBO) — bel çevresinin boya bölünmesi ile hesaplanır — son araştırmalarda özellikle umut verici evrensel bir tarama metrği olarak öne çıkmıştır; 0.5 ve üstü bir BBO değeri, farklı etnik kökenler genelinde iyi çalışan cinsiyet farkı gözetilmeksizin yüksek kardiyometabolik risk kesme noktası olarak önerilmiştir. En kapsamlı sağlık tablosu için uzmanlar artık yalnızca tek bir ölçüme dayanmak yerine BKO, bel çevresi ve VKİ gibi birden fazla metriği kan bazlı değerlendirmelerle (kolesterol, kan şekeri, inflamasyon belirteçleri) birleştirmeyi öneriyorlar.',

    demographicDifferences:
      'Vücut yağ dağılım kalıpları ve dolayısıyla anlamlı BKO yorum süreci demografik gruplar arasında önemli farklılıklar gösterir. Biyolojik cinsiyet en temel farklılık eksenidir: erkekler yağı daha çok karın bölgesinde depolar (android dağılım) ve doğal olarak daha yüksek BKO değerlerine sahiptir; kadınlar ise yağı kalça ve bacak çevresinde daha çok depolar (ginoid dağılım) ve daha düşük BKO değerleri ortaya çıkar. Bu nedenle her cinsiyet için ayrı risk eşikleri vardır. Ancak menopoz sonrası, kadınların yağ dağılım kalıbı estrogen düzeylerinin düşmesiyle android tipe kayar; bu durum önemli kilo değişikliği olmaksızın bile BKO\'nun artmasına yol açabilir. Yaş, menopozun ötesinde de önemli bir rol oynamaktadır: her iki cinsiyette de BKO, yetişkinlik boyunca karın yağı birikmesi ve kalça kaslarının azalmasıyla birlikte yavaş yavaş artar. Standart yetişkin BKO eşikleri çocuklara ve genç ergenlik çağındakilere uygulanmamalıdır. Etnik ve ırki farklılıklar, yağ dağılımında son derece önemlidir ve standart DSÖ kesme değerlerinin temel bir sınırlamasını oluşturur. Güney Asya nüfusları (Hindistan, Pakistan, Bangladeş), Avrupalı nüfuslara kıyasla daha düşük vücut ağırlığında viseral yağ eğilimi taşır ve standart kılavuzlarda "düşük risk" sayılan BKO değerlerinde bile yükselen kardiyometabolik risk altında olabilir. Doğu Asya nüfusları da benzer eğilimler gösterir. PKOS, hipotiroidizm ve Cushing sendromu gibi hormonal durumlar, beslenme veya aktiviteden bağımsız olarak yağ dağılımını köklü biçimde değiştirebilir. Yaşam tarzı ve fiziksel aktivite ise tüm bu faktörlerle etkileşir: yoğun fiziksel aktivite yapan bireyler, demografik kökenlerinden bağımsız olarak genellikle daha olumlu bir yağ dağılım kalıbına sahiptir.',

    medicalDisclaimer:
      'Bu bel-kalça oranı hesaplayıcısı yalnızca eğitim ve genel bilgilendirme amaçlı olarak hazırlanmıştır; profesyonel tıbbi danışmanlık, tanı veya tedavinin yerini almamalıdır. Sağlanan risk sınıflandırmaları, ağırlıklı olarak Avrupa ve Kuzey Amerika araştırma nüfuslarından elde edilen DSÖ kılavuzlarına dayanmaktadır; farklı etnik kökenlerden bireyler için sağlık riskini her zaman doğru yansıtmayabilir. BKO, tek bir noktada alınan tek bir ölçümdür ve kardiyovasküler veya metabolik sağlığın tüm karmaşıklığını yansıtamaz; diğer klinik göstergelerle birlikte yorumlanmalıdır. Bu araç, 18 yaş altı çocuklara, hamile veya emziren kadınlara, yeme bozuklukları geçmişi olan veya olan bireyler ile yağ dağılımını önemli ölçüde etkileyen durumları bulunan bireyler (Cushing sendromu, hipotiroidizm, PKOS dahil veya kortikostreoid, insulin, hormonal tedavi kullananlar) için uygun değildir. Düşük risk sonucu, kardiyovasküler veya diğer sağlık riskleri olmadığını garanti etmez; sigara kullanımı, aile öyküsü, kan basıncı, kolesterol, fiziksel aktivite alışkanlıkları ve beslenme kalitesi hepsi bağımsız olarak toplam hastalık riskine katkıda bulunur. Orta veya yüksek risk sonucu, herhangi bir hastalığın tanısı anlamına gelmemekle birlikte, nitelikli bir sağlık profesyoniyle görüşülmesi gereken anlamlı bir işarettir.',

    references: [
      'World Health Organization. Obesity: preventing and managing the global epidemic. Report of a WHO consultation on obesity. WHO Technical Report Series, 894. Geneva: WHO; 2000.',
      'Alberti KG, Zimmet P, Shaw J. Metabolic syndrome — a new classification from the International Diabetes Federation. Diabet Med. 2006;23(5):579-582.',
      'Ashwell M, Gunn P, Gibson S. Waist-to-height ratio is a better predictor of a healthy weight than BMI for both men and women. Obes Rev. 2012;13(3):275-284.',
      'Mishra AK, Arora NJ, Kaur L. Body adiposity measures as predictors of metabolic syndrome in Indian population. J Commun Med Public Health. 2019;34(2):103-108.',
      'Riddell JM. Using the waist:hip ratio to assess the risk of cardiovascular disease. Med J Aus. 2001;175(2):97-98.',
      'WHO Expert Consultation. Waist circumference and waist-hip ratio: report of an expert consultation. Geneva: World Health Organization; 2008.',
    ],

    tips: [
      'Ölçümleri sabah yemek ve su içmeden önce alın; bu durum en tutarlı sonuçları sağlar.',
      'Esnek ve gerilmez bir mezura kullanın — terzi mezurası ideal bir seçenektir. İp veya sert cetvel kullanmaktan kaçının.',
      'Mümkün olsa başkasının ölçüm yapmasını sağlayın; özellikle kalça çevresi için kendi kendini ölçme hatalarını bu yolla azaltabilirsiniz.',
      'BKO\'yu aylık bazda takip edin, günlük olarak değil. Hidrasyon ve gaz gibi faktörler nedeniyle günlük ölçüm farklılıkları birkaç milimetre olabilir.',
      'BKO takibini düzenli kan testi ile — açlık kan şekeri, lipid paneli ve kan basıncı ile — birleştirin; bu kapsamlı bir kardiyovasküler risk tablosu verir.',
      'Sayıya takıntılı kalmak yerine sürdürülebilir yaşam tarzı alışkanlıklarına odaklanın: düzenli fiziksel aktivite, sebze ve tam tahıllı yiyeceklere dayanan beslenme, yeterli uyku ve stres yönetimi hepsi karın yağı azaltmaya katkıda bulunur.',
      'Karın yağı, yaşam tarzı değişikliklerine en hızlı yanıt veren yağ depolarından biridir. Kalıcı yiyecek düzenleme ve düzenli egzersiz, birkaç ay içinde anlamlı BKO iyileştirmesi sağlayabilir.',
    ],

    faqs: [
      {
        question: 'BKO, VKİ\'ye kıyasla daha iyi bir sağlık göstergesi mi?',
        answer:
          'BKO ve VKİ farklı şeyleri ölçür. VKİ, boy oranında toplam vücut ağırlığını yansıtır ancak yağın nerede olduğu hakkında hiçbir bilgi vermez. BKO ise yağ dağılım kalıpını doğrudan ortaya koyar; bu da kardiyovasküler ve metabolik hastalık riskiyle daha doğrudan bir ilişkiyi yansıtır. Sağlık uzmanlarının büyük çoğunluğu, kapsamlı bir sağlık değerlendirmesi için BKO, VKİ ve bel çevresini birlikte kullanmayı önerir.',
      },
      {
        question: 'Erkekler ve kadınlar için neden farklı BKO eşikleri vardır?',
        answer:
          'Erkeklerin ve kadınların hormonal yapıları temelden farklıdır; bu da yağ depolama kalıplarını belirler. Testosteron, erkeklerde karın çevresinde yağ birikimini teşvik ederken, estrogen kadınlarda kalça ve bacak çevresinde yağ depolanmasını destekler. Bu fizyolojik farklılıklar, aynı BKO değerinin biyolojik cinsiyet bazında farklı sağlık sonuçlarına yol açabileceği anlamına gelir; bu nedenle DSÖ, her cinsiyet için ayrı eşikler belirler.',
      },
      {
        question: 'BKO\'yumu yaşam tarzı değişiklikleriyle düşürülebilir mi?',
        answer:
          'Evet. BKO, özellikle karın yağının azaltılmasıyla hayat tarzı düzenlemelerine yanıt verir. Düzenli fiziksel aktivite — özellikle kardiyopulmoner egzersiz ve direnç antrenmanının kombinasyonu — ile dengeli bir diyetin birleştirülmesi, haftalarca ve aylarca karın yağını azaltabilir. Yeterli uyku (7–9 saat) ve stres yönetimi de önemlidir; kronik stres ve uyku yoksunluğu her ikisi de karın yağı birikimini artırır. Sonuçlar genellikle ani değil, zamanla ortaya çıkar.',
      },
      {
        question: 'BKO yaşlandıkça değişir mi?',
        answer:
          'Evet, BKO her iki cinsiyette de doğal olarak yaş ilerledikçe artmaya meyletir. Bu, yaşa bağlı karın yağı artışı ve kalça kaslarında azalmayla tetiklenir. Kadınlar için menopoz, estrogen düzeylerinin düşmesiyle yağ dağılımının kalçadan karına kaymasına neden olduğundan özellikle önemli bir dönüm noktasıdır. Bu da yaşlandıkça sağlıklı yaşam alışkanlıklarının — özellikle fiziksel aktivitenin — giderek daha fazla önem taşıdığı anlamına gelir.',
      },
      {
        question: 'BKO sonucu yüksek risk gösterdiğinde ne yapmalıyım?',
        answer:
          'Yüksek risk BKO sonucu bir tanı değil, üzerinde durulması gereken anlamlı bir işarettir. Sonucu konuşmak ve kapsamlı bir kardiyometabolik risk değerlendirmesi talep etmek için sağlık hizmet sağlayıcınızla bir randevu oluşturun; bu genellikle kan basıncı ölçümü, açlık lipid paneli ve açlık kan şekeri incelemeleri içerir. Sağlayıcınız daha sonra tam sağlık profilinize dayanarak kişisel bir plan oluşturmanıza yardımcı olabilir.',
      },
      {
        question: 'DSÖ BKO eşikleri etnik kökenime göre doğru mu?',
        answer:
          'Standart DSÖ BKO eşikleri ağırlıklı olarak Avrupalı ve Kuzey Amerikalı nüfuslardan elde edilmiştir ve her etnik grup için optimal olarak kalibre edilmemiş olabilir. Araştırmalar, Güney Asya ve Doğu Asya kökenli bireyler için, standart kesme değerlerin "düşük risk" olarak sınıflandırdığı BKO değerlerinde bile yükselen kardiyovasküler risk ile karşılaşılabileceğini ortaya koymuştur. Bu kökenle gelen biriylerin sonuçlarını bu etnik farklılıkları göz önünde bulunduran bir sağlık profesyoniyle paylaşması önerilir.',
      },
    ],
  },
};
