import { FoodItem, FoodCategory, CategoryInfo, SelectedFood, NutritionSummary } from './foodCalorieTypes';

// Comprehensive food database with 150+ items
export const foodDatabase: FoodItem[] = [
  // FRUITS (20 items)
  {
    id: 'apple',
    name: { en: 'Apple', tr: 'Elma' },
    category: 'fruits',
    caloriesPer100g: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    servingExamples: { en: '1 medium apple (182g)', tr: '1 orta boy elma (182g)' },
  },
  {
    id: 'banana',
    name: { en: 'Banana', tr: 'Muz' },
    category: 'fruits',
    caloriesPer100g: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    servingExamples: { en: '1 medium banana (118g)', tr: '1 orta boy muz (118g)' },
  },
  {
    id: 'orange',
    name: { en: 'Orange', tr: 'Portakal' },
    category: 'fruits',
    caloriesPer100g: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    servingExamples: { en: '1 medium orange (131g)', tr: '1 orta boy portakal (131g)' },
  },
  {
    id: 'strawberry',
    name: { en: 'Strawberry', tr: 'Çilek' },
    category: 'fruits',
    caloriesPer100g: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    servingExamples: { en: '1 cup (152g)', tr: '1 su bardağı (152g)' },
  },
  {
    id: 'watermelon',
    name: { en: 'Watermelon', tr: 'Karpuz' },
    category: 'fruits',
    caloriesPer100g: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    servingExamples: { en: '1 slice (286g)', tr: '1 dilim (286g)' },
  },
  {
    id: 'grape',
    name: { en: 'Grapes', tr: 'Üzüm' },
    category: 'fruits',
    caloriesPer100g: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    fiber: 0.9,
    servingExamples: { en: '1 cup (151g)', tr: '1 su bardağı (151g)' },
  },
  {
    id: 'peach',
    name: { en: 'Peach', tr: 'Şeftali' },
    category: 'fruits',
    caloriesPer100g: 39,
    protein: 0.9,
    carbs: 10,
    fat: 0.3,
    fiber: 1.5,
    servingExamples: { en: '1 medium peach (150g)', tr: '1 orta boy şeftali (150g)' },
  },
  {
    id: 'pear',
    name: { en: 'Pear', tr: 'Armut' },
    category: 'fruits',
    caloriesPer100g: 57,
    protein: 0.4,
    carbs: 15,
    fat: 0.1,
    fiber: 3.1,
    servingExamples: { en: '1 medium pear (178g)', tr: '1 orta boy armut (178g)' },
  },
  {
    id: 'kiwi',
    name: { en: 'Kiwi', tr: 'Kivi' },
    category: 'fruits',
    caloriesPer100g: 61,
    protein: 1.1,
    carbs: 15,
    fat: 0.5,
    fiber: 3,
    servingExamples: { en: '1 medium kiwi (69g)', tr: '1 orta boy kivi (69g)' },
  },
  {
    id: 'mango',
    name: { en: 'Mango', tr: 'Mango' },
    category: 'fruits',
    caloriesPer100g: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    servingExamples: { en: '1 cup sliced (165g)', tr: '1 su bardağı dilimlenmiş (165g)' },
  },
  {
    id: 'pineapple',
    name: { en: 'Pineapple', tr: 'Ananas' },
    category: 'fruits',
    caloriesPer100g: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    servingExamples: { en: '1 cup chunks (165g)', tr: '1 su bardağı küp (165g)' },
  },
  {
    id: 'cherry',
    name: { en: 'Cherry', tr: 'Kiraz' },
    category: 'fruits',
    caloriesPer100g: 63,
    protein: 1.1,
    carbs: 16,
    fat: 0.2,
    fiber: 2.1,
    servingExamples: { en: '1 cup (154g)', tr: '1 su bardağı (154g)' },
  },
  {
    id: 'plum',
    name: { en: 'Plum', tr: 'Erik' },
    category: 'fruits',
    caloriesPer100g: 46,
    protein: 0.7,
    carbs: 11,
    fat: 0.3,
    fiber: 1.4,
    servingExamples: { en: '1 medium plum (66g)', tr: '1 orta boy erik (66g)' },
  },
  {
    id: 'apricot',
    name: { en: 'Apricot', tr: 'Kayısı' },
    category: 'fruits',
    caloriesPer100g: 48,
    protein: 1.4,
    carbs: 11,
    fat: 0.4,
    fiber: 2,
    servingExamples: { en: '3 medium apricots (105g)', tr: '3 orta boy kayısı (105g)' },
  },
  {
    id: 'pomegranate',
    name: { en: 'Pomegranate', tr: 'Nar' },
    category: 'fruits',
    caloriesPer100g: 83,
    protein: 1.7,
    carbs: 19,
    fat: 1.2,
    fiber: 4,
    servingExamples: { en: '1/2 pomegranate (87g)', tr: '1/2 nar (87g)' },
  },
  {
    id: 'blueberry',
    name: { en: 'Blueberry', tr: 'Yaban Mersini' },
    category: 'fruits',
    caloriesPer100g: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    servingExamples: { en: '1 cup (148g)', tr: '1 su bardağı (148g)' },
  },
  {
    id: 'raspberry',
    name: { en: 'Raspberry', tr: 'Ahududu' },
    category: 'fruits',
    caloriesPer100g: 52,
    protein: 1.2,
    carbs: 12,
    fat: 0.7,
    fiber: 6.5,
    servingExamples: { en: '1 cup (123g)', tr: '1 su bardağı (123g)' },
  },
  {
    id: 'lemon',
    name: { en: 'Lemon', tr: 'Limon' },
    category: 'fruits',
    caloriesPer100g: 29,
    protein: 1.1,
    carbs: 9,
    fat: 0.3,
    fiber: 2.8,
    servingExamples: { en: '1 lemon (58g)', tr: '1 limon (58g)' },
  },
  {
    id: 'grapefruit',
    name: { en: 'Grapefruit', tr: 'Greyfurt' },
    category: 'fruits',
    caloriesPer100g: 42,
    protein: 0.8,
    carbs: 11,
    fat: 0.1,
    fiber: 1.6,
    servingExamples: { en: '1/2 grapefruit (123g)', tr: '1/2 greyfurt (123g)' },
  },
  {
    id: 'melon',
    name: { en: 'Cantaloupe Melon', tr: 'Kavun' },
    category: 'fruits',
    caloriesPer100g: 34,
    protein: 0.8,
    carbs: 8,
    fat: 0.2,
    fiber: 0.9,
    servingExamples: { en: '1 cup cubed (160g)', tr: '1 su bardağı küp (160g)' },
  },

  // VEGETABLES (25 items)
  {
    id: 'tomato',
    name: { en: 'Tomato', tr: 'Domates' },
    category: 'vegetables',
    caloriesPer100g: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    servingExamples: { en: '1 medium tomato (123g)', tr: '1 orta boy domates (123g)' },
  },
  {
    id: 'cucumber',
    name: { en: 'Cucumber', tr: 'Salatalık' },
    category: 'vegetables',
    caloriesPer100g: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    servingExamples: { en: '1/2 cucumber (150g)', tr: '1/2 salatalık (150g)' },
  },
  {
    id: 'lettuce',
    name: { en: 'Lettuce', tr: 'Marul' },
    category: 'vegetables',
    caloriesPer100g: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    servingExamples: { en: '2 cups shredded (94g)', tr: '2 su bardağı kıyılmış (94g)' },
  },
  {
    id: 'carrot',
    name: { en: 'Carrot', tr: 'Havuç' },
    category: 'vegetables',
    caloriesPer100g: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    servingExamples: { en: '1 medium carrot (61g)', tr: '1 orta boy havuç (61g)' },
  },
  {
    id: 'broccoli',
    name: { en: 'Broccoli', tr: 'Brokoli' },
    category: 'vegetables',
    caloriesPer100g: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    servingExamples: { en: '1 cup chopped (91g)', tr: '1 su bardağı doğranmış (91g)' },
  },
  {
    id: 'spinach',
    name: { en: 'Spinach', tr: 'Ispanak' },
    category: 'vegetables',
    caloriesPer100g: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingExamples: { en: '1 cup raw (30g)', tr: '1 su bardağı çiğ (30g)' },
  },
  {
    id: 'bell-pepper',
    name: { en: 'Bell Pepper', tr: 'Dolmalık Biber' },
    category: 'vegetables',
    caloriesPer100g: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    servingExamples: { en: '1 medium pepper (119g)', tr: '1 orta boy biber (119g)' },
  },
  {
    id: 'onion',
    name: { en: 'Onion', tr: 'Soğan' },
    category: 'vegetables',
    caloriesPer100g: 40,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
    servingExamples: { en: '1 medium onion (110g)', tr: '1 orta boy soğan (110g)' },
  },
  {
    id: 'eggplant',
    name: { en: 'Eggplant', tr: 'Patlıcan' },
    category: 'vegetables',
    caloriesPer100g: 25,
    protein: 1,
    carbs: 6,
    fat: 0.2,
    fiber: 3,
    servingExamples: { en: '1 cup cubed (82g)', tr: '1 su bardağı küp (82g)' },
  },
  {
    id: 'zucchini',
    name: { en: 'Zucchini', tr: 'Kabak' },
    category: 'vegetables',
    caloriesPer100g: 17,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1,
    servingExamples: { en: '1 medium zucchini (196g)', tr: '1 orta boy kabak (196g)' },
  },
  {
    id: 'cauliflower',
    name: { en: 'Cauliflower', tr: 'Karnabahar' },
    category: 'vegetables',
    caloriesPer100g: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2,
    servingExamples: { en: '1 cup chopped (107g)', tr: '1 su bardağı doğranmış (107g)' },
  },
  {
    id: 'cabbage',
    name: { en: 'Cabbage', tr: 'Lahana' },
    category: 'vegetables',
    caloriesPer100g: 25,
    protein: 1.3,
    carbs: 6,
    fat: 0.1,
    fiber: 2.5,
    servingExamples: { en: '1 cup shredded (89g)', tr: '1 su bardağı kıyılmış (89g)' },
  },
  {
    id: 'mushroom',
    name: { en: 'Mushroom', tr: 'Mantar' },
    category: 'vegetables',
    caloriesPer100g: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    servingExamples: { en: '1 cup sliced (70g)', tr: '1 su bardağı dilimlenmiş (70g)' },
  },
  {
    id: 'green-beans',
    name: { en: 'Green Beans', tr: 'Yeşil Fasulye' },
    category: 'vegetables',
    caloriesPer100g: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.2,
    fiber: 2.7,
    servingExamples: { en: '1 cup (100g)', tr: '1 su bardağı (100g)' },
  },
  {
    id: 'peas',
    name: { en: 'Green Peas', tr: 'Bezelye' },
    category: 'vegetables',
    caloriesPer100g: 81,
    protein: 5.4,
    carbs: 14,
    fat: 0.4,
    fiber: 5.7,
    servingExamples: { en: '1 cup (160g)', tr: '1 su bardağı (160g)' },
  },
  {
    id: 'corn',
    name: { en: 'Sweet Corn', tr: 'Mısır' },
    category: 'vegetables',
    caloriesPer100g: 86,
    protein: 3.3,
    carbs: 19,
    fat: 1.4,
    fiber: 2,
    servingExamples: { en: '1 medium ear (103g)', tr: '1 orta boy koçan (103g)' },
  },
  {
    id: 'potato',
    name: { en: 'Potato', tr: 'Patates' },
    category: 'vegetables',
    caloriesPer100g: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.1,
    servingExamples: { en: '1 medium potato (173g)', tr: '1 orta boy patates (173g)' },
  },
  {
    id: 'sweet-potato',
    name: { en: 'Sweet Potato', tr: 'Tatlı Patates' },
    category: 'vegetables',
    caloriesPer100g: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    servingExamples: { en: '1 medium (114g)', tr: '1 orta boy (114g)' },
  },
  {
    id: 'beetroot',
    name: { en: 'Beetroot', tr: 'Pancar' },
    category: 'vegetables',
    caloriesPer100g: 43,
    protein: 1.6,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    servingExamples: { en: '1 cup (136g)', tr: '1 su bardağı (136g)' },
  },
  {
    id: 'radish',
    name: { en: 'Radish', tr: 'Turp' },
    category: 'vegetables',
    caloriesPer100g: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
    fiber: 1.6,
    servingExamples: { en: '1 cup sliced (116g)', tr: '1 su bardağı dilimlenmiş (116g)' },
  },
  {
    id: 'celery',
    name: { en: 'Celery', tr: 'Kereviz' },
    category: 'vegetables',
    caloriesPer100g: 14,
    protein: 0.7,
    carbs: 3,
    fat: 0.2,
    fiber: 1.6,
    servingExamples: { en: '2 medium stalks (80g)', tr: '2 orta boy sap (80g)' },
  },
  {
    id: 'asparagus',
    name: { en: 'Asparagus', tr: 'Kuşkonmaz' },
    category: 'vegetables',
    caloriesPer100g: 20,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    servingExamples: { en: '6 spears (90g)', tr: '6 dal (90g)' },
  },
  {
    id: 'artichoke',
    name: { en: 'Artichoke', tr: 'Enginar' },
    category: 'vegetables',
    caloriesPer100g: 47,
    protein: 3.3,
    carbs: 11,
    fat: 0.2,
    fiber: 5.4,
    servingExamples: { en: '1 medium artichoke (128g)', tr: '1 orta boy enginar (128g)' },
  },
  {
    id: 'leek',
    name: { en: 'Leek', tr: 'Pırasa' },
    category: 'vegetables',
    caloriesPer100g: 61,
    protein: 1.5,
    carbs: 14,
    fat: 0.3,
    fiber: 1.8,
    servingExamples: { en: '1 medium leek (89g)', tr: '1 orta boy pırasa (89g)' },
  },
  {
    id: 'garlic',
    name: { en: 'Garlic', tr: 'Sarımsak' },
    category: 'vegetables',
    caloriesPer100g: 149,
    protein: 6.4,
    carbs: 33,
    fat: 0.5,
    fiber: 2.1,
    servingExamples: { en: '3 cloves (9g)', tr: '3 diş (9g)' },
  },

  // MEAT & POULTRY (15 items)
  {
    id: 'chicken-breast',
    name: { en: 'Chicken Breast (skinless)', tr: 'Tavuk Göğsü (derisiz)' },
    category: 'meat-poultry',
    caloriesPer100g: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    servingExamples: { en: '1 breast (174g)', tr: '1 göğüs (174g)' },
  },
  {
    id: 'chicken-thigh',
    name: { en: 'Chicken Thigh (skinless)', tr: 'Tavuk But (derisiz)' },
    category: 'meat-poultry',
    caloriesPer100g: 209,
    protein: 26,
    carbs: 0,
    fat: 11,
    fiber: 0,
    servingExamples: { en: '1 thigh (52g)', tr: '1 but (52g)' },
  },
  {
    id: 'turkey-breast',
    name: { en: 'Turkey Breast', tr: 'Hindi Göğsü' },
    category: 'meat-poultry',
    caloriesPer100g: 135,
    protein: 30,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'beef-sirloin',
    name: { en: 'Beef Sirloin (lean)', tr: 'Dana Bonfile (yağsız)' },
    category: 'meat-poultry',
    caloriesPer100g: 201,
    protein: 28,
    carbs: 0,
    fat: 9,
    fiber: 0,
    servingExamples: { en: '3 oz steak (85g)', tr: '3 oz biftek (85g)' },
  },
  {
    id: 'beef-ribeye',
    name: { en: 'Beef Ribeye', tr: 'Dana Antrikot' },
    category: 'meat-poultry',
    caloriesPer100g: 291,
    protein: 25,
    carbs: 0,
    fat: 21,
    fiber: 0,
    servingExamples: { en: '3 oz steak (85g)', tr: '3 oz biftek (85g)' },
  },
  {
    id: 'ground-beef',
    name: { en: 'Ground Beef (85% lean)', tr: 'Kıyma (%85 yağsız)' },
    category: 'meat-poultry',
    caloriesPer100g: 215,
    protein: 26,
    carbs: 0,
    fat: 12,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'lamb-chop',
    name: { en: 'Lamb Chop', tr: 'Kuzu Pirzola' },
    category: 'meat-poultry',
    caloriesPer100g: 282,
    protein: 25,
    carbs: 0,
    fat: 20,
    fiber: 0,
    servingExamples: { en: '1 chop (100g)', tr: '1 pirzola (100g)' },
  },
  {
    id: 'pork-chop',
    name: { en: 'Pork Chop (lean)', tr: 'Domuz Pirzola (yağsız)' },
    category: 'meat-poultry',
    caloriesPer100g: 206,
    protein: 28,
    carbs: 0,
    fat: 10,
    fiber: 0,
    servingExamples: { en: '1 chop (87g)', tr: '1 pirzola (87g)' },
  },
  {
    id: 'bacon',
    name: { en: 'Bacon', tr: 'Pastırma/Bacon' },
    category: 'meat-poultry',
    caloriesPer100g: 541,
    protein: 37,
    carbs: 1.4,
    fat: 42,
    fiber: 0,
    servingExamples: { en: '3 slices (24g)', tr: '3 dilim (24g)' },
  },
  {
    id: 'sausage',
    name: { en: 'Pork Sausage', tr: 'Sosis' },
    category: 'meat-poultry',
    caloriesPer100g: 301,
    protein: 13,
    carbs: 1.7,
    fat: 28,
    fiber: 0,
    servingExamples: { en: '1 link (68g)', tr: '1 adet (68g)' },
  },
  {
    id: 'duck',
    name: { en: 'Duck Meat', tr: 'Ördek Eti' },
    category: 'meat-poultry',
    caloriesPer100g: 337,
    protein: 19,
    carbs: 0,
    fat: 28,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'veal',
    name: { en: 'Veal', tr: 'Dana Eti' },
    category: 'meat-poultry',
    caloriesPer100g: 172,
    protein: 31,
    carbs: 0,
    fat: 5,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'liver-beef',
    name: { en: 'Beef Liver', tr: 'Dana Karaciğeri' },
    category: 'meat-poultry',
    caloriesPer100g: 175,
    protein: 27,
    carbs: 5,
    fat: 5,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'salami',
    name: { en: 'Salami', tr: 'Salam' },
    category: 'meat-poultry',
    caloriesPer100g: 407,
    protein: 22,
    carbs: 1.6,
    fat: 34,
    fiber: 0,
    servingExamples: { en: '5 slices (50g)', tr: '5 dilim (50g)' },
  },
  {
    id: 'ham',
    name: { en: 'Ham (lean)', tr: 'Jambon (yağsız)' },
    category: 'meat-poultry',
    caloriesPer100g: 145,
    protein: 21,
    carbs: 1.5,
    fat: 6,
    fiber: 0,
    servingExamples: { en: '3 slices (84g)', tr: '3 dilim (84g)' },
  },

  // FISH & SEAFOOD (15 items)
  {
    id: 'salmon',
    name: { en: 'Salmon (Atlantic)', tr: 'Somon' },
    category: 'fish-seafood',
    caloriesPer100g: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    servingExamples: { en: '3 oz fillet (85g)', tr: '3 oz fileto (85g)' },
  },
  {
    id: 'tuna',
    name: { en: 'Tuna (fresh)', tr: 'Ton Balığı (taze)' },
    category: 'fish-seafood',
    caloriesPer100g: 144,
    protein: 23,
    carbs: 0,
    fat: 5,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'tuna-canned',
    name: { en: 'Tuna (canned in water)', tr: 'Ton Balığı (konserve)' },
    category: 'fish-seafood',
    caloriesPer100g: 116,
    protein: 26,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    servingExamples: { en: '1 can (142g)', tr: '1 kutu (142g)' },
  },
  {
    id: 'sea-bass',
    name: { en: 'Sea Bass', tr: 'Levrek' },
    category: 'fish-seafood',
    caloriesPer100g: 124,
    protein: 24,
    carbs: 0,
    fat: 3,
    fiber: 0,
    servingExamples: { en: '3 oz fillet (85g)', tr: '3 oz fileto (85g)' },
  },
  {
    id: 'cod',
    name: { en: 'Cod', tr: 'Morina Balığı' },
    category: 'fish-seafood',
    caloriesPer100g: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    servingExamples: { en: '3 oz fillet (85g)', tr: '3 oz fileto (85g)' },
  },
  {
    id: 'mackerel',
    name: { en: 'Mackerel', tr: 'Uskumru' },
    category: 'fish-seafood',
    caloriesPer100g: 205,
    protein: 19,
    carbs: 0,
    fat: 14,
    fiber: 0,
    servingExamples: { en: '1 fillet (88g)', tr: '1 fileto (88g)' },
  },
  {
    id: 'sardine',
    name: { en: 'Sardine', tr: 'Sardalya' },
    category: 'fish-seafood',
    caloriesPer100g: 208,
    protein: 25,
    carbs: 0,
    fat: 11,
    fiber: 0,
    servingExamples: { en: '1 can (92g)', tr: '1 kutu (92g)' },
  },
  {
    id: 'anchovy',
    name: { en: 'Anchovy', tr: 'Hamsi' },
    category: 'fish-seafood',
    caloriesPer100g: 131,
    protein: 20,
    carbs: 0,
    fat: 5,
    fiber: 0,
    servingExamples: { en: '1 can (45g)', tr: '1 kutu (45g)' },
  },
  {
    id: 'shrimp',
    name: { en: 'Shrimp', tr: 'Karides' },
    category: 'fish-seafood',
    caloriesPer100g: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'crab',
    name: { en: 'Crab', tr: 'Yengeç' },
    category: 'fish-seafood',
    caloriesPer100g: 97,
    protein: 19,
    carbs: 0,
    fat: 1.5,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'lobster',
    name: { en: 'Lobster', tr: 'Istakoz' },
    category: 'fish-seafood',
    caloriesPer100g: 89,
    protein: 19,
    carbs: 0,
    fat: 0.9,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'squid',
    name: { en: 'Squid', tr: 'Kalamar' },
    category: 'fish-seafood',
    caloriesPer100g: 92,
    protein: 15,
    carbs: 3.1,
    fat: 1.4,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'octopus',
    name: { en: 'Octopus', tr: 'Ahtapot' },
    category: 'fish-seafood',
    caloriesPer100g: 82,
    protein: 15,
    carbs: 2.2,
    fat: 1,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'mussels',
    name: { en: 'Mussels', tr: 'Midye' },
    category: 'fish-seafood',
    caloriesPer100g: 86,
    protein: 12,
    carbs: 3.7,
    fat: 2.2,
    fiber: 0,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'oysters',
    name: { en: 'Oysters', tr: 'İstiridye' },
    category: 'fish-seafood',
    caloriesPer100g: 68,
    protein: 7,
    carbs: 3.9,
    fat: 2.5,
    fiber: 0,
    servingExamples: { en: '6 medium oysters (84g)', tr: '6 orta boy istiridye (84g)' },
  },

  // DAIRY (15 items)
  {
    id: 'milk-whole',
    name: { en: 'Whole Milk', tr: 'Tam Yağlı Süt' },
    category: 'dairy',
    caloriesPer100g: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    servingExamples: { en: '1 cup (244g)', tr: '1 su bardağı (244g)' },
  },
  {
    id: 'milk-skim',
    name: { en: 'Skim Milk (0% fat)', tr: 'Yağsız Süt' },
    category: 'dairy',
    caloriesPer100g: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    servingExamples: { en: '1 cup (244g)', tr: '1 su bardağı (244g)' },
  },
  {
    id: 'yogurt-plain',
    name: { en: 'Plain Yogurt (full fat)', tr: 'Yoğurt (tam yağlı)' },
    category: 'dairy',
    caloriesPer100g: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    servingExamples: { en: '1 cup (245g)', tr: '1 su bardağı (245g)' },
  },
  {
    id: 'yogurt-greek',
    name: { en: 'Greek Yogurt (non-fat)', tr: 'Süzme Yoğurt (yağsız)' },
    category: 'dairy',
    caloriesPer100g: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    servingExamples: { en: '1 container (170g)', tr: '1 kase (170g)' },
  },
  {
    id: 'cheese-cheddar',
    name: { en: 'Cheddar Cheese', tr: 'Çedar Peyniri' },
    category: 'dairy',
    caloriesPer100g: 403,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    servingExamples: { en: '1 slice (28g)', tr: '1 dilim (28g)' },
  },
  {
    id: 'cheese-mozzarella',
    name: { en: 'Mozzarella Cheese', tr: 'Mozzarella Peyniri' },
    category: 'dairy',
    caloriesPer100g: 280,
    protein: 28,
    carbs: 3.1,
    fat: 17,
    fiber: 0,
    servingExamples: { en: '1 oz (28g)', tr: '1 oz (28g)' },
  },
  {
    id: 'cheese-feta',
    name: { en: 'Feta Cheese', tr: 'Beyaz Peynir' },
    category: 'dairy',
    caloriesPer100g: 264,
    protein: 14,
    carbs: 4.1,
    fat: 21,
    fiber: 0,
    servingExamples: { en: '1 oz (28g)', tr: '1 oz (28g)' },
  },
  {
    id: 'cheese-parmesan',
    name: { en: 'Parmesan Cheese', tr: 'Parmesan Peyniri' },
    category: 'dairy',
    caloriesPer100g: 431,
    protein: 38,
    carbs: 4.1,
    fat: 29,
    fiber: 0,
    servingExamples: { en: '1 tbsp grated (5g)', tr: '1 yemek kaşığı rendelenmiş (5g)' },
  },
  {
    id: 'cottage-cheese',
    name: { en: 'Cottage Cheese (low-fat)', tr: 'Süzme Peynir (az yağlı)' },
    category: 'dairy',
    caloriesPer100g: 72,
    protein: 12,
    carbs: 3.4,
    fat: 1,
    fiber: 0,
    servingExamples: { en: '1 cup (226g)', tr: '1 su bardağı (226g)' },
  },
  {
    id: 'cream-cheese',
    name: { en: 'Cream Cheese', tr: 'Krem Peynir' },
    category: 'dairy',
    caloriesPer100g: 342,
    protein: 6,
    carbs: 5.5,
    fat: 34,
    fiber: 0,
    servingExamples: { en: '1 tbsp (14g)', tr: '1 yemek kaşığı (14g)' },
  },
  {
    id: 'butter',
    name: { en: 'Butter', tr: 'Tereyağı' },
    category: 'dairy',
    caloriesPer100g: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    fiber: 0,
    servingExamples: { en: '1 tbsp (14g)', tr: '1 yemek kaşığı (14g)' },
  },
  {
    id: 'sour-cream',
    name: { en: 'Sour Cream', tr: 'Ekşi Krema' },
    category: 'dairy',
    caloriesPer100g: 193,
    protein: 2.4,
    carbs: 4.6,
    fat: 19,
    fiber: 0,
    servingExamples: { en: '2 tbsp (30g)', tr: '2 yemek kaşığı (30g)' },
  },
  {
    id: 'ice-cream',
    name: { en: 'Ice Cream (vanilla)', tr: 'Dondurma (vanilyalı)' },
    category: 'dairy',
    caloriesPer100g: 207,
    protein: 3.5,
    carbs: 24,
    fat: 11,
    fiber: 0.7,
    servingExamples: { en: '1/2 cup (66g)', tr: '1/2 su bardağı (66g)' },
  },
  {
    id: 'whipped-cream',
    name: { en: 'Whipped Cream', tr: 'Krem Şanti' },
    category: 'dairy',
    caloriesPer100g: 257,
    protein: 2.2,
    carbs: 12,
    fat: 22,
    fiber: 0,
    servingExamples: { en: '2 tbsp (15g)', tr: '2 yemek kaşığı (15g)' },
  },
  {
    id: 'ayran',
    name: { en: 'Ayran (Turkish yogurt drink)', tr: 'Ayran' },
    category: 'dairy',
    caloriesPer100g: 38,
    protein: 1.7,
    carbs: 2.5,
    fat: 2.1,
    fiber: 0,
    servingExamples: { en: '1 glass (200ml)', tr: '1 bardak (200ml)' },
  },

  // GRAINS & LEGUMES (20 items)
  {
    id: 'white-rice-cooked',
    name: { en: 'White Rice (cooked)', tr: 'Beyaz Pirinç (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    servingExamples: { en: '1 cup (158g)', tr: '1 su bardağı (158g)' },
  },
  {
    id: 'brown-rice-cooked',
    name: { en: 'Brown Rice (cooked)', tr: 'Esmer Pirinç (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 112,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    fiber: 1.8,
    servingExamples: { en: '1 cup (195g)', tr: '1 su bardağı (195g)' },
  },
  {
    id: 'pasta-cooked',
    name: { en: 'Pasta (cooked)', tr: 'Makarna (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    servingExamples: { en: '1 cup (140g)', tr: '1 su bardağı (140g)' },
  },
  {
    id: 'quinoa-cooked',
    name: { en: 'Quinoa (cooked)', tr: 'Kinoa (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    fiber: 2.8,
    servingExamples: { en: '1 cup (185g)', tr: '1 su bardağı (185g)' },
  },
  {
    id: 'oats-cooked',
    name: { en: 'Oatmeal (cooked)', tr: 'Yulaf Ezmesi (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 71,
    protein: 2.5,
    carbs: 12,
    fat: 1.5,
    fiber: 1.7,
    servingExamples: { en: '1 cup (234g)', tr: '1 su bardağı (234g)' },
  },
  {
    id: 'bulgur-cooked',
    name: { en: 'Bulgur (cooked)', tr: 'Bulgur (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 83,
    protein: 3.1,
    carbs: 19,
    fat: 0.2,
    fiber: 4.5,
    servingExamples: { en: '1 cup (182g)', tr: '1 su bardağı (182g)' },
  },
  {
    id: 'couscous-cooked',
    name: { en: 'Couscous (cooked)', tr: 'Kuskus (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 112,
    protein: 3.8,
    carbs: 23,
    fat: 0.2,
    fiber: 1.4,
    servingExamples: { en: '1 cup (157g)', tr: '1 su bardağı (157g)' },
  },
  {
    id: 'lentils-cooked',
    name: { en: 'Lentils (cooked)', tr: 'Mercimek (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    servingExamples: { en: '1 cup (198g)', tr: '1 su bardağı (198g)' },
  },
  {
    id: 'chickpeas-cooked',
    name: { en: 'Chickpeas (cooked)', tr: 'Nohut (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    fiber: 7.6,
    servingExamples: { en: '1 cup (164g)', tr: '1 su bardağı (164g)' },
  },
  {
    id: 'black-beans-cooked',
    name: { en: 'Black Beans (cooked)', tr: 'Siyah Fasulye (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 132,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
    fiber: 8.7,
    servingExamples: { en: '1 cup (172g)', tr: '1 su bardağı (172g)' },
  },
  {
    id: 'kidney-beans-cooked',
    name: { en: 'Kidney Beans (cooked)', tr: 'Kuru Fasulye (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 127,
    protein: 8.7,
    carbs: 23,
    fat: 0.5,
    fiber: 6.4,
    servingExamples: { en: '1 cup (177g)', tr: '1 su bardağı (177g)' },
  },
  {
    id: 'barley-cooked',
    name: { en: 'Barley (cooked)', tr: 'Arpa (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 123,
    protein: 2.3,
    carbs: 28,
    fat: 0.4,
    fiber: 3.8,
    servingExamples: { en: '1 cup (157g)', tr: '1 su bardağı (157g)' },
  },
  {
    id: 'cornmeal',
    name: { en: 'Cornmeal (cooked)', tr: 'Mısır Unu (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 79,
    protein: 1.9,
    carbs: 17,
    fat: 0.5,
    fiber: 1.5,
    servingExamples: { en: '1 cup (240g)', tr: '1 su bardağı (240g)' },
  },
  {
    id: 'soybeans-cooked',
    name: { en: 'Soybeans (cooked)', tr: 'Soya Fasulyesi (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 173,
    protein: 16.6,
    carbs: 9.9,
    fat: 9,
    fiber: 6,
    servingExamples: { en: '1 cup (172g)', tr: '1 su bardağı (172g)' },
  },
  {
    id: 'tofu',
    name: { en: 'Tofu (firm)', tr: 'Tofu (sert)' },
    category: 'grains-legumes',
    caloriesPer100g: 144,
    protein: 17,
    carbs: 3,
    fat: 9,
    fiber: 2.3,
    servingExamples: { en: '1/2 cup (126g)', tr: '1/2 su bardağı (126g)' },
  },
  {
    id: 'tempeh',
    name: { en: 'Tempeh', tr: 'Tempeh' },
    category: 'grains-legumes',
    caloriesPer100g: 193,
    protein: 20,
    carbs: 7.6,
    fat: 11,
    fiber: 9,
    servingExamples: { en: '3 oz (85g)', tr: '3 oz (85g)' },
  },
  {
    id: 'pinto-beans',
    name: { en: 'Pinto Beans (cooked)', tr: 'Barbunya (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 143,
    protein: 9,
    carbs: 26,
    fat: 0.7,
    fiber: 9,
    servingExamples: { en: '1 cup (171g)', tr: '1 su bardağı (171g)' },
  },
  {
    id: 'edamame',
    name: { en: 'Edamame (cooked)', tr: 'Edamame (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 122,
    protein: 11,
    carbs: 10,
    fat: 5,
    fiber: 5,
    servingExamples: { en: '1 cup (155g)', tr: '1 su bardağı (155g)' },
  },
  {
    id: 'millet-cooked',
    name: { en: 'Millet (cooked)', tr: 'Darı (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 119,
    protein: 3.5,
    carbs: 24,
    fat: 1,
    fiber: 1.3,
    servingExamples: { en: '1 cup (174g)', tr: '1 su bardağı (174g)' },
  },
  {
    id: 'farro-cooked',
    name: { en: 'Farro (cooked)', tr: 'Farro (pişmiş)' },
    category: 'grains-legumes',
    caloriesPer100g: 114,
    protein: 4.2,
    carbs: 22,
    fat: 0.8,
    fiber: 3.5,
    servingExamples: { en: '1 cup (194g)', tr: '1 su bardağı (194g)' },
  },

  // BREAD & BAKERY (15 items)
  {
    id: 'white-bread',
    name: { en: 'White Bread', tr: 'Beyaz Ekmek' },
    category: 'bread-bakery',
    caloriesPer100g: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
    servingExamples: { en: '1 slice (25g)', tr: '1 dilim (25g)' },
  },
  {
    id: 'whole-wheat-bread',
    name: { en: 'Whole Wheat Bread', tr: 'Tam Buğday Ekmeği' },
    category: 'bread-bakery',
    caloriesPer100g: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 6.8,
    servingExamples: { en: '1 slice (28g)', tr: '1 dilim (28g)' },
  },
  {
    id: 'pita-bread',
    name: { en: 'Pita Bread', tr: 'Pide Ekmeği' },
    category: 'bread-bakery',
    caloriesPer100g: 275,
    protein: 9.1,
    carbs: 55,
    fat: 1.2,
    fiber: 2.2,
    servingExamples: { en: '1 pita (60g)', tr: '1 pide (60g)' },
  },
  {
    id: 'bagel',
    name: { en: 'Bagel', tr: 'Simit' },
    category: 'bread-bakery',
    caloriesPer100g: 257,
    protein: 10,
    carbs: 50,
    fat: 1.7,
    fiber: 2.3,
    servingExamples: { en: '1 bagel (89g)', tr: '1 simit (89g)' },
  },
  {
    id: 'croissant',
    name: { en: 'Croissant', tr: 'Kruvasan' },
    category: 'bread-bakery',
    caloriesPer100g: 406,
    protein: 8.2,
    carbs: 46,
    fat: 21,
    fiber: 2.6,
    servingExamples: { en: '1 medium (57g)', tr: '1 orta boy (57g)' },
  },
  {
    id: 'muffin-blueberry',
    name: { en: 'Blueberry Muffin', tr: 'Yaban Mersinli Kek' },
    category: 'bread-bakery',
    caloriesPer100g: 353,
    protein: 5.3,
    carbs: 51,
    fat: 15,
    fiber: 1.5,
    servingExamples: { en: '1 medium (113g)', tr: '1 orta boy (113g)' },
  },
  {
    id: 'pancake',
    name: { en: 'Pancake', tr: 'Krep/Pankek' },
    category: 'bread-bakery',
    caloriesPer100g: 227,
    protein: 6.4,
    carbs: 28,
    fat: 10,
    fiber: 1.5,
    servingExamples: { en: '1 pancake (77g)', tr: '1 pankek (77g)' },
  },
  {
    id: 'waffle',
    name: { en: 'Waffle', tr: 'Waffle' },
    category: 'bread-bakery',
    caloriesPer100g: 291,
    protein: 7.9,
    carbs: 38,
    fat: 12,
    fiber: 1.7,
    servingExamples: { en: '1 waffle (75g)', tr: '1 waffle (75g)' },
  },
  {
    id: 'tortilla-flour',
    name: { en: 'Flour Tortilla', tr: 'Un Tortilla' },
    category: 'bread-bakery',
    caloriesPer100g: 312,
    protein: 8.2,
    carbs: 51,
    fat: 8,
    fiber: 3,
    servingExamples: { en: '1 tortilla (49g)', tr: '1 tortilla (49g)' },
  },
  {
    id: 'naan',
    name: { en: 'Naan Bread', tr: 'Naan Ekmeği' },
    category: 'bread-bakery',
    caloriesPer100g: 262,
    protein: 8.7,
    carbs: 45,
    fat: 5.3,
    fiber: 2,
    servingExamples: { en: '1 naan (90g)', tr: '1 naan (90g)' },
  },
  {
    id: 'pretzel',
    name: { en: 'Pretzel', tr: 'Çubuk Kraker' },
    category: 'bread-bakery',
    caloriesPer100g: 380,
    protein: 10,
    carbs: 79,
    fat: 3,
    fiber: 3,
    servingExamples: { en: '10 pretzels (60g)', tr: '10 kraker (60g)' },
  },
  {
    id: 'crackers',
    name: { en: 'Saltine Crackers', tr: 'Tuzlu Kraker' },
    category: 'bread-bakery',
    caloriesPer100g: 421,
    protein: 9.2,
    carbs: 71,
    fat: 10,
    fiber: 2.8,
    servingExamples: { en: '5 crackers (15g)', tr: '5 kraker (15g)' },
  },
  {
    id: 'cornbread',
    name: { en: 'Cornbread', tr: 'Mısır Ekmeği' },
    category: 'bread-bakery',
    caloriesPer100g: 266,
    protein: 6.5,
    carbs: 46,
    fat: 6.5,
    fiber: 3.4,
    servingExamples: { en: '1 piece (60g)', tr: '1 parça (60g)' },
  },
  {
    id: 'baguette',
    name: { en: 'Baguette', tr: 'Baget Ekmek' },
    category: 'bread-bakery',
    caloriesPer100g: 272,
    protein: 9.4,
    carbs: 55,
    fat: 1.6,
    fiber: 2.7,
    servingExamples: { en: '2 oz (56g)', tr: '2 oz (56g)' },
  },
  {
    id: 'rye-bread',
    name: { en: 'Rye Bread', tr: 'Çavdar Ekmeği' },
    category: 'bread-bakery',
    caloriesPer100g: 259,
    protein: 8.5,
    carbs: 48,
    fat: 3.3,
    fiber: 5.8,
    servingExamples: { en: '1 slice (32g)', tr: '1 dilim (32g)' },
  },

  // NUTS & SEEDS (15 items)
  {
    id: 'almonds',
    name: { en: 'Almonds', tr: 'Badem' },
    category: 'nuts-seeds',
    caloriesPer100g: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12.5,
    servingExamples: { en: '1 oz / 23 almonds (28g)', tr: '1 oz / 23 badem (28g)' },
  },
  {
    id: 'walnuts',
    name: { en: 'Walnuts', tr: 'Ceviz' },
    category: 'nuts-seeds',
    caloriesPer100g: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 6.7,
    servingExamples: { en: '1 oz / 14 halves (28g)', tr: '1 oz / 14 yarım (28g)' },
  },
  {
    id: 'cashews',
    name: { en: 'Cashews', tr: 'Kaju' },
    category: 'nuts-seeds',
    caloriesPer100g: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3.3,
    servingExamples: { en: '1 oz / 18 cashews (28g)', tr: '1 oz / 18 kaju (28g)' },
  },
  {
    id: 'pistachios',
    name: { en: 'Pistachios', tr: 'Antep Fıstığı' },
    category: 'nuts-seeds',
    caloriesPer100g: 560,
    protein: 20,
    carbs: 28,
    fat: 45,
    fiber: 10.6,
    servingExamples: { en: '1 oz / 49 kernels (28g)', tr: '1 oz / 49 çekirdek (28g)' },
  },
  {
    id: 'hazelnuts',
    name: { en: 'Hazelnuts', tr: 'Fındık' },
    category: 'nuts-seeds',
    caloriesPer100g: 628,
    protein: 15,
    carbs: 17,
    fat: 61,
    fiber: 9.7,
    servingExamples: { en: '1 oz / 21 nuts (28g)', tr: '1 oz / 21 fındık (28g)' },
  },
  {
    id: 'peanuts',
    name: { en: 'Peanuts', tr: 'Yer Fıstığı' },
    category: 'nuts-seeds',
    caloriesPer100g: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    fiber: 8.5,
    servingExamples: { en: '1 oz / 28 peanuts (28g)', tr: '1 oz / 28 fıstık (28g)' },
  },
  {
    id: 'peanut-butter',
    name: { en: 'Peanut Butter', tr: 'Yer Fıstığı Ezmesi' },
    category: 'nuts-seeds',
    caloriesPer100g: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    servingExamples: { en: '2 tbsp (32g)', tr: '2 yemek kaşığı (32g)' },
  },
  {
    id: 'sunflower-seeds',
    name: { en: 'Sunflower Seeds', tr: 'Ayçiçek Çekirdeği' },
    category: 'nuts-seeds',
    caloriesPer100g: 584,
    protein: 21,
    carbs: 20,
    fat: 51,
    fiber: 8.6,
    servingExamples: { en: '1 oz (28g)', tr: '1 oz (28g)' },
  },
  {
    id: 'pumpkin-seeds',
    name: { en: 'Pumpkin Seeds', tr: 'Kabak Çekirdeği' },
    category: 'nuts-seeds',
    caloriesPer100g: 559,
    protein: 30,
    carbs: 14,
    fat: 49,
    fiber: 6,
    servingExamples: { en: '1 oz (28g)', tr: '1 oz (28g)' },
  },
  {
    id: 'chia-seeds',
    name: { en: 'Chia Seeds', tr: 'Chia Tohumu' },
    category: 'nuts-seeds',
    caloriesPer100g: 486,
    protein: 17,
    carbs: 42,
    fat: 31,
    fiber: 34,
    servingExamples: { en: '1 oz (28g)', tr: '1 oz (28g)' },
  },
  {
    id: 'flax-seeds',
    name: { en: 'Flax Seeds', tr: 'Keten Tohumu' },
    category: 'nuts-seeds',
    caloriesPer100g: 534,
    protein: 18,
    carbs: 29,
    fat: 42,
    fiber: 27,
    servingExamples: { en: '1 tbsp (10g)', tr: '1 yemek kaşığı (10g)' },
  },
  {
    id: 'sesame-seeds',
    name: { en: 'Sesame Seeds', tr: 'Susam' },
    category: 'nuts-seeds',
    caloriesPer100g: 573,
    protein: 18,
    carbs: 23,
    fat: 50,
    fiber: 11.8,
    servingExamples: { en: '1 tbsp (9g)', tr: '1 yemek kaşığı (9g)' },
  },
  {
    id: 'tahini',
    name: { en: 'Tahini', tr: 'Tahin' },
    category: 'nuts-seeds',
    caloriesPer100g: 595,
    protein: 17,
    carbs: 21,
    fat: 54,
    fiber: 9.3,
    servingExamples: { en: '1 tbsp (15g)', tr: '1 yemek kaşığı (15g)' },
  },
  {
    id: 'brazil-nuts',
    name: { en: 'Brazil Nuts', tr: 'Brezilya Cevizi' },
    category: 'nuts-seeds',
    caloriesPer100g: 659,
    protein: 14,
    carbs: 12,
    fat: 67,
    fiber: 7.5,
    servingExamples: { en: '1 oz / 6 nuts (28g)', tr: '1 oz / 6 ceviz (28g)' },
  },
  {
    id: 'macadamia',
    name: { en: 'Macadamia Nuts', tr: 'Makadamya' },
    category: 'nuts-seeds',
    caloriesPer100g: 718,
    protein: 7.9,
    carbs: 14,
    fat: 76,
    fiber: 8.6,
    servingExamples: { en: '1 oz / 10-12 nuts (28g)', tr: '1 oz / 10-12 fındık (28g)' },
  },

  // SWEETS & DESSERTS (10 items)
  {
    id: 'chocolate-dark',
    name: { en: 'Dark Chocolate (70-85% cacao)', tr: 'Bitter Çikolata (70-85% kakao)' },
    category: 'sweets-desserts',
    caloriesPer100g: 598,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    fiber: 11,
    servingExamples: { en: '1 oz (28g)', tr: '1 oz (28g)' },
  },
  {
    id: 'chocolate-milk',
    name: { en: 'Milk Chocolate', tr: 'Sütlü Çikolata' },
    category: 'sweets-desserts',
    caloriesPer100g: 535,
    protein: 8,
    carbs: 59,
    fat: 30,
    fiber: 3.4,
    servingExamples: { en: '1 bar (44g)', tr: '1 bar (44g)' },
  },
  {
    id: 'honey',
    name: { en: 'Honey', tr: 'Bal' },
    category: 'sweets-desserts',
    caloriesPer100g: 304,
    protein: 0.3,
    carbs: 82,
    fat: 0,
    fiber: 0.2,
    servingExamples: { en: '1 tbsp (21g)', tr: '1 yemek kaşığı (21g)' },
  },
  {
    id: 'sugar',
    name: { en: 'White Sugar', tr: 'Beyaz Şeker' },
    category: 'sweets-desserts',
    caloriesPer100g: 387,
    protein: 0,
    carbs: 100,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 tsp (4g)', tr: '1 tatlı kaşığı (4g)' },
  },
  {
    id: 'cake-chocolate',
    name: { en: 'Chocolate Cake with frosting', tr: 'Kakaolu Kek (kremalı)' },
    category: 'sweets-desserts',
    caloriesPer100g: 371,
    protein: 5,
    carbs: 51,
    fat: 17,
    fiber: 2,
    servingExamples: { en: '1 slice (95g)', tr: '1 dilim (95g)' },
  },
  {
    id: 'cookies-chocolate-chip',
    name: { en: 'Chocolate Chip Cookies', tr: 'Damla Çikolatalı Kurabiye' },
    category: 'sweets-desserts',
    caloriesPer100g: 488,
    protein: 5.6,
    carbs: 67,
    fat: 23,
    fiber: 2.4,
    servingExamples: { en: '1 cookie (30g)', tr: '1 kurabiye (30g)' },
  },
  {
    id: 'brownie',
    name: { en: 'Brownie', tr: 'Browni' },
    category: 'sweets-desserts',
    caloriesPer100g: 466,
    protein: 6.3,
    carbs: 63,
    fat: 23,
    fiber: 3,
    servingExamples: { en: '1 square (56g)', tr: '1 parça (56g)' },
  },
  {
    id: 'donut',
    name: { en: 'Glazed Donut', tr: 'Donut' },
    category: 'sweets-desserts',
    caloriesPer100g: 452,
    protein: 4.9,
    carbs: 51,
    fat: 25,
    fiber: 1.4,
    servingExamples: { en: '1 medium donut (52g)', tr: '1 orta boy donut (52g)' },
  },
  {
    id: 'baklava',
    name: { en: 'Baklava', tr: 'Baklava' },
    category: 'sweets-desserts',
    caloriesPer100g: 428,
    protein: 4.5,
    carbs: 51,
    fat: 24,
    fiber: 2.4,
    servingExamples: { en: '1 piece (50g)', tr: '1 dilim (50g)' },
  },
  {
    id: 'turkish-delight',
    name: { en: 'Turkish Delight', tr: 'Lokum' },
    category: 'sweets-desserts',
    caloriesPer100g: 320,
    protein: 0,
    carbs: 80,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 piece (20g)', tr: '1 adet (20g)' },
  },

  // BEVERAGES (15 items)
  {
    id: 'water',
    name: { en: 'Water', tr: 'Su' },
    category: 'beverages',
    caloriesPer100g: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 glass (240ml)', tr: '1 bardak (240ml)' },
  },
  {
    id: 'cola',
    name: { en: 'Cola', tr: 'Kola' },
    category: 'beverages',
    caloriesPer100g: 41,
    protein: 0,
    carbs: 11,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 can (355ml)', tr: '1 kutu (355ml)' },
  },
  {
    id: 'orange-juice',
    name: { en: 'Orange Juice (100%)', tr: 'Portakal Suyu (%100)' },
    category: 'beverages',
    caloriesPer100g: 45,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    fiber: 0.2,
    servingExamples: { en: '1 glass (248ml)', tr: '1 bardak (248ml)' },
  },
  {
    id: 'apple-juice',
    name: { en: 'Apple Juice (100%)', tr: 'Elma Suyu (%100)' },
    category: 'beverages',
    caloriesPer100g: 46,
    protein: 0.1,
    carbs: 11,
    fat: 0.1,
    fiber: 0.2,
    servingExamples: { en: '1 glass (248ml)', tr: '1 bardak (248ml)' },
  },
  {
    id: 'coffee-black',
    name: { en: 'Coffee (black, no sugar)', tr: 'Kahve (sade, şekersiz)' },
    category: 'beverages',
    caloriesPer100g: 1,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 cup (240ml)', tr: '1 fincan (240ml)' },
  },
  {
    id: 'coffee-latte',
    name: { en: 'Latte (whole milk)', tr: 'Latte (tam yağlı süt)' },
    category: 'beverages',
    caloriesPer100g: 53,
    protein: 2.9,
    carbs: 5.4,
    fat: 2.4,
    fiber: 0,
    servingExamples: { en: '12 oz (355ml)', tr: '12 oz (355ml)' },
  },
  {
    id: 'tea-black',
    name: { en: 'Black Tea (unsweetened)', tr: 'Siyah Çay (şekersiz)' },
    category: 'beverages',
    caloriesPer100g: 1,
    protein: 0,
    carbs: 0.3,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 cup (240ml)', tr: '1 bardak (240ml)' },
  },
  {
    id: 'green-tea',
    name: { en: 'Green Tea (unsweetened)', tr: 'Yeşil Çay (şekersiz)' },
    category: 'beverages',
    caloriesPer100g: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 cup (240ml)', tr: '1 bardak (240ml)' },
  },
  {
    id: 'energy-drink',
    name: { en: 'Energy Drink', tr: 'Enerji İçeceği' },
    category: 'beverages',
    caloriesPer100g: 45,
    protein: 0,
    carbs: 11,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 can (250ml)', tr: '1 kutu (250ml)' },
  },
  {
    id: 'sports-drink',
    name: { en: 'Sports Drink', tr: 'Spor İçeceği' },
    category: 'beverages',
    caloriesPer100g: 25,
    protein: 0,
    carbs: 6,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 bottle (591ml)', tr: '1 şişe (591ml)' },
  },
  {
    id: 'beer',
    name: { en: 'Beer (regular)', tr: 'Bira (normal)' },
    category: 'beverages',
    caloriesPer100g: 43,
    protein: 0.5,
    carbs: 3.6,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 can (355ml)', tr: '1 kutu (355ml)' },
  },
  {
    id: 'wine-red',
    name: { en: 'Red Wine', tr: 'Kırmızı Şarap' },
    category: 'beverages',
    caloriesPer100g: 85,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '5 oz glass (148ml)', tr: '5 oz kadeh (148ml)' },
  },
  {
    id: 'wine-white',
    name: { en: 'White Wine', tr: 'Beyaz Şarap' },
    category: 'beverages',
    caloriesPer100g: 82,
    protein: 0.1,
    carbs: 2.6,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '5 oz glass (148ml)', tr: '5 oz kadeh (148ml)' },
  },
  {
    id: 'smoothie-fruit',
    name: { en: 'Fruit Smoothie', tr: 'Meyve Smoothie' },
    category: 'beverages',
    caloriesPer100g: 55,
    protein: 1.1,
    carbs: 13,
    fat: 0.2,
    fiber: 1.2,
    servingExamples: { en: '12 oz (355ml)', tr: '12 oz (355ml)' },
  },
  {
    id: 'almond-milk',
    name: { en: 'Almond Milk (unsweetened)', tr: 'Badem Sütü (şekersiz)' },
    category: 'beverages',
    caloriesPer100g: 15,
    protein: 0.4,
    carbs: 0.6,
    fat: 1.1,
    fiber: 0.2,
    servingExamples: { en: '1 cup (240ml)', tr: '1 su bardağı (240ml)' },
  },

  // FAST FOOD (15 items)
  {
    id: 'burger-beef',
    name: { en: 'Beef Burger (single patty)', tr: 'Hamburger (tek köfte)' },
    category: 'fast-food',
    caloriesPer100g: 254,
    protein: 12,
    carbs: 30,
    fat: 10,
    fiber: 1.5,
    servingExamples: { en: '1 burger (110g)', tr: '1 hamburger (110g)' },
  },
  {
    id: 'cheeseburger',
    name: { en: 'Cheeseburger', tr: 'Cheeseburger' },
    category: 'fast-food',
    caloriesPer100g: 281,
    protein: 14,
    carbs: 29,
    fat: 13,
    fiber: 1.5,
    servingExamples: { en: '1 burger (120g)', tr: '1 burger (120g)' },
  },
  {
    id: 'pizza-margherita',
    name: { en: 'Pizza Margherita', tr: 'Margarita Pizza' },
    category: 'fast-food',
    caloriesPer100g: 266,
    protein: 11,
    carbs: 33,
    fat: 10,
    fiber: 2.3,
    servingExamples: { en: '1 slice (107g)', tr: '1 dilim (107g)' },
  },
  {
    id: 'pizza-pepperoni',
    name: { en: 'Pepperoni Pizza', tr: 'Pepperoni Pizza' },
    category: 'fast-food',
    caloriesPer100g: 298,
    protein: 12,
    carbs: 34,
    fat: 13,
    fiber: 2.3,
    servingExamples: { en: '1 slice (71g)', tr: '1 dilim (71g)' },
  },
  {
    id: 'fries-french',
    name: { en: 'French Fries', tr: 'Patates Kızartması' },
    category: 'fast-food',
    caloriesPer100g: 312,
    protein: 3.4,
    carbs: 41,
    fat: 15,
    fiber: 3.8,
    servingExamples: { en: 'Medium serving (117g)', tr: 'Orta porsiyon (117g)' },
  },
  {
    id: 'chicken-nuggets',
    name: { en: 'Chicken Nuggets', tr: 'Tavuk Nugget' },
    category: 'fast-food',
    caloriesPer100g: 296,
    protein: 16,
    carbs: 18,
    fat: 18,
    fiber: 1,
    servingExamples: { en: '6 pieces (106g)', tr: '6 adet (106g)' },
  },
  {
    id: 'hot-dog',
    name: { en: 'Hot Dog', tr: 'Hot Dog' },
    category: 'fast-food',
    caloriesPer100g: 290,
    protein: 10,
    carbs: 25,
    fat: 17,
    fiber: 1,
    servingExamples: { en: '1 hot dog (98g)', tr: '1 hot dog (98g)' },
  },
  {
    id: 'taco',
    name: { en: 'Taco (beef)', tr: 'Taco (sığır eti)' },
    category: 'fast-food',
    caloriesPer100g: 226,
    protein: 9.1,
    carbs: 18,
    fat: 14,
    fiber: 3,
    servingExamples: { en: '1 taco (102g)', tr: '1 taco (102g)' },
  },
  {
    id: 'burrito',
    name: { en: 'Burrito (beef and bean)', tr: 'Burrito (et ve fasulye)' },
    category: 'fast-food',
    caloriesPer100g: 151,
    protein: 6.6,
    carbs: 17,
    fat: 6,
    fiber: 3,
    servingExamples: { en: '1 burrito (217g)', tr: '1 burrito (217g)' },
  },
  {
    id: 'sandwich-chicken',
    name: { en: 'Fried Chicken Sandwich', tr: 'Kızarmış Tavuk Sandviç' },
    category: 'fast-food',
    caloriesPer100g: 248,
    protein: 14,
    carbs: 23,
    fat: 12,
    fiber: 1.5,
    servingExamples: { en: '1 sandwich (182g)', tr: '1 sandviç (182g)' },
  },
  {
    id: 'kebab-doner',
    name: { en: 'Doner Kebab', tr: 'Döner Kebap' },
    category: 'fast-food',
    caloriesPer100g: 178,
    protein: 11,
    carbs: 16,
    fat: 8,
    fiber: 1.2,
    servingExamples: { en: '1 wrap (300g)', tr: '1 dürüm (300g)' },
  },
  {
    id: 'lahmacun',
    name: { en: 'Lahmacun', tr: 'Lahmacun' },
    category: 'fast-food',
    caloriesPer100g: 230,
    protein: 8.5,
    carbs: 28,
    fat: 9,
    fiber: 2,
    servingExamples: { en: '1 piece (120g)', tr: '1 adet (120g)' },
  },
  {
    id: 'pide',
    name: { en: 'Turkish Pide (cheese)', tr: 'Peynirli Pide' },
    category: 'fast-food',
    caloriesPer100g: 265,
    protein: 11,
    carbs: 35,
    fat: 9,
    fiber: 2,
    servingExamples: { en: '1 slice (150g)', tr: '1 dilim (150g)' },
  },
  {
    id: 'onion-rings',
    name: { en: 'Onion Rings', tr: 'Soğan Halkası' },
    category: 'fast-food',
    caloriesPer100g: 411,
    protein: 5.3,
    carbs: 38,
    fat: 27,
    fiber: 2.7,
    servingExamples: { en: '8-9 rings (83g)', tr: '8-9 halka (83g)' },
  },
  {
    id: 'fish-sandwich',
    name: { en: 'Fish Sandwich', tr: 'Balık Ekmek' },
    category: 'fast-food',
    caloriesPer100g: 226,
    protein: 10,
    carbs: 26,
    fat: 9,
    fiber: 1.5,
    servingExamples: { en: '1 sandwich (158g)', tr: '1 sandviç (158g)' },
  },

  // OILS & SAUCES (10 items)
  {
    id: 'olive-oil',
    name: { en: 'Olive Oil', tr: 'Zeytinyağı' },
    category: 'oils-sauces',
    caloriesPer100g: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    servingExamples: { en: '1 tbsp (14g)', tr: '1 yemek kaşığı (14g)' },
  },
  {
    id: 'vegetable-oil',
    name: { en: 'Vegetable Oil', tr: 'Bitkisel Yağ' },
    category: 'oils-sauces',
    caloriesPer100g: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    servingExamples: { en: '1 tbsp (14g)', tr: '1 yemek kaşığı (14g)' },
  },
  {
    id: 'coconut-oil',
    name: { en: 'Coconut Oil', tr: 'Hindistancevizi Yağı' },
    category: 'oils-sauces',
    caloriesPer100g: 892,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    servingExamples: { en: '1 tbsp (14g)', tr: '1 yemek kaşığı (14g)' },
  },
  {
    id: 'mayonnaise',
    name: { en: 'Mayonnaise', tr: 'Mayonez' },
    category: 'oils-sauces',
    caloriesPer100g: 680,
    protein: 1.1,
    carbs: 0.6,
    fat: 75,
    fiber: 0,
    servingExamples: { en: '1 tbsp (14g)', tr: '1 yemek kaşığı (14g)' },
  },
  {
    id: 'ketchup',
    name: { en: 'Ketchup', tr: 'Ketçap' },
    category: 'oils-sauces',
    caloriesPer100g: 112,
    protein: 1.2,
    carbs: 27,
    fat: 0.1,
    fiber: 0.3,
    servingExamples: { en: '1 tbsp (17g)', tr: '1 yemek kaşığı (17g)' },
  },
  {
    id: 'mustard',
    name: { en: 'Mustard', tr: 'Hardal' },
    category: 'oils-sauces',
    caloriesPer100g: 66,
    protein: 3.7,
    carbs: 5.3,
    fat: 3.3,
    fiber: 3.3,
    servingExamples: { en: '1 tsp (5g)', tr: '1 tatlı kaşığı (5g)' },
  },
  {
    id: 'soy-sauce',
    name: { en: 'Soy Sauce', tr: 'Soya Sosu' },
    category: 'oils-sauces',
    caloriesPer100g: 53,
    protein: 5.6,
    carbs: 4.9,
    fat: 0.1,
    fiber: 0.8,
    servingExamples: { en: '1 tbsp (16g)', tr: '1 yemek kaşığı (16g)' },
  },
  {
    id: 'bbq-sauce',
    name: { en: 'BBQ Sauce', tr: 'Barbekü Sos' },
    category: 'oils-sauces',
    caloriesPer100g: 172,
    protein: 0.9,
    carbs: 41,
    fat: 0.5,
    fiber: 1.2,
    servingExamples: { en: '2 tbsp (36g)', tr: '2 yemek kaşığı (36g)' },
  },
  {
    id: 'ranch-dressing',
    name: { en: 'Ranch Dressing', tr: 'Ranch Sos' },
    category: 'oils-sauces',
    caloriesPer100g: 478,
    protein: 1.3,
    carbs: 5.7,
    fat: 50,
    fiber: 0,
    servingExamples: { en: '2 tbsp (30g)', tr: '2 yemek kaşığı (30g)' },
  },
  {
    id: 'balsamic-vinegar',
    name: { en: 'Balsamic Vinegar', tr: 'Balsamik Sirke' },
    category: 'oils-sauces',
    caloriesPer100g: 88,
    protein: 0.5,
    carbs: 17,
    fat: 0,
    fiber: 0,
    servingExamples: { en: '1 tbsp (16g)', tr: '1 yemek kaşığı (16g)' },
  },
];

// Category definitions
export const categories: CategoryInfo[] = [
  {
    name: 'fruits',
    label: { en: 'Fruits', tr: 'Meyveler' },
    icon: '🍎',
    description: {
      en: 'Fresh fruits rich in vitamins, minerals, and fiber',
      tr: 'Vitamin, mineral ve lif açısından zengin taze meyveler',
    },
  },
  {
    name: 'vegetables',
    label: { en: 'Vegetables', tr: 'Sebzeler' },
    icon: '🥕',
    description: {
      en: 'Nutritious vegetables low in calories and high in nutrients',
      tr: 'Kalori açısından düşük, besin değeri yüksek sebzeler',
    },
  },
  {
    name: 'meat-poultry',
    label: { en: 'Meat & Poultry', tr: 'Et ve Tavuk' },
    icon: '🍗',
    description: {
      en: 'High-protein meat and poultry options',
      tr: 'Yüksek proteinli et ve tavuk seçenekleri',
    },
  },
  {
    name: 'fish-seafood',
    label: { en: 'Fish & Seafood', tr: 'Balık ve Deniz Ürünleri' },
    icon: '🐟',
    description: {
      en: 'Lean protein sources from the sea',
      tr: 'Denizden gelen yağsız protein kaynakları',
    },
  },
  {
    name: 'dairy',
    label: { en: 'Dairy', tr: 'Süt Ürünleri' },
    icon: '🥛',
    description: {
      en: 'Milk, cheese, yogurt and other dairy products',
      tr: 'Süt, peynir, yoğurt ve diğer süt ürünleri',
    },
  },
  {
    name: 'grains-legumes',
    label: { en: 'Grains & Legumes', tr: 'Tahıllar ve Baklagiller' },
    icon: '🌾',
    description: {
      en: 'Rice, pasta, beans and other grain-based foods',
      tr: 'Pirinç, makarna, fasulye ve diğer tahıl bazlı gıdalar',
    },
  },
  {
    name: 'bread-bakery',
    label: { en: 'Bread & Bakery', tr: 'Ekmek ve Unlu Mamuller' },
    icon: '🍞',
    description: {
      en: 'Breads, pastries and baked goods',
      tr: 'Ekmekler, hamur işleri ve fırın ürünleri',
    },
  },
  {
    name: 'nuts-seeds',
    label: { en: 'Nuts & Seeds', tr: 'Kuruyemişler ve Tohumlar' },
    icon: '🥜',
    description: {
      en: 'Calorie-dense nuts and seeds',
      tr: 'Kalori yoğunluğu yüksek kuruyemişler ve tohumlar',
    },
  },
  {
    name: 'sweets-desserts',
    label: { en: 'Sweets & Desserts', tr: 'Tatlılar ve Şekerli Ürünler' },
    icon: '🍰',
    description: {
      en: 'Sweets, candies and desserts',
      tr: 'Tatlılar, şekerlemeler ve tatlı ürünler',
    },
  },
  {
    name: 'beverages',
    label: { en: 'Beverages', tr: 'İçecekler' },
    icon: '🥤',
    description: {
      en: 'Drinks, juices and other beverages',
      tr: 'İçecekler, meyve suları ve diğer sıvı ürünler',
    },
  },
  {
    name: 'fast-food',
    label: { en: 'Fast Food', tr: 'Fast Food' },
    icon: '🍔',
    description: {
      en: 'Quick service restaurant foods',
      tr: 'Hızlı servis restoranlarının yiyecekleri',
    },
  },
  {
    name: 'oils-sauces',
    label: { en: 'Oils & Sauces', tr: 'Yağlar ve Soslar' },
    icon: '🫗',
    description: {
      en: 'Cooking oils, dressings and sauces',
      tr: 'Yemeklik yağlar, soslar ve çeşniler',
    },
  },
];

// Helper functions
export function calculateFoodNutrition(food: FoodItem, grams: number) {
  const multiplier = grams / 100;
  return {
    calories: Math.round(food.caloriesPer100g * multiplier),
    protein: Math.round(food.protein * multiplier * 10) / 10,
    carbs: Math.round(food.carbs * multiplier * 10) / 10,
    fat: Math.round(food.fat * multiplier * 10) / 10,
    fiber: food.fiber ? Math.round(food.fiber * multiplier * 10) / 10 : 0,
  };
}

export function calculateTotalNutrition(selectedFoods: SelectedFood[]): NutritionSummary {
  const foods = selectedFoods.map((sf) => {
    const nutrition = calculateFoodNutrition(sf.food, sf.grams);
    return {
      food: sf.food,
      grams: sf.grams,
      ...nutrition,
    };
  });

  const totals = foods.reduce(
    (acc, food) => ({
      totalCalories: acc.totalCalories + food.calories,
      totalProtein: acc.totalProtein + food.protein,
      totalCarbs: acc.totalCarbs + food.carbs,
      totalFat: acc.totalFat + food.fat,
      totalFiber: acc.totalFiber + food.fiber,
    }),
    { totalCalories: 0, totalProtein: 0, totalCarbs: 0, totalFat: 0, totalFiber: 0 }
  );

  return {
    ...totals,
    foods,
  };
}

export function searchFoods(query: string, locale: 'en' | 'tr'): FoodItem[] {
  const lowerQuery = query.toLowerCase();
  return foodDatabase.filter((food) => food.name[locale].toLowerCase().includes(lowerQuery));
}

export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return foodDatabase.filter((food) => food.category === category);
}

export function getCategoryInfo(category: FoodCategory): CategoryInfo | undefined {
  return categories.find((c) => c.name === category);
}

// Enhanced calculation functions
import type { MacroDistribution, MealSummary, HealthScore, MealType } from './foodCalorieTypes';

export function calculateMacroDistribution(
  totalProtein: number,
  totalCarbs: number,
  totalFat: number
): MacroDistribution {
  const proteinCalories = totalProtein * 4;
  const carbsCalories = totalCarbs * 4;
  const fatCalories = totalFat * 9;
  const totalCal = proteinCalories + carbsCalories + fatCalories;

  if (totalCal === 0) {
    return {
      proteinPercentage: 0,
      carbsPercentage: 0,
      fatPercentage: 0,
      proteinCalories: 0,
      carbsCalories: 0,
      fatCalories: 0,
    };
  }

  return {
    proteinPercentage: Math.round((proteinCalories / totalCal) * 100),
    carbsPercentage: Math.round((carbsCalories / totalCal) * 100),
    fatPercentage: Math.round((fatCalories / totalCal) * 100),
    proteinCalories: Math.round(proteinCalories),
    carbsCalories: Math.round(carbsCalories),
    fatCalories: Math.round(fatCalories),
  };
}

export function calculateMealSummary(selectedFoods: SelectedFood[]): MealSummary {
  const summary: MealSummary = {
    breakfast: { calories: 0, protein: 0, carbs: 0, fat: 0, count: 0 },
    lunch: { calories: 0, protein: 0, carbs: 0, fat: 0, count: 0 },
    dinner: { calories: 0, protein: 0, carbs: 0, fat: 0, count: 0 },
    snack: { calories: 0, protein: 0, carbs: 0, fat: 0, count: 0 },
  };

  selectedFoods.forEach((sf) => {
    const nutrition = calculateFoodNutrition(sf.food, sf.grams);
    const mealType = sf.mealType || 'snack';

    summary[mealType].calories += nutrition.calories;
    summary[mealType].protein += nutrition.protein;
    summary[mealType].carbs += nutrition.carbs;
    summary[mealType].fat += nutrition.fat;
    summary[mealType].count += 1;
  });

  // Round values
  Object.keys(summary).forEach((key) => {
    const meal = summary[key as MealType];
    meal.protein = Math.round(meal.protein * 10) / 10;
    meal.carbs = Math.round(meal.carbs * 10) / 10;
    meal.fat = Math.round(meal.fat * 10) / 10;
  });

  return summary;
}

export function calculateHealthScore(
  totalCalories: number,
  totalProtein: number,
  totalFiber: number,
  macroDistribution: MacroDistribution,
  varietyCount: number
): HealthScore {
  let proteinScore = 0;
  let fiberScore = 0;
  let balanceScore = 0;
  let varietyScore = 0;

  // Protein score (0-25 points) - based on % of calories from protein
  const proteinPercent = macroDistribution.proteinPercentage;
  if (proteinPercent >= 20 && proteinPercent <= 35) proteinScore = 25;
  else if (proteinPercent >= 15 && proteinPercent < 20) proteinScore = 20;
  else if (proteinPercent >= 10 && proteinPercent < 15) proteinScore = 15;
  else proteinScore = 5;

  // Fiber score (0-25 points) - based on fiber per 1000 calories
  const fiberPer1000Cal = totalCalories > 0 ? (totalFiber / totalCalories) * 1000 : 0;
  if (fiberPer1000Cal >= 14) fiberScore = 25;
  else if (fiberPer1000Cal >= 10) fiberScore = 20;
  else if (fiberPer1000Cal >= 6) fiberScore = 15;
  else if (fiberPer1000Cal >= 3) fiberScore = 10;
  else fiberScore = 5;

  // Balance score (0-30 points) - based on macro distribution
  const { proteinPercentage, carbsPercentage, fatPercentage } = macroDistribution;
  const idealProtein = 25;
  const idealCarbs = 50;
  const idealFat = 25;

  const proteinDiff = Math.abs(proteinPercentage - idealProtein);
  const carbsDiff = Math.abs(carbsPercentage - idealCarbs);
  const fatDiff = Math.abs(fatPercentage - idealFat);
  const totalDiff = proteinDiff + carbsDiff + fatDiff;

  if (totalDiff <= 20) balanceScore = 30;
  else if (totalDiff <= 40) balanceScore = 20;
  else if (totalDiff <= 60) balanceScore = 10;
  else balanceScore = 5;

  // Variety score (0-20 points) - based on number of different foods
  if (varietyCount >= 10) varietyScore = 20;
  else if (varietyCount >= 7) varietyScore = 15;
  else if (varietyCount >= 5) varietyScore = 10;
  else if (varietyCount >= 3) varietyScore = 5;
  else varietyScore = 0;

  const overall = proteinScore + fiberScore + balanceScore + varietyScore;

  return {
    overall,
    proteinScore,
    fiberScore,
    balanceScore,
    varietyScore,
  };
}

export function calculateNutrientDensity(
  totalProtein: number,
  totalFiber: number,
  totalCalories: number
): number {
  if (totalCalories === 0) return 0;

  // Calculate nutrients (protein + fiber) per 100 calories
  const nutrientsPerCal = ((totalProtein + totalFiber) / totalCalories) * 100;
  return Math.round(nutrientsPerCal * 10) / 10;
}

export function calculateEnhancedNutrition(
  selectedFoods: SelectedFood[],
  dailyGoalCalories?: number
): NutritionSummary {
  const basic = calculateTotalNutrition(selectedFoods);

  // Macro distribution
  const macroDistribution = calculateMacroDistribution(
    basic.totalProtein,
    basic.totalCarbs,
    basic.totalFat
  );

  // Meal summary
  const mealSummary = calculateMealSummary(selectedFoods);

  // Health score
  const healthScore = calculateHealthScore(
    basic.totalCalories,
    basic.totalProtein,
    basic.totalFiber,
    macroDistribution,
    selectedFoods.length
  );

  // Nutrient density
  const nutrientDensity = calculateNutrientDensity(
    basic.totalProtein,
    basic.totalFiber,
    basic.totalCalories
  );

  // Daily goal tracking
  let dailyGoal;
  if (dailyGoalCalories && dailyGoalCalories > 0) {
    const remaining = dailyGoalCalories - basic.totalCalories;
    const progress = Math.min(100, Math.round((basic.totalCalories / dailyGoalCalories) * 100));
    dailyGoal = {
      targetCalories: dailyGoalCalories,
      remainingCalories: remaining,
      progressPercentage: progress,
    };
  }

  // Add meal type to foods
  const foodsWithMeal = basic.foods.map((f, index) => ({
    ...f,
    mealType: selectedFoods[index].mealType,
  }));

  return {
    ...basic,
    foods: foodsWithMeal,
    macroDistribution,
    mealSummary,
    healthScore,
    nutrientDensity,
    dailyGoal,
  };
}
