import { CalculatorMeta } from '@/types/calculator';
import ChineseGenderCalculator from './ChineseGenderCalculator';

export const chineseGenderMeta: CalculatorMeta = {
  id: 'chinese-gender-predictor',
  category: 'pregnancy',
  slug: {
    en: 'chinese-gender-predictor',
    tr: 'cin-cinsiyet-tahmini',
  },
  title: {
    en: 'Chinese Gender Predictor - Ancient Chinese Baby Gender Calendar',
    tr: 'Çin Cinsiyet Tahmincisi - Eski Çin Bebek Cinsiyet Takvimi',
  },
  description: {
    en: 'Free Chinese Gender Predictor calculator using the ancient Chinese birth chart and lunar calendar. Predict baby gender based on mother\'s lunar age and conception month. Interactive tool with detailed explanations, Chinese zodiac information, scientific accuracy analysis, and comprehensive FAQs. Learn about the 700-year-old tradition, calculation methodology, and reliable medical alternatives. Entertainment purposes only - ~50% accuracy.',
    tr: 'Eski Çin doğum tablosunu ve ay takvimini kullanan ücretsiz Çin Cinsiyet Tahmincisi hesaplayıcısı. Annenin ay yaşı ve hamilelik ayına göre bebek cinsiyetini tahmin edin. Detaylı açıklamalar, Çin burcu bilgisi, bilimsel doğruluk analizi ve kapsamlı SSS içeren interaktif araç. 700 yıllık gelenek, hesaplama metodolojisi ve güvenilir tıbbi alternatifler hakkında bilgi edinin. Sadece eğlence amaçlı - %50 doğruluk oranı.',
  },
  keywords: [
    'chinese gender predictor',
    'chinese gender calendar',
    'chinese baby gender chart',
    'chinese birth chart',
    'lunar age calculator',
    'baby gender prediction',
    'ancient chinese calendar',
    'boy or girl predictor',
    'chinese gender test',
    'pregnancy gender calculator',
    'chinese zodiac',
    'lunar calendar pregnancy',
    'gender prediction chart',
    'chinese gender predictor calculator free',
    'how accurate is chinese gender predictor',
    'chinese gender chart 2024',
    'lunar age gender prediction',
    'chinese conception chart',
    'am i having a boy or girl chinese calendar',
    'chinese gender predictor by conception date',
    'baby gender calculator lunar calendar',
    'ancient chinese gender selection',
    'chinese gender chart accuracy',
    'chinese birth calendar boy or girl',
    'cin cinsiyet tahmini',
    'cin cinsiyet takvimi',
    'bebek cinsiyeti tahmini',
    'ay yaşı hesaplama',
    'cin doğum takvimi',
    'cin burcu',
    'hamilelik cinsiyeti',
    'erkek mi kız mı',
    'eski cin takvimi',
    'ay takvimi hamilelik',
    'cin cinsiyet tahmini doğru mu',
    'cin cinsiyet tablosu nasıl kullanılır',
    'hamilelik döllendirme tarihi cinsiyet',
    'ay yaşı ile cinsiyet tahmini',
    'bebek cinsiyeti nasıl anlaşılır',
    'cin cinsiyet tahmini 2024',
  ],
  icon: 'Sparkles',
  popular: true,
  featured: true,
  component: ChineseGenderCalculator,
};
