import { CalculatorContent } from '@/types/calculator';

export const calorieContent: CalculatorContent = {
  en: {
    whatIs:
      'A calorie calculator is a scientific tool that determines your daily caloric needs based on individual factors including age, gender, height, weight, and physical activity level. The calculation provides your Basal Metabolic Rate (BMR)—the number of calories your body burns at complete rest—and your Total Daily Energy Expenditure (TDEE), which accounts for your activity level. Understanding your caloric needs is fundamental for achieving any health or fitness goal, whether you aim to lose weight, maintain your current weight, or build muscle mass. The calculator uses validated formulas like the Mifflin-St Jeor equation (considered the most accurate for modern populations) or the Harris-Benedict equation to estimate your metabolic rate. These calculations help create personalized nutrition plans by establishing baseline calorie targets that can be adjusted based on specific goals such as cutting body fat, maintaining weight, or gaining lean muscle mass.',

    howToCalculate:
      'To calculate your daily calorie needs, you need five key pieces of information: age, biological sex, height, weight, and activity level. First, the calculator determines your BMR using either the Mifflin-St Jeor formula (recommended) or Harris-Benedict equation. For men using Mifflin-St Jeor: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) + 5. For women: BMR = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) - 161. Next, your BMR is multiplied by an activity factor: sedentary (1.2), lightly active (1.375), moderately active (1.55), very active (1.725), or extra active (1.9). This produces your TDEE, representing total daily calories burned. For weight loss, create a caloric deficit of 10-25% below TDEE; for muscle gain, add a 10-20% surplus; for maintenance, consume at TDEE. The calculator provides multiple calorie targets: extreme weight loss (-30%), weight loss (-20%), mild weight loss (-10%), maintenance (0%), mild weight gain (+10%), weight gain (+20%), and extreme weight gain (+30%). Most experts recommend moderate approaches (-20% for cutting, +20% for bulking) for sustainable, healthy results.',

    formulaDetails:
      'The Mifflin-St Jeor equation, developed in 1990, is currently considered the most accurate BMR formula for modern populations and has replaced the older Harris-Benedict equation in most clinical settings. The formula accounts for the fact that muscle tissue burns more calories than fat tissue, which explains why men (who typically have more muscle mass) have a higher constant (+5) than women (-161). After calculating BMR, the Harris-Benedict activity multipliers translate this resting metabolic rate into total daily expenditure: Sedentary (little/no exercise) = BMR × 1.2, Lightly Active (light exercise 1-3 days/week) = BMR × 1.375, Moderately Active (moderate exercise 3-5 days/week) = BMR × 1.55, Very Active (hard exercise 6-7 days/week) = BMR × 1.725, Extra Active (very hard exercise, physical job, or 2x/day training) = BMR × 1.9. For example, a 30-year-old woman who is 165 cm tall, weighs 65 kg, and is moderately active would calculate: BMR = (10 × 65) + (6.25 × 165) - (5 × 30) - 161 = 1,370 calories. TDEE = 1,370 × 1.55 = 2,124 calories per day. This means she burns approximately 2,124 calories daily and should eat around this amount to maintain her current weight. For a 20% caloric deficit to lose weight, she would target approximately 1,699 calories per day (2,124 × 0.8).',

    interpretation:
      'Understanding your calorie calculation results requires knowing how to apply them to your specific goals. Your BMR represents the minimum calories needed for basic physiological functions like breathing, circulation, cell production, and nutrient processing—essentially what you would burn in a coma. Your TDEE represents realistic daily expenditure including all activities. The difference between these numbers reveals how many calories your physical activities burn. For weight loss, creating a caloric deficit forces your body to use stored fat for energy; a 500-calorie daily deficit typically results in 1 pound of fat loss per week (3,500 calories equals roughly 1 pound of fat). For muscle gain, a caloric surplus provides the extra energy needed for protein synthesis and muscle repair after resistance training. However, excessive surpluses lead to unnecessary fat gain, so moderate surpluses (10-20%) are recommended. Weight maintenance requires eating at TDEE levels. It is crucial to monitor your body\'s response over 2-4 weeks and adjust calories accordingly, as metabolic adaptation can occur. If weight loss stalls, reassess your activity multiplier, as people often overestimate their activity level. Remember that these are starting estimates; individual metabolic variations mean you may need to adjust based on actual results.',

    limitations:
      'Calorie calculators provide estimates, not precise measurements, due to several important limitations. First, formulas like Mifflin-St Jeor and Harris-Benedict are population averages that may not perfectly match your individual metabolism. Actual metabolic rates can vary by 10-30% between individuals of the same size due to genetic factors, thyroid function, medications, previous dieting history, and body composition differences. Second, activity level multipliers are approximate and subject to interpretation—many people overestimate their activity level, selecting "moderately active" when "lightly active" is more accurate. Third, these calculators do not account for medical conditions affecting metabolism such as hypothyroidism, PCOS, diabetes, or hormonal imbalances. Fourth, the calculators assume average body composition, but individuals with significantly higher muscle mass (athletes, bodybuilders) or lower muscle mass (elderly, sarcopenic individuals) will have different metabolic rates than predicted. Fifth, adaptive thermogenesis (metabolic adaptation) is not factored in—chronic dieting can reduce metabolic rate by 10-20% beyond what would be expected from weight loss alone. Sixth, the calculations do not consider the thermic effect of different macronutrients (protein requires more energy to digest than carbohydrates or fats). Seventh, NEAT (Non-Exercise Activity Thermogenesis) varies widely between individuals and is difficult to quantify. Finally, calorie counting itself has limitations because food labels can be inaccurate by up to 20%, and absorption efficiency varies. For these reasons, use calculator results as starting points and adjust based on real-world results over several weeks.',

    healthRisks:
      'Both excessive caloric restriction and overconsumption carry significant health risks. Extreme calorie deficits (below 1,200 calories for women or 1,500 for men) can lead to malnutrition, muscle loss, metabolic slowdown, hormonal disruptions (including loss of menstruation in women), weakened immune function, hair loss, fatigue, dizziness, constipation, and increased risk of gallstones. Very low calorie diets can trigger the "starvation response," where the body aggressively conserves energy and increases hunger hormones, often leading to rebound weight gain. Rapid weight loss from extreme restriction frequently results in loss of lean muscle mass rather than fat, which further depresses metabolic rate. Psychologically, severe restriction often leads to obsessive food thoughts, binge eating, and development of disordered eating patterns. On the opposite end, chronic caloric surplus beyond what is needed for muscle growth leads to excessive fat accumulation, particularly visceral fat around organs, which increases risk for type 2 diabetes, cardiovascular disease, hypertension, fatty liver disease, sleep apnea, certain cancers, and joint problems from carrying excess weight. Even when bulking for muscle gain, excessive surpluses (>500 calories above TDEE) result primarily in fat gain rather than additional muscle, as there is a limit to how quickly muscle can be built (typically 0.5-1 pound per week for beginners, less for advanced lifters). The healthiest approach involves moderate caloric adjustments (200-500 calorie deficit or surplus), patience with results, focus on whole nutrient-dense foods, adequate protein intake (1.6-2.2g per kg body weight), resistance training to preserve muscle during cuts or build muscle during bulks, and regular health monitoring including energy levels, performance, mood, sleep quality, and menstrual regularity in women. Macronutrient distribution is crucial: prioritize protein (1.6-2.2g per kg body weight), set fats at 20-35% of calories, and fill remaining calories with carbohydrates based on activity level.',

    alternativeMeasures:
      'While total calorie intake determines weight change, tracking accuracy and consistency are equally important. Use a digital food scale to weigh foods in grams for precision. Track everything including oils, condiments, and beverages. Apps like MyFitnessPal or Cronometer provide comprehensive databases. Weigh yourself consistently at the same time daily and focus on weekly averages rather than daily fluctuations. Monitor non-scale victories including energy levels, workout performance, how clothes fit, and body measurements. After 4-8 weeks of strict tracking to learn portion sizes, some successfully transition to intuitive eating while others benefit from continued monitoring.',

    medicalDisclaimer:
      'This calorie calculator is provided for educational and informational purposes only and is not intended as a substitute for professional medical advice, diagnosis, or treatment. Calorie calculations are population-based estimates that may not accurately represent your individual metabolic rate due to genetic, medical, or physiological factors. Always consult with qualified healthcare professionals—including physicians, registered dietitians, or certified nutritionists—before making significant changes to your diet or exercise regimen, especially if you have pre-existing medical conditions, take medications, are pregnant or breastfeeding, have a history of eating disorders, are under 18 years old, or are significantly overweight or underweight. Individuals with diabetes, cardiovascular disease, kidney disease, thyroid disorders, hormonal imbalances, or any chronic health conditions should receive personalized medical guidance before pursuing calorie-restricted or calorie-surplus diets. Very low calorie diets (below 1,200 calories for women or 1,500 for men) should only be attempted under direct medical supervision. If you experience symptoms such as extreme fatigue, dizziness, hair loss, menstrual irregularities, persistent hunger, obsessive food thoughts, binge eating behaviors, or any concerning physical or psychological symptoms while following a calorie-controlled diet, consult a healthcare provider immediately. The calculator does not account for individual medical conditions, medications affecting metabolism, previous dieting history, or metabolic adaptation. Results should be used as starting estimates and adjusted based on individual response and professional guidance.',

    references: [
      'Mifflin MD, St Jeor ST, Hill LA, et al. A new predictive equation for resting energy expenditure in healthy individuals. Am J Clin Nutr. 1990;51(2):241-247.',
      'Harris JA, Benedict FG. A Biometric Study of Human Basal Metabolism. Proc Natl Acad Sci U S A. 1918;4(12):370-373.',
      'Frankenfield D, Roth-Yousey L, Compher C. Comparison of predictive equations for resting metabolic rate in healthy nonobese and obese adults. J Am Diet Assoc. 2005;105(5):775-789.',
      'Hall KD, Chow CC. Why is the 3500 kcal per pound weight loss rule wrong? Int J Obes. 2013;37(12):1614.',
      'Thomas DM, Martin CK, Lettieri S, et al. Can a weight loss of one pound a week be achieved with a 3500-kcal deficit? Commentary on a commonly accepted rule. Int J Obes. 2013;37(12):1611-1613.',
      'Müller MJ, Enderle J, Bosy-Westphal A. Changes in energy expenditure with weight gain and weight loss in humans. Curr Obes Rep. 2016;5(4):413-423.',
      'Academy of Nutrition and Dietetics. Position Paper: Nutrition and Athletic Performance. J Acad Nutr Diet. 2016;116(3):501-528.',
      'International Society of Sports Nutrition: Protein and Exercise. J Int Soc Sports Nutr. 2017;14:20.',
    ],

    tips: [
      'Use calorie calculations as starting estimates and adjust based on real-world results over 2-4 weeks',
      'Track body weight trends rather than daily fluctuations—weigh yourself at the same time each day and calculate weekly averages',
      'Prioritize protein intake (1.6-2.2g per kg body weight) to preserve muscle during weight loss or build muscle during weight gain',
      'Focus on whole, nutrient-dense foods rather than just meeting calorie targets with processed foods',
      'Moderate calorie deficits (-500 cal) or surpluses (+300-500 cal) are more sustainable than extreme approaches',
      'Combine calorie tracking with strength training to maintain or build muscle mass',
      'Be honest about your activity level—most people overestimate and should start with a lower activity multiplier',
      'Reassess your calorie needs every 10-15 pounds of weight loss or if fat loss stalls for 2-3 weeks',
      'Eat at maintenance calories for 1-2 weeks every 2-3 months during prolonged diets to support hormonal health',
      'Monitor non-scale metrics: energy levels, workout performance, sleep quality, mood, and body measurements',
    ],

    faqs: [
      {
        question: 'How many calories should I eat to lose weight?',
        answer:
          'To lose weight safely and sustainably, create a caloric deficit of 10-25% below your TDEE (Total Daily Energy Expenditure). A 500-calorie daily deficit typically results in about 1 pound of weight loss per week, while a 750-calorie deficit yields approximately 1.5 pounds per week. Most experts recommend 1-2 pounds per week for healthy, sustainable fat loss. Never go below 1,200 calories per day for women or 1,500 for men without medical supervision, as extreme restriction can slow metabolism, cause muscle loss, and create nutritional deficiencies. Prioritize protein intake (1.6-2.2g per kg body weight) and resistance training to preserve muscle mass during weight loss.',
      },
      {
        question: 'What is the difference between BMR and TDEE?',
        answer:
          'BMR (Basal Metabolic Rate) is the number of calories your body burns at complete rest to maintain basic physiological functions like breathing, circulation, cell production, and nutrient processing. TDEE (Total Daily Energy Expenditure) is your BMR multiplied by an activity factor, representing the total calories you burn throughout the day including all physical activities, exercise, and non-exercise movement. For example, if your BMR is 1,500 calories and you are moderately active (1.55 multiplier), your TDEE would be approximately 2,325 calories. You should base your calorie intake goals on TDEE, not BMR.',
      },
      {
        question: 'How accurate are calorie calculators?',
        answer:
          'Calorie calculators provide estimates based on population averages and may vary from your actual metabolic rate by 10-30%. Factors that affect accuracy include individual genetic variations, body composition (muscle vs. fat ratio), thyroid function, previous dieting history, medications, and age. Activity level multipliers are also subjective—many people overestimate their activity level. Use calculator results as starting points and adjust based on real-world results over 2-4 weeks. If you are not losing weight at the predicted deficit, reduce calories by 100-200 or increase activity. Professional metabolic testing (indirect calorimetry) can provide more accurate measurements.',
      },
      {
        question: 'Should I eat the same calories every day?',
        answer:
          'Most people benefit from consistent daily calories, but there are valid approaches to varying intake. Consistent calories simplify tracking and create predictable results. However, calorie cycling (varying intake across the week while maintaining the same weekly average) can be effective—for example, eating more on training days and less on rest days. Intermittent fasting approaches involve significant daily variations. The most important factor is your weekly or monthly average calorie intake. Some find that higher calories on weekends for social events, balanced by stricter weekdays, creates better adherence. Choose the pattern that best fits your lifestyle and preferences while hitting weekly targets.',
      },
      {
        question: 'Can I lose weight without counting calories?',
        answer:
          'Yes, many people successfully lose weight without tracking calories by using alternative strategies: eating whole, unprocessed foods that naturally promote satiety; practicing portion control; eating mindfully without distractions; stopping when satisfied rather than stuffed; reducing liquid calories; increasing protein and fiber intake; and following structured eating patterns like intermittent fasting or time-restricted eating. However, calorie tracking is useful for those who have plateaued with intuitive approaches, want to ensure adequate protein intake, need precise control for specific body composition goals, or want to develop better portion awareness. Many use tracking initially (4-8 weeks) to develop intuition, then transition to mindful eating.',
      },
      {
        question: 'How many calories do I need to build muscle?',
        answer:
          'Building muscle requires a combination of progressive resistance training, adequate protein intake (1.6-2.2g per kg body weight), and a caloric surplus to provide energy for protein synthesis and recovery. A moderate surplus of 200-500 calories above TDEE is recommended, as excessive surpluses primarily create fat gain rather than additional muscle. Natural lifters can typically build 0.5-1 pound of muscle per week as beginners, 0.5 pounds per month as intermediates, and even less as advanced lifters. This means a surplus of only 200-300 calories is sufficient for most people. "Lean bulking" with smaller surpluses minimizes fat gain and reduces the need for aggressive cutting phases later. Track body weight and strength progress—if gaining more than 2-4 pounds per month, reduce surplus to minimize fat accumulation.',
      },
      {
        question: 'Why am I not losing weight despite eating in a calorie deficit?',
        answer:
          'Several factors can explain plateaus despite apparent deficits: (1) Tracking inaccuracies—studies show people underestimate calorie intake by 20-50%, especially for restaurant meals, oils, condiments, and portion sizes; (2) Metabolic adaptation—your body reduces NEAT (non-exercise activity), lowers BMR slightly, and becomes more efficient, reducing actual deficit; (3) Water retention from new exercise, high sodium, hormonal changes (menstrual cycle), or stress can mask fat loss on the scale for 1-4 weeks; (4) Overestimating calorie burn from exercise—most devices and formulas overestimate by 20-40%; (5) Not accounting for reduced calories needed as body weight decreases—reassess TDEE every 10-15 pounds lost. Solutions: tighten tracking accuracy with food scale, reduce calories by 100-200, increase activity, take a diet break at maintenance for 1-2 weeks to reset hormones, or consult a healthcare provider to rule out medical issues like hypothyroidism.',
      },
    ],
  },
  tr: {
    whatIs:
      'Kalori hesaplayıcı, yaş, cinsiyet, boy, kilo ve fiziksel aktivite düzeyi gibi bireysel faktörlere dayalı olarak günlük kalori ihtiyacınızı belirleyen bilimsel bir araçtır. Hesaplama, tam dinlenme halinde vücudunuzun yaktığı kalori sayısı olan Bazal Metabolizma Hızınızı (BMR) ve aktivite düzeyinizi hesaba katan Toplam Günlük Enerji Harcamanızı (TDEE) sağlar. Kalori ihtiyacınızı anlamak, kilo verme, mevcut kilonuzu koruma veya kas kütlesi oluşturma gibi her türlü sağlık veya fitness hedefine ulaşmak için temeldir. Hesaplayıcı, modern popülasyonlar için en doğru kabul edilen Mifflin-St Jeor denklemi veya Harris-Benedict denklemi gibi doğrulanmış formüller kullanarak metabolik hızınızı tahmin eder. Bu hesaplamalar, vücut yağını azaltma, kilo koruma veya yağsız kas kütlesi kazanma gibi belirli hedeflere göre ayarlanabilecek temel kalori hedefleri oluşturarak kişiselleştirilmiş beslenme planları oluşturmaya yardımcı olur.',

    howToCalculate:
      'Günlük kalori ihtiyacınızı hesaplamak için beş önemli bilgiye ihtiyacınız vardır: yaş, biyolojik cinsiyet, boy, kilo ve aktivite düzeyi. İlk olarak, hesaplayıcı Mifflin-St Jeor formülü (önerilen) veya Harris-Benedict denklemini kullanarak BMR\'nizi belirler. Mifflin-St Jeor kullanan erkekler için: BMR = 10 × kilo(kg) + 6,25 × boy(cm) - 5 × yaş(yıl) + 5. Kadınlar için: BMR = 10 × kilo(kg) + 6,25 × boy(cm) - 5 × yaş(yıl) - 161. Daha sonra, BMR\'niz bir aktivite faktörüyle çarpılır: hareketsiz (1,2), hafif aktif (1,375), orta derecede aktif (1,55), çok aktif (1,725) veya ekstra aktif (1,9). Bu, günlük yakılan toplam kalorileri temsil eden TDEE\'nizi üretir. Kilo kaybı için, TDEE\'nin %10-25 altında kalorik açık oluşturun; kas kazanımı için %10-20 fazlalık ekleyin; kilo koruma için TDEE\'de tüketin. Hesaplayıcı birden fazla kalori hedefi sağlar: aşırı kilo verme (-%30), kilo verme (-%20), hafif kilo verme (-%10), koruma (%0), hafif kilo alma (%10), kilo alma (%20) ve aşırı kilo alma (%30). Çoğu uzman, sürdürülebilir, sağlıklı sonuçlar için ılımlı yaklaşımlar (kesme için -%20, toplu için %20) önerir.',

    formulaDetails:
      '1990\'da geliştirilen Mifflin-St Jeor denklemi, şu anda modern popülasyonlar için en doğru BMR formülü olarak kabul edilmektedir ve çoğu klinik ortamda eski Harris-Benedict denkleminin yerini almıştır. Formül, kas dokusunun yağ dokusundan daha fazla kalori yaktığı gerçeğini hesaba katar; bu, erkeklerin (genellikle daha fazla kas kütlesine sahip olanların) kadınlardan daha yüksek bir sabite (+5) sahip olmasını açıklar (-161). BMR hesaplandıktan sonra, Harris-Benedict aktivite çarpanları bu dinlenme metabolik hızını toplam günlük harcamaya dönüştürür: Hareketsiz (az/hiç egzersiz yok) = BMR × 1,2, Hafif Aktif (haftada 1-3 gün hafif egzersiz) = BMR × 1,375, Orta Derecede Aktif (haftada 3-5 gün orta düzeyde egzersiz) = BMR × 1,55, Çok Aktif (haftada 6-7 gün sert egzersiz) = BMR × 1,725, Ekstra Aktif (çok sert egzersiz, fiziksel iş veya günde 2x antrenman) = BMR × 1,9. Örneğin, 165 cm boyunda, 65 kg ağırlığında ve orta derecede aktif olan 30 yaşında bir kadın şöyle hesaplar: BMR = (10 × 65) + (6,25 × 165) - (5 × 30) - 161 = 1.370 kalori. TDEE = 1.370 × 1,55 = 2.124 kalori/gün. Bu, günde yaklaşık 2.124 kalori yaktığı ve mevcut kilosunu korumak için bu miktar civarında yemesi gerektiği anlamına gelir. Kilo vermek için %20 kalorik açık için, günde yaklaşık 1.699 kaloriyi (2.124 × 0,8) hedefler.',

    interpretation:
      'Kalori hesaplama sonuçlarınızı anlamak, bunları belirli hedeflerinize nasıl uygulayacağınızı bilmeyi gerektirir. BMR\'niz, nefes alma, dolaşım, hücre üretimi ve besin işleme gibi temel fizyolojik işlevler için gereken minimum kalorileri temsil eder—esasen komada olsaydınız yakacağınız şey. TDEE\'niz, tüm aktiviteler dahil gerçekçi günlük harcamayı temsil eder. Bu sayılar arasındaki fark, fiziksel aktivitelerinizin kaç kalori yaktığını ortaya çıkarır. Kilo kaybı için, kalorik açık oluşturmak vücudunuzu enerji için depolanmış yağ kullanmaya zorlar; günlük 500 kalorili açık genellikle haftada 1 pound yağ kaybına neden olur (3.500 kalori kabaca 1 pound yağa eşittir). Kas kazanımı için, kalorik fazlalık, direnç antrenmanından sonra protein sentezi ve kas onarımı için gereken ekstra enerjiyi sağlar. Ancak, aşırı fazlalıklar gereksiz yağ kazanımına yol açar, bu nedenle ılımlı fazlalıklar (%10-20) önerilir. Kilo koruma, TDEE seviyelerinde yemeyi gerektirir. Metabolik adaptasyon meydana gelebileceğinden, vücudunuzun tepkisini 2-4 hafta boyunca izlemek ve kalorileri buna göre ayarlamak çok önemlidir. Kilo kaybı duruyorsa, aktivite çarpanınızı yeniden değerlendirin, çünkü insanlar genellikle aktivite seviyelerini fazla tahmin eder. Bunların başlangıç tahminleri olduğunu unutmayın; bireysel metabolik varyasyonlar, gerçek sonuçlara göre ayarlama yapmanız gerekebileceği anlamına gelir.',

    limitations:
      'Kalori hesaplayıcılar, birkaç önemli sınırlama nedeniyle kesin ölçümler değil, tahminler sağlar. İlk olarak, Mifflin-St Jeor ve Harris-Benedict gibi formüller, bireysel metabolizmanızla mükemmel bir şekilde eşleşmeyebilecek popülasyon ortalamalarıdır. Gerçek metabolik oranlar, genetik faktörler, tiroid fonksiyonu, ilaçlar, önceki diyet geçmişi ve vücut kompozisyonu farklılıkları nedeniyle aynı büyüklükteki bireyler arasında %10-30 oranında değişebilir. İkinci olarak, aktivite düzeyi çarpanları yaklaşıktır ve yoruma tabidir—birçok kişi aktivite düzeyini fazla tahmin eder, "hafif aktif" daha doğru olduğunda "orta derecede aktif" seçer. Üçüncü olarak, bu hesaplayıcılar hipotiroidizm, PKOS, diyabet veya hormonal dengesizlikler gibi metabolizmayı etkileyen tıbbi durumları hesaba katmaz. Dördüncü olarak, hesaplayıcılar ortalama vücut kompozisyonunu varsayar, ancak önemli ölçüde daha yüksek kas kütlesine (sporcular, vücut geliştiriciler) veya daha düşük kas kütlesine (yaşlı, sarkopenik bireyler) sahip bireyler, tahmin edilenden farklı metabolik oranlara sahip olacaklardır. Beşinci olarak, adaptif termogenez (metabolik adaptasyon) hesaba katılmaz—kronik diyet, kilo kaybından beklenenin ötesinde metabolik oranı %10-20 oranında azaltabilir. Altıncı olarak, hesaplamalar farklı makro besinlerin termik etkisini dikkate almaz (protein, karbonhidratlar veya yağlardan daha fazla enerji sindirmeyi gerektirir). Yedinci olarak, NEAT (Egzersiz Dışı Aktivite Termogenezi) bireyler arasında büyük ölçüde değişir ve ölçülmesi zordur. Son olarak, gıda etiketleri %20\'ye kadar yanlış olabileceğinden ve emilim verimliliği değiştiğinden, kalori saymanın kendisinin sınırlamaları vardır. Bu nedenlerle, hesaplayıcı sonuçlarını başlangıç noktaları olarak kullanın ve birkaç hafta boyunca gerçek dünya sonuçlarına göre ayarlayın.',

    healthRisks:
      'Hem aşırı kalorik kısıtlama hem de aşırı tüketim önemli sağlık riskleri taşır. Aşırı kalori açıkları (kadınlar için 1.200 kalorinin altında veya erkekler için 1.500) yetersiz beslenme, kas kaybı, metabolik yavaşlama, hormonal bozukluklar (kadınlarda adet kaybı dahil), zayıflamış bağışıklık fonksiyonu, saç dökülmesi, yorgunluk, baş dönmesi, kabızlık ve artan safra taşı riskine yol açabilir. Çok düşük kalorili diyetler "açlık tepkisini" tetikleyebilir; burada vücut agresif bir şekilde enerji korur ve açlık hormonlarını artırır, bu da genellikle yeniden kilo alımına yol açar. Aşırı kısıtlamadan kaynaklanan hızlı kilo kaybı sıklıkla yağ yerine yağsız kas kütlesi kaybına neden olur, bu da metabolik oranı daha da düşürür. Psikolojik olarak, ciddi kısıtlama genellikle obsesif gıda düşüncelerine, aşırı yemeye ve düzensiz yeme kalıplarının gelişmesine yol açar. Diğer tarafta, kas büyümesi için gerekenden fazla kronik kalorik fazlalık, özellikle organlar etrafındaki visseral yağ olmak üzere aşırı yağ birikimine yol açar, bu da tip 2 diyabet, kardiyovasküler hastalık, hipertansiyon, yağlı karaciğer hastalığı, uyku apnesi, belirli kanserler ve aşırı kilonun eklemler üzerindeki sorunlarını artırır. Kas kazanımı için toplu bile olsa, aşırı fazlalıklar (TDEE\'nin >500 kalori üstü) ek kas yerine öncelikle yağ kazanımıyla sonuçlanır, çünkü kasın ne kadar hızlı inşa edilebileceğinin bir sınırı vardır (genellikle yeni başlayanlar için haftada 0,5-1 pound, ileri seviye kaldırıcılar için daha az). En sağlıklı yaklaşım, ılımlı kalorik ayarlamaları (200-500 kalori açık veya fazlalık), sonuçlara karşı sabır, tam besin değeri yüksek gıdalara odaklanma, yeterli protein alımı (vücut ağırlığının kg başına 1,6-2,2g), kesimler sırasında kası korumak veya toplu sırasında kas oluşturmak için direnç antrenmanı ve enerji seviyeleri, performans, ruh hali, uyku kalitesi ve kadınlarda adet düzenliliği dahil düzenli sağlık izlemeyi içerir. Makrobesin dağılımı çok önemlidir: proteine öncelik verin (vücut ağırlığının kg başına 1,6-2,2g), yağları kalorilerin %20-35\'i olarak ayarlayın ve kalan kalorileri aktivite düzeyine göre karbonhidratlarla doldurun.',

    alternativeMeasures:
      'Toplam kalori alımı kilo değişimini belirlerken, takip doğruluğu ve tutarlılığı eşit derecede önemlidir. Hassasiyet için gıdaları gram cinsinden tartmak için dijital bir gıda terazisi kullanın. Yağlar, çeşniler ve içecekler dahil her şeyi takip edin. MyFitnessPal veya Cronometer gibi uygulamalar kapsamlı veritabanları sağlar. Her gün aynı saatte tutarlı bir şekilde kendinizi tartın ve günlük dalgalanmalar yerine haftalık ortalamalara odaklanın. Enerji seviyeleri, antrenman performansı, kıyafetlerin nasıl oturduğu ve vücut ölçümleri dahil ölçek dışı başarıları izleyin. Porsiyon boyutlarını öğrenmek için 4-8 hafta sıkı takipten sonra, bazıları sezgisel yemeye başarılı bir şekilde geçiş yaparken, diğerleri devam eden izlemeden faydalanır.',

    medicalDisclaimer:
      'Bu kalori hesaplayıcı yalnızca eğitim ve bilgilendirme amaçlıdır ve profesyonel tıbbi tavsiye, teşhis veya tedavinin yerine geçmez. Kalori hesaplamaları, genetik, tıbbi veya fizyolojik faktörler nedeniyle bireysel metabolik hızınızı doğru bir şekilde temsil etmeyebilecek popülasyona dayalı tahminlerdir. Diyetinizde veya egzersiz rejiminizde önemli değişiklikler yapmadan önce, özellikle önceden var olan tıbbi durumlarınız varsa, ilaç alıyorsanız, hamile veya emziriyorsanız, yeme bozukluğu geçmişiniz varsa, 18 yaşın altındaysanız veya önemli ölçüde fazla kilolu veya zayıfsanız, her zaman doktorlar, kayıtlı diyetisyenler veya sertifikalı beslenme uzmanları dahil kalifiye sağlık profesyonelleriyle görüşün. Diyabet, kardiyovasküler hastalık, böbrek hastalığı, tiroid bozuklukları, hormonal dengesizlikler veya herhangi bir kronik sağlık durumu olan bireyler, kalori kısıtlamalı veya kalori fazlalıklı diyetlere başlamadan önce kişiselleştirilmiş tıbbi rehberlik almalıdır. Çok düşük kalorili diyetler (kadınlar için 1.200 kalorinin altında veya erkekler için 1.500) yalnızca doğrudan tıbbi gözetim altında denenmelidir. Kalorice kontrollü bir diyet izlerken aşırı yorgunluk, baş dönmesi, saç dökülmesi, adet düzensizlikleri, sürekli açlık, obsesif gıda düşünceleri, aşırı yeme davranışları veya herhangi bir endişe verici fiziksel veya psikolojik semptom yaşarsanız, derhal bir sağlık hizmeti sağlayıcısına danışın. Hesaplayıcı, bireysel tıbbi durumları, metabolizmayı etkileyen ilaçları, önceki diyet geçmişini veya metabolik adaptasyonu hesaba katmaz. Sonuçlar, başlangıç tahminleri olarak kullanılmalı ve bireysel tepkiye ve profesyonel rehberliğe göre ayarlanmalıdır.',

    references: [
      'Mifflin MD, St Jeor ST, Hill LA, ve ark. Sağlıklı bireylerde dinlenme enerji harcaması için yeni bir öngörücü denklem. Am J Clin Nutr. 1990;51(2):241-247.',
      'Harris JA, Benedict FG. İnsan Bazal Metabolizmasının Biyometrik Çalışması. Proc Natl Acad Sci U S A. 1918;4(12):370-373.',
      'Frankenfield D, Roth-Yousey L, Compher C. Sağlıklı obez olmayan ve obez yetişkinlerde dinlenme metabolik hızı için öngörücü denklemlerin karşılaştırılması. J Am Diet Assoc. 2005;105(5):775-789.',
      'Hall KD, Chow CC. Neden 3500 kcal pound başına kilo kaybı kuralı yanlış? Int J Obes. 2013;37(12):1614.',
      'Thomas DM, Martin CK, Lettieri S, ve ark. Haftada bir pound kilo kaybı 3500 kcal açıkla elde edilebilir mi? Yaygın olarak kabul edilen bir kural üzerine yorum. Int J Obes. 2013;37(12):1611-1613.',
      'Müller MJ, Enderle J, Bosy-Westphal A. İnsanlarda kilo alımı ve kilo kaybı ile enerji harcamasındaki değişiklikler. Curr Obes Rep. 2016;5(4):413-423.',
      'Beslenme ve Diyetetik Akademisi. Pozisyon Belgesi: Beslenme ve Atletik Performans. J Acad Nutr Diet. 2016;116(3):501-528.',
      'Uluslararası Spor Beslenmesi Derneği: Protein ve Egzersiz. J Int Soc Sports Nutr. 2017;14:20.',
    ],

    tips: [
      'Kalori hesaplamalarını başlangıç tahminleri olarak kullanın ve 2-4 hafta boyunca gerçek dünya sonuçlarına göre ayarlayın',
      'Günlük dalgalanmalar yerine vücut ağırlığı eğilimlerini izleyin—her gün aynı zamanda kendinizi tartın ve haftalık ortalamaları hesaplayın',
      'Kilo kaybı sırasında kası korumak veya kilo alımı sırasında kas oluşturmak için protein alımına öncelik verin (vücut ağırlığının kg başına 1,6-2,2g)',
      'Sadece kalori hedeflerini karşılamak için işlenmiş gıdalarla değil, tam, besin değeri yüksek gıdalara odaklanın',
      'Ilımlı kalori açıkları (-500 kal) veya fazlalıkları (+300-500 kal) aşırı yaklaşımlardan daha sürdürülebilirdir',
      'Kas kütlesini korumak veya oluşturmak için kalori takibini güç antrenmanı ile birleştirin',
      'Aktivite düzeyiniz konusunda dürüst olun—çoğu insan fazla tahmin eder ve daha düşük bir aktivite çarpanıyla başlamalıdır',
      'Her 10-15 pound kilo kaybından sonra veya yağ kaybı 2-3 hafta boyunca duruyorsa kalori ihtiyaçlarınızı yeniden değerlendirin',
      'Uzun süreli diyetler sırasında hormonal sağlığı desteklemek için her 2-3 ayda bir 1-2 hafta bakım kalorilerinde yiyin',
      'Ölçek dışı metrikleri izleyin: enerji seviyeleri, antrenman performansı, uyku kalitesi, ruh hali ve vücut ölçümleri',
    ],

    faqs: [
      {
        question: 'Kilo vermek için kaç kalori yemeliyim?',
        answer:
          'Güvenli ve sürdürülebilir bir şekilde kilo vermek için, TDEE\'nizin (Toplam Günlük Enerji Harcaması) %10-25 altında kalorik açık oluşturun. Günlük 500 kalorili açık genellikle haftada yaklaşık 1 pound kilo kaybına neden olurken, 750 kalorili açık haftada yaklaşık 1,5 pound verir. Çoğu uzman, sağlıklı, sürdürülebilir yağ kaybı için haftada 1-2 pound önerir. Tıbbi gözetim olmadan kadınlar için günde 1.200 kalorinin, erkekler için 1.500\'ün altına asla inmeyin, çünkü aşırı kısıtlama metabolizmayı yavaşlatabilir, kas kaybına neden olabilir ve beslenme eksiklikleri yaratabilir. Kilo kaybı sırasında kas kütlesini korumak için protein alımına (vücut ağırlığının kg başına 1,6-2,2g) ve direnç antrenmanına öncelik verin.',
      },
      {
        question: 'BMR ve TDEE arasındaki fark nedir?',
        answer:
          'BMR (Bazal Metabolizma Hızı), vücudunuzun nefes alma, dolaşım, hücre üretimi ve besin işleme gibi temel fizyolojik işlevleri sürdürmek için tam dinlenme halinde yaktığı kalori sayısıdır. TDEE (Toplam Günlük Enerji Harcaması), BMR\'nizin bir aktivite faktörüyle çarpımıdır ve tüm fiziksel aktiviteler, egzersiz ve egzersiz dışı hareket dahil gün boyunca yaktığınız toplam kalorileri temsil eder. Örneğin, BMR\'niz 1.500 kalori ise ve orta derecede aktifseniz (1,55 çarpan), TDEE\'niz yaklaşık 2.325 kalori olacaktır. Kalori alımı hedeflerinizi BMR\'ye değil TDEE\'ye dayandırmalısınız.',
      },
      {
        question: 'Kalori hesaplayıcılar ne kadar doğru?',
        answer:
          'Kalori hesaplayıcılar popülasyon ortalamalarına dayalı tahminler sağlar ve gerçek metabolik hızınızdan %10-30 oranında değişebilir. Doğruluğu etkileyen faktörler arasında bireysel genetik varyasyonlar, vücut kompozisyonu (kas ve yağ oranı), tiroid fonksiyonu, önceki diyet geçmişi, ilaçlar ve yaş bulunur. Aktivite düzeyi çarpanları da özneldir—birçok kişi aktivite düzeyini fazla tahmin eder. Hesaplayıcı sonuçlarını başlangıç noktaları olarak kullanın ve 2-4 hafta boyunca gerçek dünya sonuçlarına göre ayarlayın. Öngörülen açıkta kilo vermiyorsanız, kalorileri 100-200 azaltın veya aktiviteyi artırın. Profesyonel metabolik test (dolaylı kalorimetre) daha doğru ölçümler sağlayabilir.',
      },
      {
        question: 'Her gün aynı kalorileri yemeli miyim?',
        answer:
          'Çoğu insan tutarlı günlük kalorilerden faydalanır, ancak alımı değiştirmek için geçerli yaklaşımlar vardır. Tutarlı kalori takibi basitleştirir ve öngörülebilir sonuçlar yaratır. Ancak, kalori döngüsü (aynı haftalık ortalamayı korurken hafta boyunca alımı değiştirmek) etkili olabilir—örneğin, antrenman günlerinde daha fazla, dinlenme günlerinde daha az yemek. Aralıklı oruç yaklaşımları önemli günlük varyasyonlar içerir. En önemli faktör, haftalık veya aylık ortalama kalori alımınızdır. Bazıları, sosyal etkinlikler için hafta sonları daha yüksek kalorilerin, daha sıkı hafta içi günleriyle dengelenmesinin daha iyi uyum yarattığını düşünür. Haftalık hedeflere ulaşırken yaşam tarzınıza ve tercihlerinize en uygun modeli seçin.',
      },
      {
        question: 'Kalori saymadan kilo verebilir miyim?',
        answer:
          'Evet, birçok insan alternatif stratejiler kullanarak kalori takibi yapmadan başarılı bir şekilde kilo verir: tokluk hissini doğal olarak teşvik eden tam, işlenmemiş gıdalar yemek; porsiyon kontrolü uygulamak; dikkatli yemek, dikkat dağıtıcı şeyler olmadan; tıka basa dolmak yerine tatmin olduğunda durmak; sıvı kalorileri azaltmak; protein ve lif alımını artırmak; ve aralıklı oruç veya zamana kısıtlı yeme gibi yapılandırılmış yeme kalıplarını takip etmek. Ancak, kalori takibi, sezgisel yaklaşımlarla durgunluk yaşayanlar, yeterli protein alımını sağlamak isteyenler, belirli vücut kompozisyonu hedefleri için kesin kontrol gerektirerek veya daha iyi porsiyon farkındalığı geliştirmek isteyenler için yararlıdır. Birçoğu, sezgi geliştirmek için başlangıçta (4-8 hafta) takip kullanır, sonra bilinçli yemeye geçiş yapar.',
      },
      {
        question: 'Kas oluşturmak için kaç kaloriye ihtiyacım var?',
        answer:
          'Kas oluşturmak, ilerleyici direnç antrenmanı, yeterli protein alımı (vücut ağırlığının kg başına 1,6-2,2g) ve protein sentezi ve iyileşme için enerji sağlamak için kalorik fazlalık kombinasyonu gerektirir. Aşırı fazlalıklar öncelikle ek kas yerine yağ kazanımı yarattığından, TDEE\'nin üzerinde 200-500 kalorili ılımlı fazlalık önerilir. Doğal kaldırıcılar genellikle yeni başlayanlar olarak haftada 0,5-1 pound kas oluşturabilir, orta düzey olarak ayda 0,5 pound ve ileri düzey kaldırıcılar olarak daha da az. Bu, çoğu insan için sadece 200-300 kalorili fazlalığın yeterli olduğu anlamına gelir. Daha küçük fazlalıklarla "yağsız toplu", yağ kazanımını en aza indirir ve daha sonra agresif kesme aşamalarına olan ihtiyacı azaltır. Vücut ağırlığını ve kuvvet ilerlemesini izleyin—ayda 2-4 pound\'dan fazla kazanıyorsanız, yağ birikimini en aza indirmek için fazlalığı azaltın.',
      },
      {
        question: 'Kalori açığında yemek yememe rağmen neden kilo vermiyorum?',
        answer:
          'Birkaç faktör, görünür açıklara rağmen durgunlukları açıklayabilir: (1) Takip yanlışlıkları—çalışmalar insanların kalori alımını %20-50 oranında hafife aldıklarını gösteriyor, özellikle restoran yemekleri, yağlar, çeşniler ve porsiyon boyutları için; (2) Metabolik adaptasyon—vücudunuz NEAT\'ı (egzersiz dışı aktivite) azaltır, BMR\'yi hafifçe düşürür ve daha verimli hale gelir, gerçek açığı azaltır; (3) Yeni egzersiz, yüksek sodyum, hormonal değişiklikler (adet döngüsü) veya stresten kaynaklanan su tutma, terazideki yağ kaybını 1-4 hafta boyunca gizleyebilir; (4) Egzersizden kalori yanmasını fazla tahmin etmek—çoğu cihaz ve formül %20-40 oranında fazla tahmin eder; (5) Vücut ağırlığı azaldıkça ihtiyaç duyulan azaltılmış kalorileri hesaba katmamak—her 10-15 pound kaybedildikten sonra TDEE\'yi yeniden değerlendirin. Çözümler: gıda terazisiyle takip doğruluğunu sıkılaştırın, kalorileri 100-200 azaltın, aktiviteyi artırın, hormonları sıfırlamak için 1-2 hafta bakımda diyet molası verin veya hipotiroidizm gibi tıbbi sorunları ekarte etmek için bir sağlık hizmeti sağlayıcısına danışın.',
      },
    ],
  },
};
