import { CalculatorContent } from '@/types/calculator';

export const gfrContent: CalculatorContent = {
  en: {
    whatIs:
      'Glomerular Filtration Rate (GFR) is a crucial measurement that indicates how well your kidneys are filtering waste products from your blood. GFR represents the volume of fluid filtered from the renal glomerular capillaries into the Bowman\'s capsule per unit time, typically measured in milliliters per minute per 1.73 square meters (mL/min/1.73m²). The kidneys contain approximately one million filtering units called nephrons, each containing a glomerulus. These glomeruli work continuously to remove waste products, excess fluids, and toxins from the bloodstream while retaining essential proteins and blood cells. A normal GFR is typically 90 mL/min/1.73m² or higher in healthy adults, though this naturally declines with age. GFR estimation is essential for detecting and monitoring chronic kidney disease (CKD), which affects approximately 10% of the global population. Since directly measuring GFR requires complex procedures involving timed urine collection and administration of exogenous markers, healthcare providers typically use estimation equations based on serum creatinine, age, sex, and race. The most commonly used formulas include the CKD-EPI (Chronic Kidney Disease Epidemiology Collaboration) equation, which is considered more accurate than the older MDRD (Modification of Diet in Renal Disease) equation, especially for GFR values above 60. Understanding your GFR helps identify kidney disease early when interventions can slow progression and prevent complications such as cardiovascular disease, anemia, bone disease, and eventual kidney failure requiring dialysis or transplantation.',

    formulaDetails:
      'GFR is estimated using the CKD-EPI 2021 equation, which relies on three input variables: serum creatinine concentration, patient age, and biological sex. The 2021 revision of the CKD-EPI equation deliberately removed the race coefficient that was present in the older 2009 version, because studies demonstrated that race-based adjustments were inaccurate across diverse populations and could cause real harm to patient care by systematically delaying diagnoses in certain groups. The mathematical structure of the formula is: eGFR = 142 × min(Scr/κ, 1)^α × max(Scr/κ, 1)^(−1.200) × 0.9938^Age × (1.012 if female), where κ equals 0.7 for females or 0.9 for males, and α equals −0.241 for females or −0.302 for males. Creatinine is a byproduct of normal muscle metabolism; the kidneys filter it from the blood at a rate that is directly proportional to kidney filtration capacity, making serum creatinine a reliable and practical proxy for estimating GFR. A normal eGFR value is defined as 90 mL/min/1.73m² or higher in healthy adults.',

    howToCalculate:
      'GFR calculation uses estimation equations based on serum creatinine levels along with demographic factors. The CKD-EPI equation, currently recommended by major nephrology organizations, provides the most accurate estimates for most patients. For the CKD-EPI equation, the formula varies based on sex and creatinine level. For females with creatinine ≤ 0.7 mg/dL: GFR = 144 × (creatinine/0.7)^(-0.329) × (0.993)^age. For females with creatinine > 0.7: GFR = 144 × (creatinine/0.7)^(-1.209) × (0.993)^age. For males with creatinine ≤ 0.9: GFR = 141 × (creatinine/0.9)^(-0.411) × (0.993)^age. For males with creatinine > 0.9: GFR = 141 × (creatinine/0.9)^(-1.209) × (0.993)^age. Previously, an additional factor of 1.159 was applied for African American patients, but recent guidelines recommend removing race from the equation due to concerns about health equity and the social rather than biological basis of race categories. The calculation requires a blood test to measure serum creatinine, a waste product produced by normal muscle breakdown. Creatinine is filtered by the kidneys, so higher blood creatinine levels indicate lower kidney function. However, creatinine production varies based on muscle mass, so the equation adjusts for age (older people have less muscle) and sex (males typically have more muscle mass). For more accurate assessment in certain populations, additional markers like cystatin C can be incorporated into the CKD-EPI equation. The MDRD equation, though older, may still be used in some settings: GFR = 175 × (creatinine)^(-1.154) × (age)^(-0.203) × (0.742 if female). These equations provide estimated GFR (eGFR) values that correlate well with measured GFR in most cases, though accuracy may be reduced in extremes of body size, pregnancy, severe malnutrition, or rapidly changing kidney function.',

    interpretation:
      'GFR results are interpreted according to standardized stages of chronic kidney disease defined by the National Kidney Foundation. Stage 1 (GFR ≥ 90 mL/min/1.73m²) indicates normal or high kidney function, though kidney damage may be present if there are other abnormalities like protein in urine. Stage 2 (GFR 60-89) represents mild reduction in kidney function. Both stages 1 and 2 require evidence of kidney damage (such as albuminuria, structural abnormalities, or genetic kidney disease) to diagnose CKD, as GFR naturally declines with age. Stage 3a (GFR 45-59) and Stage 3b (GFR 30-44) represent mild to moderate and moderate to severe reduction in kidney function respectively. At these stages, patients should be under nephrology care and monitored for complications including anemia, bone disease, and cardiovascular risk. Stage 4 (GFR 15-29) indicates severe reduction in kidney function, requiring preparation for potential renal replacement therapy and aggressive management of complications. Stage 5 (GFR < 15) is kidney failure, requiring dialysis or kidney transplantation for survival. The rate of GFR decline is also important - rapid decreases (>5 mL/min/1.73m² per year) suggest progressive kidney disease requiring urgent intervention. Several factors besides kidney disease can affect GFR temporarily, including dehydration (decreases GFR), high protein intake (increases GFR), certain medications (especially NSAIDs and ACE inhibitors), and acute illness. Therefore, abnormal GFR results should be repeated and evaluated in clinical context. It\'s also important to note that GFR estimation equations may be less accurate in certain populations including children, pregnant women, people with extreme body sizes, those with unusual muscle mass (bodybuilders or amputees), and certain ethnic groups.',

    healthRisks:
      'Reduced kidney function, reflected by a low GFR, leads to a cascade of progressive and potentially life-threatening complications if it is not identified and managed early. Cardiovascular events — specifically heart attack and stroke — represent the leading cause of death among patients with chronic kidney disease (CKD), occurring at two to five times the rate observed in the general population. As kidney filtration declines, fluid and electrolyte imbalances become increasingly dangerous: hyperkalemia (elevated potassium) can trigger life-threatening cardiac arrhythmias, while fluid retention causes peripheral edema and worsens pre-existing heart failure. Anemia develops because the kidneys produce erythropoietin, the hormone essential for red blood cell formation, and reduced production leads to chronic fatigue and reduced oxygen delivery. Renal osteodystrophy (bone disease caused by kidney dysfunction) weakens the skeletal system and raises fracture risk significantly. Metabolic acidosis, characterized by acid accumulation in the blood, disrupts multiple organ systems including the cardiovascular, respiratory, and musculoskeletal systems. End-stage renal disease (ESRD), defined as GFR falling below 15 mL/min/1.73m², necessitates dialysis or kidney transplantation to sustain life. Early detection of declining GFR through regular monitoring remains critical, because CKD is frequently asymptomatic until it has reached an advanced stage.',

    alternativeMeasures:
      'Cystatin C is an alternative biomarker for kidney function assessment that offers a meaningful advantage over creatinine: it is produced at a relatively constant rate by all nucleated cells and is not significantly affected by muscle mass, making cystatin C-based GFR equations more accurate for individuals with abnormal muscle mass such as the elderly, malnourished patients, or highly muscular individuals. Equations that combine both serum creatinine and cystatin C provide the most accurate eGFR estimates currently available and are recommended by guidelines when single-marker equations are insufficiently reliable. The 24-hour urine creatinine clearance method — which involves collecting all urine produced over a 24-hour period to directly measure creatinine excretion — is considered the clinical gold standard for kidney function measurement, though it is impractical for routine clinical use because of the significant patient burden and frequent collection errors. Inulin clearance represents the true physiological gold standard used exclusively in research settings, as it measures GFR without any estimation, but it is not feasible in everyday clinical practice. Kidney biopsies provide histological information that can determine the underlying cause of kidney disease when GFR values alone are insufficient for diagnosis and management. For the most complete picture of kidney health, guidelines recommend monitoring both eGFR and the urine albumin-to-creatinine ratio (ACR) together, as this combination enables accurate staging and individualized risk stratification.',

    demographicDifferences:
      'Age is the single strongest predictor of GFR decline across the population: kidney filtration capacity naturally decreases by approximately 1 mL/min/1.73m² per year after age 40, which means that older adults are statistically more likely to fall into lower eGFR categories even in the complete absence of underlying kidney disease. Sex differences in GFR are well documented: women generally have slightly lower GFR than men at the same age, primarily because women have lower average muscle mass and therefore produce less creatinine, which can paradoxically make their eGFR appear better than it truly is when creatinine-based equations are used in isolation. Muscle mass represents a major confounding factor in creatinine-based GFR estimation — very muscular individuals may have elevated serum creatinine that falsely suggests reduced kidney function, while individuals with low muscle mass may have a falsely normal eGFR that masks early kidney damage. Dietary patterns also affect results: a high-protein diet temporarily increases serum creatinine production, which can transiently lower estimated GFR. Diabetes and hypertension are the two leading causes of chronic kidney disease worldwide and disproportionately affect certain ethnic and socioeconomic groups, amplifying health disparities in kidney disease outcomes. The removal of the race coefficient from the CKD-EPI 2021 equation was a deliberate and important step toward more equitable kidney function assessment across all populations.',

    medicalDisclaimer:
      'This GFR calculator is provided for educational and informational purposes only and should not be used for clinical decision-making or as a substitute for professional medical advice, diagnosis, or treatment. GFR estimation equations have limitations and may not be accurate in all individuals, particularly those with extremes of age, body size, muscle mass, or nutritional status. The calculator provides an estimate based on serum creatinine and demographic factors, but accurate kidney function assessment requires comprehensive medical evaluation including review of other laboratory values, imaging studies, clinical symptoms, and medical history. A single GFR value does not diagnose kidney disease - diagnosis requires persistent reduction in GFR or evidence of kidney damage. Never make medication changes, start supplements, or alter your treatment plan based solely on GFR calculations without consulting your healthcare provider. Many common medications require dose adjustment based on kidney function, and improper dosing can be dangerous. If you have been diagnosed with kidney disease or have risk factors such as diabetes, hypertension, family history of kidney disease, or use of nephrotoxic medications, regular monitoring by a nephrologist or primary care physician is essential. Sudden changes in GFR may indicate acute kidney injury requiring urgent medical attention. This calculator does not replace laboratory testing, medical imaging, kidney biopsy, or professional clinical judgment. Always consult with qualified healthcare professionals including physicians, nephrologists, pharmacists, and dietitians for diagnosis, monitoring, and management of kidney conditions.',

    references: [
      'Levey AS, et al. A New Equation to Estimate Glomerular Filtration Rate. Ann Intern Med. 2009;150(9):604-612.',
      'Kidney Disease: Improving Global Outcomes (KDIGO) CKD Work Group. KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease. Kidney Int. 2024;105(4S):S117-S314.',
      'National Kidney Foundation. K/DOQI Clinical Practice Guidelines for Chronic Kidney Disease: Evaluation, Classification, and Stratification. Am J Kidney Dis. 2002;39(2 Suppl 1):S1-266.',
      'Inker LA, et al. New Creatinine- and Cystatin C-Based Equations to Estimate GFR without Race. N Engl J Med. 2021;385(19):1737-1749.',
      'Stevens LA, Levey AS. Measured GFR as a confirmatory test for estimated GFR. J Am Soc Nephrol. 2009;20(11):2305-2313.',
    ],

    tips: [
      'Have your GFR checked annually if you have diabetes, high blood pressure, heart disease, or a family history of kidney disease',
      'Stay well-hydrated before blood tests, as dehydration can falsely lower GFR results',
      'Inform your healthcare provider about all medications and supplements, as some can affect creatinine levels or kidney function',
      'Avoid high-protein meals and intense exercise for 24 hours before having creatinine blood tests, as these can temporarily elevate creatinine',
      'A single abnormal GFR result does not mean you have kidney disease - it should be repeated after 3 months for confirmation',
      'Monitor your GFR trends over time rather than focusing on individual values - consistent decline is more concerning than fluctuations',
      'Maintain healthy blood pressure (target < 130/80 mmHg for most people with CKD) and blood sugar levels to protect kidney function',
      'Reduce sodium intake to less than 2,300 mg per day, and consider reducing protein intake if advised by your healthcare provider',
      'Be cautious with over-the-counter pain medications (NSAIDs like ibuprofen) as they can harm kidneys, especially with long-term use',
    ],

    faqs: [
      {
        question: 'What is a normal GFR and does it change with age?',
        answer:
          'A normal GFR for young healthy adults is approximately 90-120 mL/min/1.73m², though the exact value varies by individual. GFR naturally declines with age at a rate of approximately 0.75-1 mL/min/1.73m² per year after age 40, even in healthy individuals without kidney disease. This age-related decline is due to normal aging processes including nephron loss, decreased renal blood flow, and structural changes in the kidneys. Therefore, a GFR of 70-75 might be considered normal for a healthy 80-year-old but would raise concerns in a 30-year-old. This is why GFR must be interpreted in the context of age and why elderly patients with GFR 60-89 may not have kidney disease unless other evidence of kidney damage is present. Children typically have higher GFR than adults, with values often exceeding 120 mL/min/1.73m². It\'s important to track GFR trends over time rather than comparing to population averages, as individual baseline varies considerably.',
      },
      {
        question: 'What causes low GFR and how can I improve it?',
        answer:
          'Low GFR can result from various causes including diabetes (the leading cause of kidney disease), high blood pressure, glomerulonephritis (kidney inflammation), polycystic kidney disease, prolonged urinary obstruction, recurrent kidney infections, and certain medications. Other factors include aging, cardiovascular disease, obesity, and family history of kidney disease. To improve or stabilize GFR, focus on controlling underlying conditions: maintain excellent blood sugar control if diabetic (HbA1c < 7%), keep blood pressure well-controlled (often < 130/80 mmHg), follow a kidney-friendly diet with appropriate protein and sodium restriction, stay well-hydrated, avoid nephrotoxic medications (especially NSAIDs), quit smoking, maintain a healthy weight, and exercise regularly. Certain medications like ACE inhibitors or ARBs can protect kidneys in people with diabetes or proteinuria, though they may initially cause a slight GFR decrease. In some cases, treating the underlying cause (such as removing a urinary obstruction or treating an autoimmune condition) can improve GFR. However, once kidney damage has occurred, the goal is often to slow progression rather than reverse damage, making early detection and intervention crucial.',
      },
      {
        question: 'How is GFR different from creatinine levels?',
        answer:
          'Serum creatinine and GFR are related but measure different aspects of kidney function. Creatinine is a waste product from muscle metabolism that is filtered by the kidneys and measured in blood (typically 0.6-1.2 mg/dL). Higher creatinine levels indicate worse kidney function because the kidneys aren\'t removing it effectively. However, creatinine alone doesn\'t account for age, sex, race, or body size. A muscular young man might have creatinine of 1.3 mg/dL and normal kidney function, while an elderly woman with the same creatinine might have significantly impaired kidney function due to lower muscle mass. GFR is calculated from creatinine using equations that adjust for these factors, providing a standardized measure of actual kidney filtration capacity. GFR is more accurate than creatinine alone for assessing kidney function and is the primary metric used to stage chronic kidney disease. Additionally, creatinine is an indirect marker - it only starts rising significantly once more than 50% of kidney function is lost, so normal creatinine doesn\'t guarantee normal kidney function. This is why GFR calculation is essential for detecting early kidney disease.',
      },
      {
        question: 'Why was race removed from newer GFR calculations?',
        answer:
          'The race coefficient in older GFR equations (multiplying by 1.159 for African American patients) was based on observations that Black individuals on average have slightly higher muscle mass and thus higher creatinine production. However, race is a social construct, not a biological category with clear genetic boundaries. Using race in medical equations raised significant concerns about health equity, as it could lead to underestimation of kidney disease in Black patients, potentially delaying diagnosis and treatment. Studies showed that the race coefficient was based on limited data and didn\'t account for the enormous genetic and phenotypic diversity within racial groups. In 2021, a National Kidney Foundation and American Society of Nephrology task force recommended new CKD-EPI equations without a race variable. These newer race-free equations perform similarly in accuracy to race-based equations and promote more equitable care. If needed, alternative markers like cystatin C (a protein not affected by muscle mass) can be measured for more accurate GFR estimation in individuals where creatinine-based equations may be less reliable.',
      },
      {
        question: 'When should I see a nephrologist about my GFR?',
        answer:
          'You should see a nephrologist (kidney specialist) if you have: GFR consistently below 60 mL/min/1.73m² (Stage 3 CKD or worse), GFR below 30 mL/min/1.73m² (Stage 4-5 CKD), rapid decline in GFR (>5 mL/min/1.73m² per year or >10 mL/min/1.73m² over 5 years), significant proteinuria (protein in urine, especially if >300 mg/day or urine albumin-to-creatinine ratio >300 mg/g), persistent abnormal urinalysis findings (blood in urine, abnormal kidney function tests), kidney disease with unclear cause, difficult-to-control blood pressure despite multiple medications, or hereditary kidney disease. Early referral to a nephrologist is associated with better outcomes, slower disease progression, and better preparation for potential dialysis or transplantation if needed. Primary care physicians can often manage Stages 1-2 CKD, but specialist care becomes increasingly important as kidney function declines. Even if your GFR is only mildly reduced, referral may be appropriate if you have diabetes, cardiovascular disease, or rapidly changing kidney function.',
      },
    ],
  },
  tr: {
    whatIs:
      'Glomerüler Filtrasyon Hızı (GFH), böbreklerinizin atık ürünleri kanınızdan ne kadar iyi filtrelediğini gösteren çok önemli bir ölçümdür. GFH, renal glomerüler kılcal damarlardan Bowman kapsülüne birim zamanda filtrelenen sıvı hacmini temsil eder ve tipik olarak mililitre/dakika/1.73 metrekare (mL/dk/1.73m²) olarak ölçülür. Böbrekler, her biri bir glomerül içeren nefron adı verilen yaklaşık bir milyon filtreleme birimi içerir. Bu glomerüller, temel proteinleri ve kan hücrelerini korurken atık ürünleri, fazla sıvıları ve toksinleri kan dolaşımından çıkarmak için sürekli çalışır. Sağlıklı yetişkinlerde normal GFH tipik olarak 90 mL/dk/1.73m² veya daha yüksektir, ancak bu yaşla birlikte doğal olarak azalır. GFH tahmini, küresel popülasyonun yaklaşık %10\'unu etkileyen kronik böbrek hastalığını (KBH) tespit etmek ve izlemek için gereklidir. GFH\'yi doğrudan ölçmek, zamanlanmış idrar toplama ve ekzojen belirteçlerin uygulanmasını içeren karmaşık prosedürler gerektirdiğinden, sağlık hizmeti sağlayıcıları tipik olarak serum kreatinin, yaş, cinsiyet ve ırka dayalı tahmin denklemleri kullanır. En yaygın kullanılan formüller arasında, özellikle 60\'ın üzerindeki GFH değerleri için eski MDRD (Renal Hastalıkta Diyet Modifikasyonu) denkleminden daha doğru kabul edilen CKD-EPI (Kronik Böbrek Hastalığı Epidemiyoloji İşbirliği) denklemi bulunur. GFH\'nizi anlamak, müdahalelerin ilerlemeyi yavaşlatabildiği ve diyaliz veya transplantasyon gerektiren kardiyovasküler hastalık, anemi, kemik hastalığı ve nihai böbrek yetmezliği gibi komplikasyonları önleyebildiği böbrek hastalığını erken belirlemeye yardımcı olur.',

    formulaDetails:
      'GFH, üç giriş değişkeni kullanan CKD-EPI 2021 denklemi ile tahmin edilmektedir: serum kreatinin konsantrasyonu, hasta yaşı ve biyolojik cinsiyet. CKD-EPI denkleminin 2021 revizyonu, eski 2009 versiyonunda yer alan ırk katsayısını bilinçli bir şekilde kaldırmıştır; zira çalışmalar, ırka dayalı ayarlamaların çeşitli popülasyonlarda doğru olmadığını ve belirli gruplarda tanıları sistematik olarak geciktirebileceğini ortaya koymuştur. Formülün matematiksel yapısı şu şekildedir: eGFH = 142 × min(Scr/κ, 1)^α × max(Scr/κ, 1)^(−1.200) × 0.9938^Yaş × (kadınsa 1.012); burada κ kadınlar için 0.7 erkekler için 0.9 ve α kadınlar için −0.241 erkekler için −0.302 değerini alır. Kreatinin, normal kas metabolizmasının bir ürünüdür; böbrekler onu, filtrasyon kapasitesiyle doğrudan orantılı bir hızda kandan temizler; bu durum serum kreatinini GFH tahmininde güvenilir ve pratik bir yardımcı gösterge hâline getirir. Sağlıklı yetişkinlerde normal eGFH değeri 90 mL/dk/1.73m² veya daha yüksek olarak tanımlanmıştır.',

    howToCalculate:
      'GFH hesaplaması, demografik faktörlerle birlikte serum kreatinin seviyelerine dayalı tahmin denklemleri kullanır. Büyük nefroloji organizasyonları tarafından şu anda önerilen CKD-EPI denklemi, çoğu hasta için en doğru tahminleri sağlar. CKD-EPI denklemi için formül, cinsiyete ve kreatinin seviyesine göre değişir. Kreatinin ≤ 0.7 mg/dL olan kadınlar için: GFH = 144 × (kreatinin/0.7)^(-0.329) × (0.993)^yaş. Kreatinin > 0.7 olan kadınlar için: GFH = 144 × (kreatinin/0.7)^(-1.209) × (0.993)^yaş. Kreatinin ≤ 0.9 olan erkekler için: GFH = 141 × (kreatinin/0.9)^(-0.411) × (0.993)^yaş. Kreatinin > 0.9 olan erkekler için: GFH = 141 × (kreatinin/0.9)^(-1.209) × (0.993)^yaş. Daha önce, Afro-Amerikan hastalar için 1.159\'luk ek bir faktör uygulanıyordu, ancak son kılavuzlar sağlık eşitliği konusundaki endişeler ve ırk kategorilerinin biyolojik değil sosyal temeli nedeniyle ırkı denklemden çıkarmayı önermektedir. Hesaplama, normal kas yıkımı tarafından üretilen bir atık ürünü olan serum kreatinini ölçmek için bir kan testi gerektirir. Kreatinin böbrekler tarafından filtrelenir, bu nedenle daha yüksek kan kreatinin seviyeleri daha düşük böbrek fonksiyonunu gösterir. Ancak, kreatinin üretimi kas kütlesine göre değişir, bu nedenle denklem yaş (yaşlı insanlar daha az kasa sahiptir) ve cinsiyet (erkekler tipik olarak daha fazla kas kütlesine sahiptir) için ayarlama yapar. Belirli popülasyonlarda daha doğru değerlendirme için, sistatin C gibi ek belirteçler CKD-EPI denklemine dahil edilebilir. MDRD denklemi, daha eski olmasına rağmen, bazı ortamlarda hala kullanılabilir: GFH = 175 × (kreatinin)^(-1.154) × (yaş)^(-0.203) × (kadınsa 0.742). Bu denklemler, çoğu durumda ölçülen GFH ile iyi korelasyon gösteren tahmini GFH (tGFH) değerleri sağlar, ancak doğruluk vücut boyutunun uçlarında, hamilelikte, ciddi yetersiz beslenmede veya hızla değişen böbrek fonksiyonunda azalabilir.',

    interpretation:
      'GFH sonuçları, Ulusal Böbrek Vakfı tarafından tanımlanan kronik böbrek hastalığının standartlaştırılmış aşamalarına göre yorumlanır. Aşama 1 (GFH ≥ 90 mL/dk/1.73m²) normal veya yüksek böbrek fonksiyonunu gösterir, ancak idrarda protein gibi diğer anormallikler varsa böbrek hasarı mevcut olabilir. Aşama 2 (GFH 60-89) böbrek fonksiyonunda hafif azalmayı temsil eder. Hem aşama 1 hem de 2, KBH teşhisi koymak için böbrek hasarı kanıtı (albüminüri, yapısal anormallikler veya genetik böbrek hastalığı gibi) gerektirir, çünkü GFH yaşla birlikte doğal olarak azalır. Aşama 3a (GFH 45-59) ve Aşama 3b (GFH 30-44) sırasıyla böbrek fonksiyonunda hafif ila orta ve orta ila şiddetli azalmayı temsil eder. Bu aşamalarda, hastalar nefroloji bakımı altında olmalı ve anemi, kemik hastalığı ve kardiyovasküler risk dahil komplikasyonlar için izlenmelidir. Aşama 4 (GFH 15-29) böbrek fonksiyonunda ciddi azalmayı gösterir, potansiyel renal replasman tedavisine hazırlık ve komplikasyonların agresif yönetimini gerektirir. Aşama 5 (GFH < 15) böbrek yetmezliğidir ve hayatta kalma için diyaliz veya böbrek nakli gerektirir. GFH azalma hızı da önemlidir - hızlı azalmalar (yılda >5 mL/dk/1.73m²) acil müdahale gerektiren ilerleyici böbrek hastalığını önerir. Böbrek hastalığının yanı sıra, dehidratasyon (GFH\'yi azaltır), yüksek protein alımı (GFH\'yi artırır), belirli ilaçlar (özellikle NSAİİ\'ler ve ACE inhibitörleri) ve akut hastalık dahil olmak üzere birkaç faktör GFH\'yi geçici olarak etkileyebilir. Bu nedenle, anormal GFH sonuçları tekrarlanmalı ve klinik bağlamda değerlendirilmelidir. GFH tahmin denklemlerinin çocuklar, hamile kadınlar, aşırı vücut boyutlarına sahip kişiler, olağandışı kas kütlesine sahip olanlar (vücut geliştiriciler veya ampüteler) ve belirli etnik gruplar dahil olmak üzere belirli popülasyonlarda daha az doğru olabileceğini de not etmek önemlidir.',

    healthRisks:
      'Düşük GFH ile yansıyan azalmış böbrek fonksiyonu, erken tespit edilmez ve yönetilmezse ciddi ve yaşamı tehdit eden komplikasyonlara yol açar. Kardiyovasküler olaylar — özellikle kalp krizi ve inme — kronik böbrek hastalığı (KBH) hastaları arasında ölümün önde gelen nedenidir ve genel nüfusa kıyasla iki ila beş kat daha yüksek bir oranla karşılaşılır. Böbrek filtrasyon kapasitesi azaldıkça sıvı ve elektrolit dengesi giderek tehlikeli bir hal alır: hiperkalemi (yüksek potasiyum) yaşamı tehdit eden kalp ritim bozuklukları tetikleyebilir, sıvı retansiyonu ise perifersel edema oluşturur ve mevcut kalp yetmezliğini daha da ağırlaştırır. Anemi gelişir; zira böbrekler, kırmızı kan hücrelerinin üretimi için zorunlu olan eritropoietin hormonu salgılar ve üretiminin azalması kronik yorgunluğa ve oksijeni doğru ileten azalmış kapasiteye neden olur. Renal osteodistrafi (böbrek disfonksiyonunun neden olduğu kemik hastalığı), iskelet sistemi üzerinde ciddi bir zayıflatıcı etki yaratır ve kırık riskini önemli ölçüde artırır. Metabolik asidoz, yani kanda asit birikimi, kardiyovasküler, solunumsal ve kas-iskelet sistemleri dahil olmak üzere birden fazla organ sistemini etkiler. Son dönem böbrek hastalığı (SDBH), GFH\'nın 15 mL/dk/1.73m²\'nin altına düşmesi ile tanımlanır; bu aşamada yaşamın sürdürülmesi için diyaliz veya böbrek nakli zorunludur. KBH genellikle ileri bir aşamaya ulaşana kadar asemptomatik kalır; bu nedenle düzenli izleme ile GFH düşüşünün erken fark edilmesi kritik önem taşır.',

    alternativeMeasures:
      'Sistatin C, böbrek fonksiyonu değerlendirmesi için anlamlı bir avantaj sunan alternatif bir biyobelirteçtir: sistatin C, tüm çekirdeğe sahip hücreler tarafından nispeten sabit bir hızda üretilir ve kas kütlesinden kayda değer biçimde etkilenmez. Bu özellik, sistatin C tabanlı GFH denklemlerini, anormal kas kütlesine sahip bireyler — yaşlılar, yetersiz beslenme durumundakiler veya son derece kaslı bireyler — için kreatinine dayalı yöntemlerden çok daha doğru kılar. Hem serum kreatinin hem de sistatin C kullanan denklemler, günümüzde mevcut en doğru eGFH tahminlerini sağlar ve tek belirteç denklemlerinin yeterli güvenilirlik sunmadığı durumlarda kılavuzlar tarafından önerilir. 24 saatlik idrar kreatinin klirensi yöntemi — 24 saat süresince üretilen tüm idrarın toplanarak kreatinin atılımının doğrudan ölçülmesi — böbrek fonksiyon ölçümünde klinik altın standart olarak kabul edilmektedir; ancak ciddi hasta yükü ve sık toplama hataları nedeniyle rutin klinik kullanım için elverişli değildir. İnülin klirensi, herhangi bir tahmin olmaksızın GFH\'yı ölçen gerçek fizyolojik altın standart olarak yalnızca araştırma ortamlarında kullanılır; ancak günlük klinik pratikte uygulanması mümkün değildir. Böbrek biyopsisi, GFH değerleri tek başına teşhis ve yönetim için yetersiz kalıyor olsa da, böbrek hastalığının altta yatan nedeni hakkında histolojik bilgi sağlar. Böbrek sağlığının en eksiksiz bir şekilde değerlendirilebilmesi için, kılavuzlar eGFH ile idrar albümin-kreatinin oranının (AKO) birlikte izlenmesini önerir; bu ikili yaklaşım, doğru aşamalandırma ve bireyselleştirilmiş risk stratifikasyonu imkânı tanır.',

    demographicDifferences:
      'Yaş, popülasyon genelinde GFH düşüşünün tek en güçlü belirleyicisidir: böbrek filtrasyon kapasitesi, 40 yaşından sonra yılda yaklaşık 1 mL/dk/1.73m² oranında doğal olarak azalır; bu durum, istatistiksel olarak yaşlı yetişkinlerin altta yatan bir böbrek hastalığı olmaksızın bile daha düşük eGFH kategorilerine düşme olasılığını artırır. GFH\'daki cinsiyet farklılıkları iyi belgelenmemiştir denilemez; aksine kadınlar tipik olarak aynı yaştaki erkeklere kıyasla biraz daha düşük bir GFH\'ya sahiptir; bunun başlıca nedeni, kadınların ortalama kas kütlesinin erkeklere göre daha düşük olması ve dolayısıyla daha az kreatinin üretmesidir. Bu paradoks, kreatinin tabanlı denklemlerin tek başına kullanıldığında kadınların gerçek GFH\'larından daha iyi bir tablo çizmesine yol açabilir. Kas kütlesi, kreatinin tabanlı GFH tahmininde önemli bir karıştırıcı faktördür: son derece kaslı bireyler, yüksek serum kreatinin düzeyleri nedeniyle azalmış böbrek fonksiyonuna sahipmiş gibi bir yanlış izlenim verebilirken, düşük kas kütlesine sahip bireyler, erken böbrek hasarını maskeleyebilecek yanlış normal bir eGFH değeri taşıyabilir. Beslenme alışkanlıkları da sonuçları etkiler: yüksek proteinli bir diyet, serum kreatinin üretimini geçici olarak artırır ve tahmini GFH\'yı transient olarak düşürür. Diyabet ve hipertansiyon, dünya genelinde kronik böbrek hastalığının başlıca iki nedenidir ve belirli etnik ile sosyoekonomik gruplarda orantısız biçimde yaygındır; bu durum, böbrek hastalığı sonuçlarında sağlık eşitsizliklerini derinleştirmektedir. CKD-EPI 2021 denkleminden ırk katsayısının çıkarılması, tüm popülasyonlar için daha adil bir böbrek fonksiyon değerlendirmesi yönündeki bilinçli ve önemli bir adımdı.',

    medicalDisclaimer:
      'Bu GFH hesaplayıcı yalnızca eğitim ve bilgilendirme amaçlıdır ve klinik karar verme veya profesyonel tıbbi tavsiye, teşhis veya tedavinin yerine kullanılmamalıdır. GFH tahmin denklemlerinin sınırlamaları vardır ve tüm bireylerde, özellikle yaş, vücut boyutu, kas kütlesi veya beslenme durumunun uçlarında olanlarda doğru olmayabilir. Hesaplayıcı, serum kreatinin ve demografik faktörlere dayalı bir tahmin sağlar, ancak doğru böbrek fonksiyon değerlendirmesi, diğer laboratuvar değerlerinin, görüntüleme çalışmalarının, klinik semptomların ve tıbbi geçmişin gözden geçirilmesi dahil kapsamlı tıbbi değerlendirme gerektirir. Tek bir GFH değeri böbrek hastalığını teşhis etmez - teşhis, GFH\'de kalıcı azalma veya böbrek hasarı kanıtı gerektirir. Yalnızca GFH hesaplamalarına dayanarak sağlık hizmeti sağlayıcınıza danışmadan asla ilaç değişiklikleri yapmayın, takviyeler başlatmayın veya tedavi planınızı değiştirmeyin. Birçok yaygın ilaç, böbrek fonksiyonuna göre doz ayarlaması gerektirir ve uygunsuz dozlama tehlikeli olabilir. Böbrek hastalığı teşhisi aldıysanız veya diyabet, hipertansiyon, böbrek hastalığı aile öyküsü veya nefrotoksik ilaç kullanımı gibi risk faktörleriniz varsa, bir nefrolog veya birinci basamak hekimi tarafından düzenli izleme gereklidir. GFH\'deki ani değişiklikler, acil tıbbi müdahale gerektiren akut böbrek hasarını gösterebilir. Bu hesaplayıcı, laboratuvar testinin, tıbbi görüntülemenin, böbrek biyopsisinin veya profesyonel klinik yargının yerini almaz. Böbrek durumlarının teşhisi, izlenmesi ve yönetimi için her zaman doktorlar, nefrologlar, eczacılar ve diyetisyenler dahil kalifiye sağlık profesyonellerine danışın.',

    references: [
      'Levey AS, ve ark. Glomerüler Filtrasyon Hızını Tahmin Etmek İçin Yeni Bir Denklem. Ann Intern Med. 2009;150(9):604-612.',
      'Böbrek Hastalığı: Küresel Sonuçları İyileştirme (KDIGO) KBH Çalışma Grubu. Kronik Böbrek Hastalığının Değerlendirilmesi ve Yönetimi için KDIGO 2024 Klinik Uygulama Kılavuzu. Kidney Int. 2024;105(4S):S117-S314.',
      'Ulusal Böbrek Vakfı. Kronik Böbrek Hastalığı için K/DOQI Klinik Uygulama Kılavuzları: Değerlendirme, Sınıflandırma ve Katmanlama. Am J Kidney Dis. 2002;39(2 Ek 1):S1-266.',
      'Inker LA, ve ark. Irk Olmadan GFH Tahmin Etmek İçin Yeni Kreatinin ve Sistatin C Tabanlı Denklemler. N Engl J Med. 2021;385(19):1737-1749.',
      'Stevens LA, Levey AS. Tahmini GFH için doğrulayıcı test olarak ölçülen GFH. J Am Soc Nephrol. 2009;20(11):2305-2313.',
    ],

    tips: [
      'Diyabetiniz, yüksek tansiyonunuz, kalp hastalığınız veya böbrek hastalığı aile öyküsü varsa GFH\'nizi yıllık olarak kontrol ettirin',
      'Dehidratasyon GFH sonuçlarını yanlış bir şekilde düşürebileceğinden, kan testlerinden önce iyi hidrate olun',
      'Bazıları kreatinin seviyelerini veya böbrek fonksiyonunu etkileyebileceğinden, tüm ilaçlar ve takviyeler hakkında sağlık hizmeti sağlayıcınızı bilgilendirin',
      'Kreatinin kan testleri yaptırmadan önce 24 saat boyunca yüksek proteinli yemeklerden ve yoğun egzersizden kaçının, çünkü bunlar kreatinini geçici olarak yükseltebilir',
      'Tek bir anormal GFH sonucu böbrek hastalığınız olduğu anlamına gelmez - doğrulama için 3 ay sonra tekrarlanmalıdır',
      'Bireysel değerlere odaklanmak yerine zaman içinde GFH eğilimlerinizi izleyin - tutarlı düşüş dalgalanmalardan daha endişe vericidir',
      'Böbrek fonksiyonunu korumak için sağlıklı kan basıncı (KBH\'li çoğu insan için hedef < 130/80 mmHg) ve kan şekeri seviyelerini koruyun',
      'Günde 2,300 mg\'dan az sodyum alımını azaltın ve sağlık hizmeti sağlayıcınız tavsiye ederse protein alımını azaltmayı düşünün',
      'Reçetesiz ağrı kesicilerle (ibuprofen gibi NSAİİ\'ler) dikkatli olun, çünkü bunlar özellikle uzun süreli kullanımda böbreklere zarar verebilir',
    ],

    faqs: [
      {
        question: 'Normal GFH nedir ve yaşla birlikte değişir mi?',
        answer:
          'Genç sağlıklı yetişkinler için normal GFH yaklaşık 90-120 mL/dk/1.73m²\'dir, ancak tam değer bireye göre değişir. GFH, böbrek hastalığı olmayan sağlıklı bireylerde bile 40 yaşından sonra yılda yaklaşık 0.75-1 mL/dk/1.73m² oranında yaşla birlikte doğal olarak azalır. Bu yaşla ilişkili düşüş, nefron kaybı, azalmış renal kan akışı ve böbreklerdeki yapısal değişiklikler dahil normal yaşlanma süreçlerinden kaynaklanır. Bu nedenle, 70-75\'lik bir GFH sağlıklı bir 80 yaşındaki için normal kabul edilebilirken, 30 yaşındaki birinde endişe yaratır. Bu nedenle GFH yaş bağlamında yorumlanmalı ve yaşlı hastalarda GFH 60-89, böbrek hasarının başka kanıtı olmadıkça böbrek hastalığına sahip olmayabilir. Çocuklar tipik olarak yetişkinlerden daha yüksek GFH\'ye sahiptir ve değerler genellikle 120 mL/dk/1.73m²\'yi aşar. Bireysel taban çizgisi oldukça değişiklik gösterdiğinden, popülasyon ortalamalarıyla karşılaştırmak yerine zaman içinde GFH eğilimlerini takip etmek önemlidir.',
      },
      {
        question: 'Düşük GFH\'ye ne sebep olur ve nasıl iyileştirebilirim?',
        answer:
          'Düşük GFH, diyabet (böbrek hastalığının önde gelen nedeni), yüksek tansiyon, glomerülonefrit (böbrek iltihabı), polikistik böbrek hastalığı, uzun süreli idrar tıkanıklığı, tekrarlayan böbrek enfeksiyonları ve belirli ilaçlar dahil olmak üzere çeşitli nedenlerden kaynaklanabilir. Diğer faktörler yaşlanma, kardiyovasküler hastalık, obezite ve böbrek hastalığı aile öyküsünü içerir. GFH\'yi iyileştirmek veya stabilize etmek için, altta yatan durumları kontrol etmeye odaklanın: diyabetikseniz mükemmel kan şekeri kontrolünü sağlayın (HbA1c < %7), kan basıncını iyi kontrol altında tutun (genellikle < 130/80 mmHg), uygun protein ve sodyum kısıtlaması ile böbrek dostu bir diyet uygulayın, iyi hidrate olun, nefrotoksik ilaçlardan (özellikle NSAİİ\'lerden) kaçının, sigarayı bırakın, sağlıklı bir kilo koruyun ve düzenli egzersiz yapın. ACE inhibitörleri veya ARB\'ler gibi belirli ilaçlar, başlangıçta hafif bir GFH düşüşüne neden olsalar da, diyabeti veya proteinürisi olan kişilerde böbrekleri koruyabilir. Bazı durumlarda, altta yatan nedeni tedavi etmek (idrar tıkanıklığını kaldırmak veya bir otoimmün durumu tedavi etmek gibi) GFH\'yi iyileştirebilir. Ancak, böbrek hasarı meydana geldikten sonra, hedef genellikle hasarı tersine çevirmek yerine ilerlemeyi yavaşlatmaktır, bu da erken tespit ve müdahaleyi çok önemli kılar.',
      },
      {
        question: 'GFH kreatinin seviyelerinden nasıl farklıdır?',
        answer:
          'Serum kreatinin ve GFH ilişkilidir ancak böbrek fonksiyonunun farklı yönlerini ölçer. Kreatinin, böbrekler tarafından filtrelenen ve kanda ölçülen kas metabolizmasından bir atık üründür (tipik olarak 0.6-1.2 mg/dL). Daha yüksek kreatinin seviyeleri, böbrekler onu etkili bir şekilde uzaklaştırmadığından daha kötü böbrek fonksiyonunu gösterir. Ancak, kreatinin tek başına yaş, cinsiyet, ırk veya vücut boyutunu hesaba katmaz. Kaslı bir genç adam 1.3 mg/dL kreatinine sahip olabilir ve normal böbrek fonksiyonuna sahip olabilirken, aynı kreatinine sahip yaşlı bir kadın daha düşük kas kütlesi nedeniyle önemli ölçüde bozulmuş böbrek fonksiyonuna sahip olabilir. GFH, bu faktörlere göre ayarlama yapan denklemler kullanarak kreatininden hesaplanır ve gerçek böbrek filtrasyon kapasitesinin standartlaştırılmış bir ölçüsünü sağlar. GFH, böbrek fonksiyonunu değerlendirmek için kreatininden tek başına daha doğrudur ve kronik böbrek hastalığını aşamalandırmak için kullanılan birincil metriktir. Ek olarak, kreatinin dolaylı bir belirteçtir - böbrek fonksiyonunun %50\'sinden fazlası kaybolduğunda önemli ölçüde yükselmeye başlar, bu nedenle normal kreatinin normal böbrek fonksiyonunu garanti etmez. Bu nedenle erken böbrek hastalığını tespit etmek için GFH hesaplaması gereklidir.',
      },
      {
        question: 'Irk neden daha yeni GFH hesaplamalarından çıkarıldı?',
        answer:
          'Eski GFH denklemlerindeki ırk katsayısı (Afro-Amerikan hastalar için 1.159 ile çarpma), Siyah bireylerin ortalama olarak biraz daha yüksek kas kütlesine ve dolayısıyla daha yüksek kreatinin üretimine sahip olduğu gözlemlerine dayanıyordu. Ancak, ırk sosyal bir yapıdır, net genetik sınırları olan biyolojik bir kategori değildir. Tıbbi denklemlerde ırk kullanmak, Siyah hastalarda böbrek hastalığının küçümsenmesine yol açabileceğinden, potansiyel olarak teşhis ve tedaviyi geciktirerek sağlık eşitliği konusunda önemli endişeler yarattı. Çalışmalar, ırk katsayısının sınırlı verilere dayandığını ve ırk grupları içindeki muazzam genetik ve fenotipik çeşitliliği hesaba katmadığını gösterdi. 2021\'de, bir Ulusal Böbrek Vakfı ve Amerikan Nefroloji Derneği görev gücü ırk değişkeni olmayan yeni CKD-EPI denklemleri önerdi. Bu yeni ırksız denklemler, ırk tabanlı denklemlere benzer doğrulukta performans gösterir ve daha eşitlikçi bakımı teşvik eder. Gerekirse, kreatinin tabanlı denklemlerin daha az güvenilir olabileceği bireylerde daha doğru GFH tahmini için sistatin C (kas kütlesinden etkilenmeyen bir protein) gibi alternatif belirteçler ölçülebilir.',
      },
      {
        question: 'GFH\'m hakkında ne zaman bir nefrologa görünmeliyim?',
        answer:
          'Aşağıdaki durumlarda bir nefrologa (böbrek uzmanı) görünmelisiniz: GFH sürekli olarak 60 mL/dk/1.73m²\'nin altında (Aşama 3 KBH veya daha kötü), GFH 30 mL/dk/1.73m²\'nin altında (Aşama 4-5 KBH), GFH\'de hızlı düşüş (yılda >5 mL/dk/1.73m² veya 5 yılda >10 mL/dk/1.73m²), önemli proteinüri (idrarda protein, özellikle >300 mg/gün veya idrar albümin-kreatinin oranı >300 mg/g ise), kalıcı anormal idrar tahlili bulguları (idrarda kan, anormal böbrek fonksiyon testleri), nedeni belirsiz böbrek hastalığı, birden fazla ilaca rağmen kontrol edilmesi zor yüksek tansiyon veya kalıtsal böbrek hastalığı. Nefrologa erken sevk, daha iyi sonuçlar, daha yavaş hastalık ilerlemesi ve gerekirse potansiyel diyaliz veya transplantasyon için daha iyi hazırlık ile ilişkilidir. Birinci basamak hekimleri genellikle Aşama 1-2 KBH\'yi yönetebilir, ancak böbrek fonksiyonu azaldıkça uzman bakımı giderek daha önemli hale gelir. GFH\'niz sadece hafif azalmış olsa bile, diyabet, kardiyovasküler hastalık veya hızla değişen böbrek fonksiyonunuz varsa sevk uygun olabilir.',
      },
    ],
  },
};
